// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package main

// XXX using a table with version or size delimiters as a field in another table
// doesn't compute sizes correctly. it's fine, OpenType doesn't do that.

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		// We need syntax to get access to unexported types
		Mode: packages.NeedTypes | packages.NeedSyntax,
	}
	pkgs, err := packages.Load(cfg, "honnef.co/go/gutter/opentype/internal/tables")
	if err != nil {
		log.Fatal(err)
	}

	if len(pkgs) != 1 {
		log.Fatal("expected 1 package, found", len(pkgs))
	}

	type buffer struct {
		buf          bytes.Buffer
		extraImports map[string]struct{}
	}
	bufs := map[string]*buffer{}
	getBuf := func(pos token.Pos) *buffer {
		name := path.Base(pkgs[0].Fset.PositionFor(pos, false).Filename)
		buf, ok := bufs[name]
		if ok {
			return buf
		}
		buf = &buffer{}
		bufs[name] = buf
		return buf
	}

	scope := pkgs[0].Types.Scope()
	for _, name := range scope.Names() {
		obj, ok := scope.Lookup(name).(*types.TypeName)
		if !ok {
			continue
		}

		if _, ok := obj.Type().Underlying().(*types.Struct); !ok {
			continue
		}

		g := &generator{rawPkg: pkgs[0].Types, fset: pkgs[0].Fset}
		buf := getBuf(obj.Pos())
		g.writeParsers(&buf.buf, obj)
		fmt.Fprintln(&buf.buf)

		if buf.extraImports == nil {
			buf.extraImports = map[string]struct{}{}
		}
		for imp := range g.extraImports {
			buf.extraImports[imp] = struct{}{}
		}
	}

	// This destructively modifies the AST to remove struct fields we don't want in the
	// generated API.
	for _, f := range pkgs[0].Syntax {
		// Don't include types.go
		if path.Base(pkgs[0].Fset.PositionFor(f.Pos(), false).Filename) == "types.go" {
			continue
		}

		// Change package name
		f.Name.Name = "opentype"

		decls := f.Decls[:0]
		for _, decl := range f.Decls {
			gdecl, ok := decl.(*ast.GenDecl)
			// Drop import opentype package
			if ok && gdecl.Tok == token.IMPORT {
				specs := gdecl.Specs[:0]
				for _, spec := range gdecl.Specs {
					p, _ := strconv.Unquote(spec.(*ast.ImportSpec).Path.Value)
					if p == "honnef.co/go/gutter/opentype" {
						continue
					}
					specs = append(specs, spec)
				}
				gdecl.Specs = specs

				// Don't add empty import block
				if len(specs) == 0 {
					continue
				}
			}

			decls = append(decls, decl)

			// Remove unwanted fields and strip field tags
			if !ok || gdecl.Tok != token.TYPE {
				continue
			}
			typ, ok := gdecl.Specs[0].(*ast.TypeSpec).Type.(*ast.StructType)
			if !ok {
				continue
			}
			fields := typ.Fields.List[:0]
			for _, f := range typ.Fields.List {
				if f.Names[0].Name[0] == '_' {
					continue
				}
				if f.Tag != nil {
					tag, _ := strconv.Unquote(f.Tag.Value)
					if parseTag(tag).command == "omit" {
						continue
					}
				}
				f.Tag = nil
				fields = append(fields, f)
			}
			typ.Fields.List = fields
		}
		f.Decls = decls
	}

	// Insert extra imports
	for _, f := range pkgs[0].Syntax {
		// Don't include types.go
		if path.Base(pkgs[0].Fset.PositionFor(f.Pos(), false).Filename) == "types.go" {
			continue
		}

		buf := getBuf(f.Pos())
		var nodes []ast.Decl
		for imp := range buf.extraImports {
			nodes = append(nodes, &ast.GenDecl{
				Tok: token.IMPORT,
				Specs: []ast.Spec{
					&ast.ImportSpec{
						Path: &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(imp)},
					},
				},
			})
		}
		f.Decls = slices.Insert(f.Decls, 0, nodes...)
	}

	for _, af := range pkgs[0].Syntax {
		// Don't include types.go
		name := path.Base(pkgs[0].Fset.PositionFor(af.Pos(), false).Filename)
		if name == "types.go" {
			continue
		}

		dst := name[:len(name)-len(filepath.Ext(name))] + "_gen.go"
		f, err := os.Create(dst)
		if err != nil {
			log.Fatal(err)
		}

		fmt.Fprintln(f, "// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.")
		fmt.Fprintln(f)

		// Write transformed type definitions
		{
			var bufTypes bytes.Buffer
			if err := format.Node(&bufTypes, pkgs[0].Fset, af); err != nil {
				log.Fatal(err)
			}
			// This is a nasty way of turning qualified identifiers into unqualified ones.
			b := bytes.ReplaceAll(bufTypes.Bytes(), []byte("opentype."), []byte(""))
			b, err := format.Source(b)
			if err != nil {
				log.Fatal(err)
			}
			if _, err := f.Write(b); err != nil {
				log.Fatal(err)
			}
		}

		// Write generated parsers
		{
			bufParsers := getBuf(af.Pos()).buf
			b := bytes.ReplaceAll(bufParsers.Bytes(), []byte("*&"), []byte(""))
			b, err := format.Source(b)
			if err != nil {
				log.Fatal(err)
			}

			if _, err := f.Write(b); err != nil {
				log.Fatal(err)
			}
		}

		f.Close()

	}
}

type generator struct {
	fset         *token.FileSet
	rawPkg       *types.Package
	extraImports map[string]struct{}
}

func qualifiedName(typ *types.Named) string {
	if pkg := typ.Obj().Pkg(); pkg != nil {
		return pkg.Path() + "." + typ.Obj().Name()
	} else {
		return typ.Obj().Name()
	}
}

func (g *generator) addImport(name string) {
	if g.extraImports == nil {
		g.extraImports = map[string]struct{}{}
	}
	g.extraImports[name] = struct{}{}
}

func (g *generator) writeParsers(out io.Writer, obj *types.TypeName) {
	rawStruct, ok := obj.Type().Underlying().(*types.Struct)
	if !ok {
		return
	}

	dstFields := map[string]struct{}{}
	for i := range rawStruct.NumFields() {
		f := rawStruct.Field(i)
		if f.Name()[0] == '_' {
			continue
		}

		tag := parseTag(rawStruct.Tag(i))
		if tag.command == "omit" {
			continue
		}

		dstFields[f.Name()] = struct{}{}
	}
	dstHasField := func(name string) bool {
		_, ok := dstFields[name]
		return ok
	}
	fieldHandle := func(field string) string {
		if _, ok := dstFields[field]; ok {
			return "out." + field
		} else {
			return field
		}
	}

	rawFields := make([]field, rawStruct.NumFields())
	hasData := dstHasField("data")
	hasParentData := dstHasField("parentData")
	for i := range rawStruct.NumFields() {
		var fieldInfo field
		field := rawStruct.Field(i)
		if field.Name() == "data" || field.Name() == "parentData" {
			continue
		}

		fieldInfo.field = field
		fieldInfo.size, _ = g.elemSize(field.Type())
		fieldInfo.parser = g.parse(field.Type())

		if field.Name() == "MajorVersion" {
			tag := reflect.StructTag(rawStruct.Tag(i)).Get("gen")
			max, err := strconv.Atoi(tag)
			if err != nil {
				panic(err)
			}
			fieldInfo.maxSupportedVersion = max
		}
		if field.Name() == "MinorVersion" {
			tag := reflect.StructTag(rawStruct.Tag(i)).Get("gen")
			if tag == "version16dot16" {
				fieldInfo.versionIsWeird = true
			}
		}

		if named, ok := field.Type().(*types.Named); ok && qualifiedName(named) == "honnef.co/go/gutter/opentype/internal/tables.versionDelimiter" {
			tag := reflect.StructTag(rawStruct.Tag(i)).Get("gen")
			fieldInfo.isVersionDelimiter = true
			if strings.Contains(tag, ".") {
				parts := strings.SplitN(tag, ".", 2)
				major, err := strconv.Atoi(parts[0])
				if err != nil {
					panic(err)
				}
				minor, err := strconv.Atoi(parts[1])
				if err != nil {
					panic(err)
				}
				fieldInfo.delimVersionMajor = major
				fieldInfo.delimVersionMinor = minor
			} else {
				vers, err := strconv.Atoi(tag)
				if err != nil {
					panic(err)
				}
				fieldInfo.delimVersion = vers
			}
		}
		if named, ok := field.Type().(*types.Named); ok && qualifiedName(named) == "honnef.co/go/gutter/opentype/internal/tables.sizeDelimiter" {
			fieldInfo.isSizeDelimiter = true
		}

		if fieldInfo.size == -1 {
			// Slice
			fieldInfo.isSlice = true

			switch typ := types.Unalias(fieldInfo.field.Type()).(type) {
			case *types.Slice:
				if !types.Identical(typ.Elem().Underlying(), types.Typ[types.Byte]) {
					log.Fatalf("unsupported slice element type %q", typ.Elem())
				}
				fieldInfo.sliceInfo.elem = typ.Elem()
				if !types.Identical(typ.Elem(), types.Typ[types.Byte]) {
					fieldInfo.sliceInfo.typedByteSlice = true
				}
			case *types.Named:
				if name := qualifiedName(typ); name != "honnef.co/go/gutter/opentype.Slice" {
					log.Fatalf("unsupported named slice type %q", name)
				}
				fieldInfo.sliceInfo.elem = typ.TypeArgs().At(0)
			default:
				log.Fatalf("unsupported type %q", typ)
			}

			tag := parseTag(rawStruct.Tag(i))
			if tag.command == "slice" {
				si := &fieldInfo.sliceInfo
				si.offset = tag.args["offset"]
				if count, ok := tag.args["count"]; ok {
					si.numElements = []string{count}
				} else if count, ok := tag.args["2dcount"]; ok {
					si.numElements = strings.Split(count, ";")
				}
				si.singular = tag.args["singular"]

				if sz, ok := tag.args["size"]; ok {
					// The element size is specified by a field and is different from the
					// element type's size. This is the case for the design axes in the
					// STAT table, for example.
					fieldInfo.sliceInfo.elemSizeField = sz
				}
			}

			if len(fieldInfo.sliceInfo.numElements) == 0 {
				if i == 0 {
					log.Fatalf("slice has no count and no previous field")
				} else {
					f := rawStruct.Field(i - 1)
					if typ, ok := f.Type().(*types.Basic); ok {
						if (typ.Info() & types.IsInteger) == 0 {
							log.Fatalf("field before slice is not an integer")
						}
					} else {
						log.Fatalf("field before slice is not an integer")
					}
					fieldInfo.sliceInfo.numElements = []string{rawStruct.Field(i - 1).Name()}
				}
			}

			if fieldInfo.sliceInfo.elemSizeField == "" {
				var dynamic bool
				fieldInfo.sliceInfo.elemSize, dynamic = g.elemSize(fieldInfo.sliceInfo.elem)
				if dynamic {
					panic("slices of dynamic type lengths are unsupported")
				}
			}
		}

		tag := parseTag(rawStruct.Tag(i))
		if tag.command == "union" {
			fieldInfo.union.field = tag.args[0]
			fieldInfo.union.version, _ = strconv.Atoi(tag.args[1])
		}

		rawFields[i] = fieldInfo
	}

	var hasUnion bool
	for _, f := range rawFields {
		if f.union.field != "" {
			hasUnion = true
		} else if hasUnion {
			log.Fatalf("non-union field following union field")
		}
	}

	fieldGroups := make([]fieldGroup, 1)
	curGrp := &fieldGroups[0]
	curSz := 0
	curStart := 0
fieldLoop:
	for i := range rawFields {
		f := &rawFields[i]
		switch {
		case f.isSizeDelimiter:
			curGrp.minSize = curSz
			curSz = 0
			fieldGroups = append(fieldGroups, fieldGroup{})
			curGrp = &fieldGroups[len(fieldGroups)-1]
			curGrp.start = curStart
			curGrp.optional = true
		case f.isVersionDelimiter:
			curGrp.minSize = curSz
			curSz = 0
			fieldGroups = append(fieldGroups, fieldGroup{})
			curGrp = &fieldGroups[len(fieldGroups)-1]
			curGrp.minVersion = f.delimVersion
			curGrp.minVersionMajor = f.delimVersionMajor
			curGrp.minVersionMinor = f.delimVersionMinor
			curGrp.start = curStart
		case f.isSlice:
			curGrp.fields = append(curGrp.fields, f)
			curGrp.minSize = curSz
			curSz = 0
			fieldGroups = append(fieldGroups, fieldGroup{})
			curGrp = &fieldGroups[len(fieldGroups)-1]
			curGrp.start = 0
			curStart = 0
		case f.union.field != "":
			curGrp.minSize = curSz
			curSz = 0
			fieldGroups = append(fieldGroups, fieldGroup{})
			curGrp = &fieldGroups[len(fieldGroups)-1]
			curGrp.start = curStart
			curGrp.union = f.union.field
			for j := range rawFields[i:] {
				curGrp.fields = append(curGrp.fields, &rawFields[i+j])
			}
			break fieldLoop
		default:
			curGrp.fields = append(curGrp.fields, f)
			curStart += f.size
		}
		if f.size > 0 {
			curSz += f.size
		}
	}
	curGrp.minSize = curSz

	var parserFnName string
	if strings.HasSuffix(obj.Name(), "Table") || strings.HasSuffix(obj.Name(), "Directory") {
		parserFnName = "Parse" + obj.Name()
	} else {
		parserFnName = "parse" + obj.Name()
	}

	if obj_ := g.rawPkg.Scope().Lookup(parserFnName); obj_ == nil || path.Base(g.fset.PositionFor(obj_.Pos(), false).Filename) == "types.go" {
		var parentBufArg string
		if strings.HasSuffix(obj.Name(), "Table") || strings.HasSuffix(obj.Name(), "Directory") {
			parentBufArg = "buf"
			fmt.Fprintf(out, "func Parse%s(buf []byte, out *%s) int {\n", obj.Name(), obj.Name())
		} else {
			if hasParentData {
				parentBufArg = "parentBuf"
				fmt.Fprintf(out, "func parse%s(buf, parentBuf []byte, out *%s) int {\n", obj.Name(), obj.Name())
			} else {
				fmt.Fprintf(out, "func parse%s(buf []byte, out *%s) int {\n", obj.Name(), obj.Name())
			}
		}

		fmt.Fprintf(out, "*out = %s{}\n", obj.Name())
		fmt.Fprintln(out, "origBuf := buf")
		fmt.Fprintln(out, "var dynSize int")
		for _, f := range rawFields {
			if f.field == nil || f.field.Name()[0] == '_' {
				continue
			}
			if !dstHasField(f.field.Name()) {
				fmt.Fprintf(out, "var %s %s\n", f.field.Name(), types.TypeString(f.field.Type(), func(p *types.Package) string { return "" }))
			}
		}
		if hasData {
			fmt.Fprintln(out, "out.data = buf")
		}
		if hasParentData {
			fmt.Fprintln(out, "out.parentData = parentBuf")
		}

		for _, grp := range fieldGroups {
			start := grp.start
			fmt.Fprintln(out)
			if grp.minVersion > 0 {
				fmt.Fprintf(out, "if %s < %d { return dynSize }\n", fieldHandle("Version"), grp.minVersion)
			}
			if grp.minVersionMajor > 0 {
				fmt.Fprintf(out, "if %s < %d { return dynSize }\n", fieldHandle("MajorVersion"), grp.minVersionMajor)
			}
			if grp.minVersionMinor > 0 {
				fmt.Fprintf(out, "if %s == %d && %s < %d { return dynSize }\n",
					fieldHandle("MajorVersion"), grp.minVersionMajor, fieldHandle("MinorVersion"), grp.minVersionMinor)
			}
			if grp.minSize > 0 {
				if !grp.optional {
					fmt.Fprintln(out, "/* FIXME return error */")
				}
				fmt.Fprintf(out, "if len(buf) < %d { return dynSize }\n", grp.start+grp.minSize)
			}
			if grp.union != "" {
				fmt.Fprintf(out, "switch %s {\n", fieldHandle(grp.union))
				for _, f := range grp.fields {
					if f.isSlice {
						log.Fatalf("union can't contain slices")
					}
					if f.field == nil {
						continue
					}

					fmt.Fprintf(out, "case %d:\n", f.union.version)

					if f.parser.dynamic {
						call := f.parser.fn(fmt.Sprintf("buf[%d:]", grp.start), parentBufArg, fmt.Sprintf("&%s", fieldHandle(f.field.Name())))
						fmt.Fprintf(out, "dynSize += %s\n", call)
					} else {
						fmt.Fprintln(out, f.parser.fn(fmt.Sprintf("buf[%d:%d]", grp.start, grp.start+f.size), parentBufArg, fmt.Sprintf("&%s", fieldHandle(f.field.Name()))))
					}
				}
				fmt.Fprintln(out, "}")
			} else {
				for _, f := range grp.fields {
					if f.field == nil {
						continue
					}

					if f.isSlice {
						fmt.Fprintln(out, "{")
						var elemSize string
						if f.sliceInfo.elemSizeField != "" {
							fmt.Fprintf(out, "sz := int(%s)\n", fieldHandle(f.sliceInfo.elemSizeField))
							elemSize = "sz"
						} else {
							elemSize = strconv.Itoa(f.sliceInfo.elemSize)
						}
						dst := fieldHandle(f.field.Name())
						convertSlice := func(s string) string {
							if f.sliceInfo.typedByteSlice {
								return fmt.Sprintf(`sliceCast[%s](%s)`, f.sliceInfo.elem.(*types.Named).Obj().Name(), s)
							} else {
								return s
							}
						}
						if f.sliceInfo.numElements[0] == "-1" {
							var s string
							if f.sliceInfo.offset != "" {
								if hasParentData {
									s = fmt.Sprintf("parentBuf[int(%s):]", fieldHandle(f.sliceInfo.offset))
								} else {
									s = fmt.Sprintf("origBuf[int(%s):]", fieldHandle(f.sliceInfo.offset))
								}
							} else {
								s = fmt.Sprintf("buf[%d:]", start)
							}
							s = convertSlice(s)
							fmt.Fprintf(out, "%s = %s\n", dst, s)
						} else {
							if n, err := strconv.Atoi(f.sliceInfo.numElements[0]); err == nil {
								fmt.Fprintf(out, "n := %d\n", n)
							} else {
								switch n := len(f.sliceInfo.numElements); n {
								case 1:
									fmt.Fprintf(out, "n := int(%s)\n", fieldHandle(f.sliceInfo.numElements[0]))
								case 2:
									fmt.Fprintf(out, "n := int(%s) * int(%s)\n", fieldHandle(f.sliceInfo.numElements[0]), fieldHandle(f.sliceInfo.numElements[1]))
								default:
									panic(n)
								}
							}
							sz := fmt.Sprintf("n*%s", elemSize)
							if f.sliceInfo.offset != "" {
								fmt.Fprintf(out, "start := int(%s)\n", fieldHandle(f.sliceInfo.offset))
								start := "start"
								fmt.Fprintln(out, "/* FIXME: check that buf is long enough */")
								var s string
								if hasParentData {
									s = fmt.Sprintf("parentBuf[%s:%s+%s]", start, start, sz)
								} else {
									s = fmt.Sprintf("origBuf[%s:%s+%s]", start, start, sz)
								}
								s = convertSlice(s)
								fmt.Fprintf(out, "%s = %s\n", dst, s)
							} else {
								fmt.Fprintln(out, "/* FIXME: check that buf is long enough */")
								s := fmt.Sprintf("buf[%d:%d+%s]", start, start, sz)
								s = convertSlice(s)
								fmt.Fprintf(out, "%s = %s\n", dst, s)
								fmt.Fprintf(out, "dynSize += %s\n", sz)
								fmt.Fprintf(out, "buf = buf[%d+%s:]\n", start, sz)
								start = 0
							}
						}
						fmt.Fprintln(out, "}")
					} else {
						if f.parser.dynamic {
							call := f.parser.fn(fmt.Sprintf("buf[%d:]", start), "parentBuf", fmt.Sprintf("&%s", fieldHandle(f.field.Name())))
							fmt.Fprintln(out, "{")
							fmt.Fprintf(out, "n := %s\n", call)
							fmt.Fprintln(out, "dynSize += n")
							fmt.Fprintf(out, "buf = buf[%d+%d+n:]\n", start, f.size)
							fmt.Fprintln(out, "}")
							start = 0
						} else {
							if f.field.Name()[0] != '_' {
								if f.field.Name() == "MinorVersion" && f.versionIsWeird {
									fmt.Fprintf(out, "parseWeirdMinorVersion(buf[%d:%d], &%s)\n", start, start+f.size, fieldHandle(f.field.Name()))
								} else {
									fmt.Fprintln(out, f.parser.fn(fmt.Sprintf("buf[%d:%d]", start, start+f.size), "parentBuf", fmt.Sprintf("&%s", fieldHandle(f.field.Name()))))
								}

								if f.field.Name() == "MajorVersion" {
									fmt.Fprintln(out, "/* XXX return error */")
									fmt.Fprintf(out, "if out.MajorVersion > %d { return dynSize }\n", f.maxSupportedVersion)
								}
							}
							start += f.size
						}
					}
				}
			}
		}

		// Make sure the last reslice of buf is always used, to silence SA4006
		fmt.Fprintln(out, "_ = buf")
		fmt.Fprintln(out, "_ = origBuf")
		fmt.Fprintln(out, "return dynSize")
		fmt.Fprintln(out, "}")
	}

	elemName := func(typ types.Type) string {
		switch typ := typ.(type) {
		case *types.Named:
			// This assumes that we only refer to types that will belong to the opentype
			// package.
			return typ.Obj().Name()
		case *types.Basic:
			return typ.Name()
		default:
			panic(fmt.Sprintf("unreachable: %T", typ))
		}
	}
	for _, f := range rawFields {
		if f.field == nil {
			continue
		}

		if fieldName := f.field.Name(); !ast.IsExported(fieldName) && strings.HasSuffix(fieldName, "Offset") {
			if named, ok := f.field.Origin().Type().(*types.Named); ok &&
				(qualifiedName(named) == "honnef.co/go/gutter/opentype.Offset16" || qualifiedName(named) == "honnef.co/go/gutter/opentype.Offset32") {
				targ := named.TypeArgs().At(0)
				if _, ok := targ.Underlying().(*types.Interface); !ok {
					fmt.Fprintf(out, "func (tbl *%s) %s(into *%s) bool {\n", obj.Name(), title(strings.TrimSuffix(fieldName, "Offset")), elemName(targ))
					var parentData string
					if hasParentData {
						parentData = "tbl.parentData"
					} else if hasData {
						parentData = "tbl.data"
					} else {
						log.Fatalf("couldn't generate getter for %s because of missing parent data", f.field)
					}
					fmt.Fprintln(out, "// FIXME: check bounds")
					fmt.Fprintf(out, "if tbl.%s == 0 { return false }\n", fieldName)
					fmt.Fprintln(out, g.parse(targ).fn(fmt.Sprintf("%s[tbl.%s:]", parentData, fieldName), "parentData", "into"))
					fmt.Fprintln(out, "return true")
					fmt.Fprintln(out, "}")
					fmt.Fprintln(out)
				}
			}
		}

		if !f.isSlice {
			continue
		}
		if types.Identical(f.sliceInfo.elem.Underlying(), types.Typ[types.Byte]) {
			continue
		}

		fmt.Fprintln(out)
		getterFnName := f.field.Name()
		if f.sliceInfo.singular != "" {
			getterFnName = f.sliceInfo.singular
		} else if before, ok0 := strings.CutSuffix(getterFnName, "s"); ok0 {
			getterFnName = title(before)
		} else {
			getterFnName = "Get" + title(getterFnName)
		}
		var parentData string
		if hasParentData {
			parentData = "tbl.parentData"
		} else {
			parentData = "tbl.data"
		}
		if named, ok := f.sliceInfo.elem.(*types.Named); ok &&
			(qualifiedName(named) == "honnef.co/go/gutter/opentype.Offset16" || qualifiedName(named) == "honnef.co/go/gutter/opentype.Offset32") {
			// Generate getter for a single item from the slice, resolving offset
			// elem := name.TypeArgs().At(0)
			// panic(nil)
		} else {
			// Generate getter for a single item from the slice
			fmt.Fprintf(out, "func (tbl *%s) %s(i int) %s {\n", obj.Name(), getterFnName, elemName(f.sliceInfo.elem))
			var elemSize string
			if f.sliceInfo.elemSizeField != "" {
				fmt.Fprintf(out, "sz := int(tbl.%s)\n", f.sliceInfo.elemSizeField)
				elemSize = "sz"
			} else {
				elemSize = strconv.Itoa(f.sliceInfo.elemSize)
			}
			fmt.Fprintf(out, "var out %s\n", elemName(f.sliceInfo.elem))
			fmt.Fprintln(out, g.parse(f.sliceInfo.elem).fn(fmt.Sprintf("tbl.%s[i*%s:(i+1)*%s:len(tbl.%s)]", f.field.Name(), elemSize, elemSize, f.field.Name()), parentData, "&out"))
			fmt.Fprintln(out, "return out")
			fmt.Fprintln(out, "}")

			// Generate iterator over slice
			fmt.Fprintln(out)
			g.addImport("iter")
			fmt.Fprintf(out, "func (tbl *%s) %s() iter.Seq2[int, %s] {\n", obj.Name(), title(f.field.Name()), elemName(f.sliceInfo.elem))
			fmt.Fprintf(out, "return func(yield func(int, %s) bool) {\n", elemName(f.sliceInfo.elem))
			if len(f.sliceInfo.numElements) > 1 || f.sliceInfo.numElements[0] == "-1" || !dstHasField(f.sliceInfo.numElements[0]) {
				fmt.Fprintf(out, "for i := range tbl.Num%s() {\n", title(f.field.Name()))
			} else {
				fmt.Fprintf(out, "for i := range int(tbl.%s) {\n", f.sliceInfo.numElements[0])
			}
			fmt.Fprintf(out, "if !yield(i, tbl.%s(i)) { return }}}}\n", getterFnName)
		}

		// Generate method to get number of elements if it has to be computed dynamically
		if len(f.sliceInfo.numElements) > 1 || f.sliceInfo.numElements[0] == "-1" || !dstHasField(f.sliceInfo.numElements[0]) {
			fmt.Fprintln(out)
			fmt.Fprintf(out, "func (tbl *%s) Num%s() int {\n", obj.Name(), title(f.field.Name()))
			if f.sliceInfo.elemSizeField != "" {
				fmt.Fprintf(out, "return len(tbl.%s) / int(tbl.%s)\n", f.field.Name(), f.sliceInfo.elemSizeField)
			} else {
				fmt.Fprintf(out, "return len(tbl.%s) / %d\n", f.field.Name(), f.sliceInfo.elemSize)
			}
			fmt.Fprintln(out, "}")
		}
	}
}

func (g *generator) elemSize(typ types.Type) (_ int, dynamic bool) {
	switch typ := types.Unalias(typ).(type) {
	case *types.Named:
		// XXX check full object path
		switch qualifiedName(typ) {
		case "honnef.co/go/gutter/opentype/internal/tables.versionDelimiter", "honnef.co/go/gutter/opentype/internal/tables.sizeDelimiter":
			return 0, true
		case "honnef.co/go/gutter/opentype.Slice":
			return -1, true
		case "honnef.co/go/gutter/opentype.Tag":
			return 4, false
		case "time.Time":
			return 8, false
		default:
			return g.elemSize(typ.Underlying())
		}
	case *types.Basic:
		switch typ.Kind() {
		case types.Int8:
			return 1, false
		case types.Int16:
			return 2, false
		case types.Int32:
			return 4, false
		case types.Int64:
			return 8, false
		case types.Uint8:
			return 1, false
		case types.Uint16:
			return 2, false
		case types.Uint32:
			return 4, false
		case types.Uint64:
			return 8, false
		default:
			panic(fmt.Sprintf("unsupported type %s", typ))
		}
	case *types.Pointer:
		if arr, ok := typ.Elem().(*types.Array); ok {
			return g.elemSize(arr)
		} else {
			panic(fmt.Sprintf("unsupported type %s", typ))
		}
	case *types.Array:
		sz, dynamic := g.elemSize(typ.Elem())
		if dynamic {
			panic("arrays of dynamic length types are unsupported")
		}
		return int(typ.Len()) * sz, false
	case *types.Struct:
		var totalSize int
		var isDynamic bool

		unionSize := -2
		for i := 0; i < typ.NumFields(); i++ {
			f := typ.Field(i)
			if f.Name() == "data" || f.Name() == "parentData" {
				continue
			}
			sz, dynamic := g.elemSize(f.Type())
			if dynamic {
				isDynamic = true
			}
			if sz >= 0 {
				totalSize += sz
			}
			switch tag := parseTag(typ.Tag(i)); tag.command {
			case "slice":
				isDynamic = tag.args["offset"] == ""
			case "union":
				if (unionSize != -2 && sz != unionSize) || dynamic {
					isDynamic = true
				}
				unionSize = sz
			}
		}
		return totalSize, isDynamic
	case *types.Slice:
		return -1, true
	default:
		panic(fmt.Sprintf("unsupported type %s", typ))
	}
}

func (g *generator) parseArray(typ *types.Array) parser {
	if typ.Len() < 16 {
		elemSize, dynamic := g.elemSize(typ.Elem())
		if dynamic {
			panic("arrays of dynamic length types are unsupported")
		}

		elemParser := g.parse(typ.Elem())
		return parser{
			fn: func(buf, parentBuf, into string) string {
				var out strings.Builder
				fmt.Fprintln(&out, "{")
				fmt.Fprintf(&out, "\tbuf := %s\n", buf)
				fmt.Fprintf(&out, "\tinto := %s\n", into)
				for i := range int(typ.Len()) {
					fmt.Fprintln(&out, elemParser.fn(fmt.Sprintf("buf[%d:%d]", elemSize*i, elemSize*(i+1)), parentBuf, fmt.Sprintf("&into[%d]", i)))
				}
				fmt.Fprintln(&out, "}")
				return out.String()
			},
		}
	} else {
		elemParser := g.parse(typ.Elem())
		elemSize, dynamic := g.elemSize(typ.Elem())
		if dynamic {
			panic("arrays of dynamic length types are unsupported")
		}
		return parser{
			fn: func(buf, parentBuf, into string) string {
				var out strings.Builder
				fmt.Fprintln(&out, "{")
				fmt.Fprintf(&out, "buf := %s\n", buf)
				fmt.Fprintf(&out, "into := %s\n", into)
				fmt.Fprintln(&out, "for i := range into {")
				fmt.Fprintln(&out, elemParser.fn(fmt.Sprintf("buf[:%d]", elemSize), parentBuf, "&into[i]"))
				fmt.Fprintf(&out, "buf = buf[%d:]\n", elemSize)
				fmt.Fprintln(&out, "}")
				fmt.Fprintln(&out, "}")
				return out.String()
			},
		}
	}
}

func simpleCall(fn string, withParentData bool) parser {
	var cb func(buf, parentBuf, into string) string
	if withParentData {
		cb = func(buf, parentBuf, into string) string {
			return fmt.Sprintf("%s(%s, %s, %s)", fn, buf, parentBuf, into)
		}
	} else {
		cb = func(buf, parentBuf, into string) string {
			return fmt.Sprintf("%s(%s, %s)", fn, buf, into)
		}
	}
	return parser{fn: cb}
}
func title(s string) string {
	s = strings.TrimPrefix(s, "raw")
	return strings.ToUpper(s[0:1]) + s[1:]
}

func (g *generator) parse(typ types.Type) (ret parser) {
	switch typ := typ.(type) {
	case *types.Named:
		if qualifiedName(typ) == "honnef.co/go/gutter/opentype/internal/tables.versionDelimiter" {
			return parser{}
		}
		var prefix string
		isTable := strings.HasSuffix(typ.Obj().Name(), "Table") || strings.HasSuffix(typ.Obj().Name(), "Directory")
		if isTable {
			prefix = "Parse"
		} else {
			prefix = "parse"
		}
		fn := prefix + title(typ.Obj().Name())
		p := simpleCall(fn, g.needsParentData(typ))
		_, p.dynamic = g.elemSize(typ)
		return p
	case *types.Basic:
		switch typ.Kind() {
		case types.Int8:
			return parser{
				fn: func(buf, parentBuf, into string) string {
					return fmt.Sprintf("*%s = int8(%s[0])", into, buf)
				},
			}
		case types.Uint8:
			return parser{
				fn: func(buf, parentBuf, into string) string {
					return fmt.Sprintf("*%s = %s[0]", into, buf)
				},
			}
		default:
			return simpleCall("parse"+title(typ.Name()), false)
		}
	case *types.Array:
		if basic, ok := typ.Elem().(*types.Basic); ok && basic.Kind() == types.Uint8 {
			return parser{
				fn: func(buf, parentBuf, into string) string {
					return fmt.Sprintf("*%s = [%d]byte(%s)", into, typ.Len(), buf)
				},
			}
		} else {
			return g.parseArray(typ)
		}
	case *types.Pointer:
		arr := typ.Elem().(*types.Array)
		if basic, ok := arr.Elem().(*types.Basic); ok && basic.Kind() == types.Uint8 {
			return parser{
				fn: func(buf, parentBuf, into string) string {
					return fmt.Sprintf("*%s = (*[%d]byte)(%s)", into, arr.Len(), buf)
				},
			}
		} else {
			panic(fmt.Sprintf("unhandled type %T", arr))
		}
	case *types.Slice:
		return parser{dynamic: true}
	default:
		panic(fmt.Sprintf("unhandled type %T", typ))
	}
}

type parser struct {
	fn      func(buf, parentBuf, into string) string
	dynamic bool
}

type field struct {
	field               *types.Var
	size                int
	parser              parser
	isVersionDelimiter  bool
	isSizeDelimiter     bool
	delimVersion        int
	delimVersionMajor   int
	delimVersionMinor   int
	maxSupportedVersion int
	// is this the minor version of a Version16Dot16 version?
	versionIsWeird bool
	isSlice        bool
	sliceInfo      sliceInfo
	union          struct {
		field   string
		version int
	}
}

type sliceInfo struct {
	// name of field that contains the number of elements in the slice
	numElements []string
	// the element type of the slice
	elem types.Type
	// name of field that contains the offset of this slice. empty string means the slice
	// follows the previous field.
	offset   string
	elemSize int
	// element size is determined by this field instead of elemSize
	elemSizeField  string
	singular       string
	typedByteSlice bool
}

type fieldGroup struct {
	start           int
	minSize         int
	minVersion      int
	minVersionMajor int
	minVersionMinor int
	union           string
	optional        bool
	fields          []*field
}

type tag struct {
	command string
	args    map[any]string
}

func parseTag(s string) tag {
	var out tag
	g := reflect.StructTag(s).Get("gen")
	if idx := strings.Index(g, "("); idx != -1 {
		out.command = g[:idx]
		g = g[idx+1:]
		g = strings.TrimSuffix(g, ")")
		out.args = map[any]string{}
		n := 0
		for arg := range strings.SplitSeq(g, ",") {
			parts := strings.SplitN(strings.TrimSpace(arg), "=", 2)
			if len(parts) == 1 {
				out.args[n] = parts[0]
				n++
			} else {
				out.args[parts[0]] = parts[1]
			}
		}
	}
	return out
}

func (g *generator) needsParentData(typ types.Type) bool {
	switch typ := typ.Underlying().(type) {
	case *types.Struct:
		for field := range typ.Fields() {
			if field.Name() == "parentData" {
				return true
			}
		}
		return false
	case *types.Basic, *types.Slice, *types.Array:
		return false
	default:
		panic(fmt.Sprintf("unhandled type %T", typ))
	}
}
