version = 1
[[annotations]]
path = ["**/*_string.go"]
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**/testdata/zipper.json"]
SPDX-FileCopyrightText = "Google LLC"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileAttributionText = "This is the :zipper-face: emote from https://googlefonts.github.io/noto-emoji-animation/"

[[annotations]]
path = ["text/bidi/testdata/ucd/*.txt"]
SPDX-FileCopyrightText = "1991-2025 Unicode, Inc."
SPDX-License-Identifier = "Unicode-3.0"
