version = 1
[[annotations]]
# Generated files (and a checklist) that don't deserve copyright.
path = [
  "**/*_string.go",
  "text/bidi/data.go",
  "opentype/todo.org",
]
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**/testdata/fuzz/**"]
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**/testdata/zipper.json"]
SPDX-FileCopyrightText = "Google LLC"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileAttributionText = "This is the :zipper-face: emote from https://googlefonts.github.io/noto-emoji-animation/"

[[annotations]]
path = [
  "text/bidi/testdata/ucd/*.txt",
  "text/linebreak/testdata/ucd/*.txt",
  "text/bidi/BidiBrackets.txt",
  "text/bidi/DerivedBidiClass.txt",
  "text/linebreak/DerivedLineBreak.txt",
]
SPDX-FileCopyrightText = "1991-2025 Unicode, Inc."
SPDX-License-Identifier = "Unicode-3.0"

[[annotations]]
path = ["internal/language/**", "internal/tag/**"]
# Most files come with a copyright notice. Generated files do not.
SPDX-FileCopyrightText = "2013 The Go Authors."
SPDX-License-Identifier = "BSD-3-Clause"
