// Code generated by "stringer -type=cmdType"; DO NOT EDIT.

package sparse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[cmdNop-0]
	_ = x[cmdFill-1]
	_ = x[cmdAlphaFill-2]
	_ = x[cmdPushLayer-3]
	_ = x[cmdPopLayer-4]
	_ = x[cmdCopyBackdrop-5]
	_ = x[cmdBlend-6]
	_ = x[cmdAlphaBlend-7]
	_ = x[cmdClear-8]
}

const _cmdType_name = "cmdNopcmdFillcmdAlphaFillcmdPushLayercmdPopLayercmdCopyParentcmdBlendcmdAlphaBlendcmdClear"

var _cmdType_index = [...]uint8{0, 6, 13, 25, 37, 48, 61, 69, 82, 90}

func (i cmdType) String() string {
	if i >= cmdType(len(_cmdType_index)-1) {
		return "cmdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cmdType_name[_cmdType_index[i]:_cmdType_index[i+1]]
}
