// Code generated by "stringer -type=Compose -trimprefix=Compose"; DO NOT EDIT.

package sparse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComposeSrcOver-0]
	_ = x[ComposeCopy-129]
	_ = x[ComposeDest-130]
	_ = x[ComposeClear-131]
	_ = x[ComposeDestOver-4]
	_ = x[ComposeSrcIn-133]
	_ = x[ComposeDestIn-134]
	_ = x[ComposeSrcOut-135]
	_ = x[ComposeDestOut-136]
	_ = x[ComposeSrcAtop-9]
	_ = x[ComposeDestAtop-138]
	_ = x[ComposeXor-11]
	_ = x[ComposePlus-12]
}

const (
	_Compose_name_0 = "SrcOver"
	_Compose_name_1 = "DestOver"
	_Compose_name_2 = "SrcAtop"
	_Compose_name_3 = "XorPlus"
	_Compose_name_4 = "CopyDestClear"
	_Compose_name_5 = "SrcInDestInSrcOutDestOut"
	_Compose_name_6 = "DestAtop"
)

var (
	_Compose_index_3 = [...]uint8{0, 3, 7}
	_Compose_index_4 = [...]uint8{0, 4, 8, 13}
	_Compose_index_5 = [...]uint8{0, 5, 11, 17, 24}
)

func (i Compose) String() string {
	switch {
	case i == 0:
		return _Compose_name_0
	case i == 4:
		return _Compose_name_1
	case i == 9:
		return _Compose_name_2
	case 11 <= i && i <= 12:
		i -= 11
		return _Compose_name_3[_Compose_index_3[i]:_Compose_index_3[i+1]]
	case 129 <= i && i <= 131:
		i -= 129
		return _Compose_name_4[_Compose_index_4[i]:_Compose_index_4[i+1]]
	case 133 <= i && i <= 136:
		i -= 133
		return _Compose_name_5[_Compose_index_5[i]:_Compose_index_5[i+1]]
	case i == 138:
		return _Compose_name_6
	default:
		return "Compose(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
