// SPDX-FileCopyrightText: 2025 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

// Code generated by gen_fine.go. DO NOT EDIT.

package sparse

func fineClipFillSimpleNosNative(dst [][stripHeight]Color, nos Color, tos [][stripHeight]Color) {
	_ = tos[len(dst)-1]
	for i := range dst {
		dstCol := &dst[i]
		tosCol := &tos[i]
		for j := range stripHeight {
			oneMinusAlpha := 1.0 - tosCol[j][3]
			dstCol[j][0] = nos[0]*oneMinusAlpha + tosCol[j][0]
			dstCol[j][1] = nos[1]*oneMinusAlpha + tosCol[j][1]
			dstCol[j][2] = nos[2]*oneMinusAlpha + tosCol[j][2]
			dstCol[j][3] = nos[3]*oneMinusAlpha + tosCol[j][3]
		}
	}

}

func fineClipFillSimpleTosTranslucentNative(dst [][stripHeight]Color, tos Color) {

	oneMinusAlpha := 1.0 - tos[3]
	for i := range dst {
		dstCol := &dst[i]
		for j := range stripHeight {
			dstCol[j][0] = dstCol[j][0]*oneMinusAlpha + tos[0]
			dstCol[j][1] = dstCol[j][1]*oneMinusAlpha + tos[1]
			dstCol[j][2] = dstCol[j][2]*oneMinusAlpha + tos[2]
			dstCol[j][3] = dstCol[j][3]*oneMinusAlpha + tos[3]
		}
	}

}

func fineClipFillNative(dst, tos [][stripHeight]Color) {
	_ = tos[len(dst)-1]
	for i := range dst {
		dstCol := &dst[i]
		tosCol := &tos[i]
		for j := range stripHeight {
			oneMinusAlpha := 1.0 - tosCol[j][3]
			dstCol[j][0] = dstCol[j][0]*oneMinusAlpha + tosCol[j][0]
			dstCol[j][1] = dstCol[j][1]*oneMinusAlpha + tosCol[j][1]
			dstCol[j][2] = dstCol[j][2]*oneMinusAlpha + tosCol[j][2]
			dstCol[j][3] = dstCol[j][3]*oneMinusAlpha + tosCol[j][3]
		}
	}

}
