// SPDX-FileCopyrightText: 2025 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

//go:build ignore

package main

import (
	"bytes"
	"go/format"
	"os"
	"text/template"
)

func generateClipFill(tosComplex, nosComplex bool) string {
	tosColor := "tos"
	if tosComplex {
		tosColor = "tosCol[j]"
	}

	nosColor := "nos"
	if nosComplex {
		nosColor = "dstCol[j]"
	}

	tmpl := `
	{{- if .tosComplex -}}
		_ = tos[len(dst)-1]
	{{ else }}
		oneMinusAlpha := 1.0 - {{ .tosColor }}[3]
	{{ end -}}
	for i := range dst {
		dstCol := &dst[i]
		{{ if .tosComplex -}}
			tosCol := &tos[i]
		{{ end -}}
		for j := range stripHeight {
			{{ if .tosComplex -}} 
				oneMinusAlpha := 1.0 - {{ .tosColor }}[3]
			{{ end -}}
			dstCol[j][0] = {{ .nosColor }}[0]*oneMinusAlpha + {{ .tosColor }}[0]
			dstCol[j][1] = {{ .nosColor }}[1]*oneMinusAlpha + {{ .tosColor }}[1]
			dstCol[j][2] = {{ .nosColor }}[2]*oneMinusAlpha + {{ .tosColor }}[2]
			dstCol[j][3] = {{ .nosColor }}[3]*oneMinusAlpha + {{ .tosColor }}[3]
		}
	}
	`

	tmpl_, err := template.New("").Parse(tmpl)
	if err != nil {
		panic(err)
	}

	var b bytes.Buffer
	if err := tmpl_.Execute(&b, map[string]any{
		"tosColor":   tosColor,
		"nosColor":   nosColor,
		"tosComplex": tosComplex,
		"nosComplex": nosComplex,
	}); err != nil {
		panic(err)
	}
	return b.String()
}

func main() {
	tmpl := `
// SPDX-FileCopyrightText: 2025 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

// Code generated by gen_fine.go. DO NOT EDIT.

package sparse

	func fineClipFillSimpleNosNative(dst [][stripHeight]Color, nos Color, tos [][stripHeight]Color) {
		{{ generateClipFill true false }}
	}
	
	func fineClipFillSimpleTosTranslucentNative(dst [][stripHeight]Color, tos Color) {
		{{ generateClipFill false true }}
	}
	
	func fineClipFillNative(dst, tos [][stripHeight]Color) {
		{{ generateClipFill true true }}
	}
	`

	tmpl_, err := template.New("").Funcs(template.FuncMap{"generateClipFill": generateClipFill}).Parse(tmpl)
	if err != nil {
		panic(err)
	}

	var b bytes.Buffer
	if err := tmpl_.Execute(&b, nil); err != nil {
		panic(err)
	}

	f, err := os.Create("fine_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if _, err := f.Write(src); err != nil {
		panic(err)
	}
}
