// Code generated by command: go run sparse_amd64_asm.go -out ../sparse_amd64.s -pkg sparse. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

DATA one<>+0(SB)/4, $(1.0)
GLOBL one<>(SB), RODATA|NOPTR, $4

// func fineFillAVX(out [][4][4]float32, color [4]float32)
// Requires: AVX
TEXT ·fineFillAVX(SB), $0-40
	MOVQ           out_len+8(FP), AX
	SHLQ           $0x02, AX
	TESTQ          AX, AX
	JZ             exit
	VMOVSS         one<>+0(SB), X0
	VBROADCASTF128 color+24(FP), Y1
	MOVQ           out_base+0(FP), CX
	SHLQ           $0x04, AX
	ADDQ           AX, CX
	NEGQ           AX
	VMOVSS         color_3+36(FP), X2
	VUCOMISS       X0, X2
	JNE            blend
	PCALIGN        $0x10

loopOpaque:
	VMOVAPS Y1, (CX)(AX*1)
	VMOVAPS Y1, 32(CX)(AX*1)
	ADDQ    $0x40, AX
	JL      loopOpaque
	VZEROUPPER
	RET

blend:
	VSUBSS      X2, X0, X0
	VSHUFPS     $0x00, X0, X0, X0
	VINSERTF128 $0x01, X0, Y0, Y0
	PCALIGN     $0x10

loopTranslucent:
	VMOVAPS (CX)(AX*1), Y2
	VMULPS  Y0, Y2, Y2
	VADDPS  Y1, Y2, Y2
	VMOVAPS Y2, (CX)(AX*1)
	VMOVAPS 32(CX)(AX*1), Y2
	VMULPS  Y0, Y2, Y2
	VADDPS  Y1, Y2, Y2
	VMOVAPS Y2, 32(CX)(AX*1)
	ADDQ    $+64, AX
	JL      loopTranslucent

exit:
	VZEROUPPER
	RET

// func fineFillSSE(out [][4][4]float32, color [4]float32)
// Requires: SSE
TEXT ·fineFillSSE(SB), $0-40
	MOVQ    out_len+8(FP), AX
	SHLQ    $0x02, AX
	TESTQ   AX, AX
	JZ      exit
	MOVSS   one<>+0(SB), X0
	MOVUPS  color+24(FP), X1
	MOVQ    out_base+0(FP), CX
	SHLQ    $0x04, AX
	ADDQ    AX, CX
	NEGQ    AX
	MOVSS   color_3+36(FP), X2
	UCOMISS X0, X2
	JNE     blend

loopOpaque:
	MOVAPS X1, (CX)(AX*1)
	MOVAPS X1, 16(CX)(AX*1)
	ADDQ   $0x20, AX
	JL     loopOpaque
	RET

blend:
	MOVSS  X0, X3
	SUBSS  X2, X3
	SHUFPS $0x00, X3, X3

loopTranslucent:
	MOVAPS (CX)(AX*1), X0
	MULPS  X3, X0
	ADDPS  X1, X0
	MOVAPS X0, (CX)(AX*1)
	MOVAPS 16(CX)(AX*1), X0
	MULPS  X3, X0
	ADDPS  X1, X0
	MOVAPS X0, 16(CX)(AX*1)
	ADDQ   $0x20, AX
	JL     loopTranslucent

exit:
	RET
