// Code generated by command: go run sparse_amd64_asm.go -out sparse_amd64.s. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

DATA zeroToFour<>+0(SB)/4, $(0.0)
DATA zeroToFour<>+4(SB)/4, $(1.0)
DATA zeroToFour<>+8(SB)/4, $(2.0)
DATA zeroToFour<>+12(SB)/4, $(3.0)
DATA zeroToFour<>+16(SB)/4, $(4.0)
GLOBL zeroToFour<>(SB), RODATA|NOPTR, $20

DATA absMask<>+0(SB)/4, $0x80000000
DATA absMask<>+4(SB)/4, $0x80000000
DATA absMask<>+8(SB)/4, $0x80000000
DATA absMask<>+12(SB)/4, $0x80000000
GLOBL absMask<>(SB), RODATA|NOPTR, $16

// func memsetColumnsAVX(buf [][4]gfx.PlainColor, color gfx.PlainColor)
// Requires: AVX
TEXT ·memsetColumnsAVX(SB), $0-40
	MOVQ           buf_len+8(FP), AX
	SHLQ           $0x02, AX
	TESTQ          AX, AX
	JZ             exit
	MOVQ           buf_base+0(FP), CX
	SHLQ           $0x04, AX
	ADDQ           AX, CX
	NEGQ           AX
	VBROADCASTF128 color_0+24(FP), Y0
	PCALIGN        $0x10

loop:
	VMOVUPS Y0, (CX)(AX*1)
	VMOVUPS Y0, 32(CX)(AX*1)
	ADDQ    $0x40, AX
	JL      loop

exit:
	VZEROUPPER
	RET

// func memsetColumnsSSE(buf [][4]gfx.PlainColor, color gfx.PlainColor)
// Requires: SSE
TEXT ·memsetColumnsSSE(SB), $0-40
	MOVQ   buf_len+8(FP), AX
	SHLQ   $0x02, AX
	TESTQ  AX, AX
	JZ     exit
	MOVQ   buf_base+0(FP), CX
	SHLQ   $0x04, AX
	ADDQ   AX, CX
	NEGQ   AX
	MOVUPS color_0+24(FP), X0

loop:
	MOVAPS X0, (CX)(AX*1)
	MOVAPS X0, 16(CX)(AX*1)
	ADDQ   $0x20, AX
	JL     loop

exit:
	RET

// func processOutOfBoundsWindingSSE(ymin float32, ymax float32, sign float32, locationWinding *[4][4]float32, accumulatedWinding *[4]float32)
// Requires: SSE
TEXT ·processOutOfBoundsWindingSSE(SB), $0-32
	MOVUPS zeroToFour<>+0(SB), X0
	MOVUPS zeroToFour<>+4(SB), X1
	MOVSS  ymin+0(FP), X2
	SHUFPS $0x00, X2, X2
	MAXPS  X0, X2
	MOVSS  ymax+4(FP), X0
	SHUFPS $0x00, X0, X0
	MINPS  X1, X0
	MOVSS  sign+8(FP), X1
	SHUFPS $0x00, X1, X1
	XORPS  X3, X3
	SUBPS  X2, X0
	MAXPS  X3, X0
	MULPS  X1, X0
	MOVQ   accumulatedWinding+24(FP), AX
	MOVUPS (AX), X1
	ADDPS  X0, X1
	MOVUPS X1, (AX)
	MOVQ   locationWinding+16(FP), AX
	MOVUPS (AX), X1
	ADDPS  X0, X1
	MOVUPS X1, (AX)
	MOVUPS 16(AX), X1
	ADDPS  X0, X1
	MOVUPS X1, 16(AX)
	MOVUPS 32(AX), X1
	ADDPS  X0, X1
	MOVUPS X1, 32(AX)
	MOVUPS 48(AX), X1
	ADDPS  X0, X1
	MOVUPS X1, 48(AX)
	RET

// func computeAlphasNonZeroSSE(tail *[4][4]uint8, locationWinding *[4][4]float32)
// Requires: SSE, SSE2
TEXT ·computeAlphasNonZeroSSE(SB), $0-16
	MOVQ      locationWinding+8(FP), AX
	MOVQ      tail+0(FP), CX
	MOVUPS    f4_437f0000<>+0(SB), X0
	MOVUPS    f4_3f800000<>+0(SB), X1
	MOVUPS    f4_3f000000<>+0(SB), X2
	MOVUPS    absMask<>+0(SB), X3
	MOVUPS    (AX), X4
	MOVAPS    X3, X5
	ANDNPS    X4, X5
	MINPS     X1, X5
	MULPS     X0, X5
	ADDPS     X2, X5
	MOVUPS    16(AX), X4
	MOVAPS    X3, X6
	ANDNPS    X4, X6
	MINPS     X1, X6
	MULPS     X0, X6
	ADDPS     X2, X6
	MOVUPS    32(AX), X4
	MOVAPS    X3, X7
	ANDNPS    X4, X7
	MINPS     X1, X7
	MULPS     X0, X7
	ADDPS     X2, X7
	MOVUPS    48(AX), X4
	MOVAPS    X3, X3
	ANDNPS    X4, X3
	MINPS     X1, X3
	MULPS     X0, X3
	ADDPS     X2, X3
	CVTTPS2PL X5, X5
	CVTTPS2PL X6, X6
	CVTTPS2PL X7, X7
	CVTTPS2PL X3, X3
	PACKSSLW  X6, X5
	PACKSSLW  X3, X7
	PACKUSWB  X7, X5
	MOVUPS    X5, (CX)
	RET

DATA f4_437f0000<>+0(SB)/4, $(255.0)
DATA f4_437f0000<>+4(SB)/4, $(255.0)
DATA f4_437f0000<>+8(SB)/4, $(255.0)
DATA f4_437f0000<>+12(SB)/4, $(255.0)
GLOBL f4_437f0000<>(SB), RODATA|NOPTR, $16

DATA f4_3f800000<>+0(SB)/4, $(1.0)
DATA f4_3f800000<>+4(SB)/4, $(1.0)
DATA f4_3f800000<>+8(SB)/4, $(1.0)
DATA f4_3f800000<>+12(SB)/4, $(1.0)
GLOBL f4_3f800000<>(SB), RODATA|NOPTR, $16

DATA f4_3f000000<>+0(SB)/4, $(0.5)
DATA f4_3f000000<>+4(SB)/4, $(0.5)
DATA f4_3f000000<>+8(SB)/4, $(0.5)
DATA f4_3f000000<>+12(SB)/4, $(0.5)
GLOBL f4_3f000000<>(SB), RODATA|NOPTR, $16

// func computeAlphasNonZeroAVX(tail *[4][4]uint8, locationWinding *[4][4]float32)
// Requires: AVX, AVX2
TEXT ·computeAlphasNonZeroAVX(SB), $0-16
	MOVQ         locationWinding+8(FP), AX
	MOVQ         tail+0(FP), CX
	VBROADCASTSS f_437f0000<>+0(SB), Y0
	VBROADCASTSS f_3f800000<>+0(SB), Y1
	VBROADCASTSS f_3f000000<>+0(SB), Y2
	VBROADCASTSS f_80000000<>+0(SB), Y3
	VANDNPS      (AX), Y3, Y4
	VMINPS       Y1, Y4, Y4
	VMULPS       Y0, Y4, Y4
	VADDPS       Y2, Y4, Y4
	VANDNPS      32(AX), Y3, Y3
	VMINPS       Y1, Y3, Y3
	VMULPS       Y0, Y3, Y3
	VADDPS       Y2, Y3, Y3
	VCVTTPS2DQ   Y4, Y4
	VCVTTPS2DQ   Y3, Y3
	VPACKSSDW    Y3, Y4, Y4
	VPACKUSWB    Y4, Y4, Y4
	VMOVUPS      permMask<>+0(SB), Y0
	VPERMD       Y4, Y0, Y4
	VMOVUPS      X4, (CX)
	VZEROUPPER
	RET

DATA f_437f0000<>+0(SB)/4, $(255.0)
GLOBL f_437f0000<>(SB), RODATA|NOPTR, $4

DATA f_3f800000<>+0(SB)/4, $(1.0)
GLOBL f_3f800000<>(SB), RODATA|NOPTR, $4

DATA f_3f000000<>+0(SB)/4, $(0.5)
GLOBL f_3f000000<>(SB), RODATA|NOPTR, $4

DATA f_80000000<>+0(SB)/4, $(-0.0)
GLOBL f_80000000<>(SB), RODATA|NOPTR, $4

DATA permMask<>+0(SB)/4, $0x00000000
DATA permMask<>+4(SB)/4, $0x00000004
DATA permMask<>+8(SB)/4, $0x00000001
DATA permMask<>+12(SB)/4, $0x00000005
DATA permMask<>+16(SB)/4, $0x00000002
DATA permMask<>+20(SB)/4, $0x00000006
DATA permMask<>+24(SB)/4, $0x00000003
DATA permMask<>+28(SB)/4, $0x00000007
GLOBL permMask<>(SB), RODATA|NOPTR, $32
