// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type BASETable struct {
	data []byte

	MajorVersion    uint16
	MinorVersion    uint16
	horizAxisOffset Offset16[AxisTable]
	vertAxisOffset  Offset16[AxisTable]

	itemVarStoreOffset Offset32[ItemVariationStoreTable]
}

type AxisTable struct {
	data []byte

	baseTagListOffset    Offset16[BaseTagListTable]
	baseScriptListOffset Offset16[BaseScriptListTable]
}

type BaseTagListTable struct {
	baseTagCount uint16
	baselineTags Slice[Tag]
}

type BaseScriptListTable struct {
	data []byte

	baseScriptCount   uint16
	baseScriptRecords Slice[BaseScriptRecord]
}

type BaseScriptRecord struct {
	parentData []byte

	Tag              Tag
	baseScriptOffset Offset16[BaseScriptTable]
}

type BaseScriptTable struct {
	data []byte

	baseValuesOffset    Offset16[BaseValuesTable]
	DefaultMinMaxOffset Offset16[MinMaxTable]
	baseLangSysCount    uint16
	baseLangSysRecords  Slice[BaseLangSysRecord]
}

type BaseLangSysRecord struct {
	parentData []byte

	Tag          Tag
	minMaxOffset Offset16[MinMaxTable]
}

type BaseValuesTable struct {
	data []byte

	DefaultBaselineIndex uint16
	baseCoordCount       uint16
	baseCoordOffsets     Slice[Offset16[BaseCoordTable]]
}

type MinMaxTable struct {
	data []byte

	minCoordOffset    Offset16[BaseCoordTable]
	maxCoordOffset    Offset16[BaseCoordTable]
	featMinMaxCount   uint16
	featMinMaxRecords Slice[FeatMinMaxRecord]
}

type FeatMinMaxRecord struct {
	data []byte

	FeatureTableTag Tag
	minCoordOffset  Offset16[BaseCoordTable]
	maxCoordOffset  Offset16[BaseCoordTable]
}

type BaseCoordTable struct {
	Format uint16

	Format1 BaseCoordTableFormat1
	Format2 BaseCoordTableFormat2
	Format3 BaseCoordTableFormat3
}

type BaseCoordTableFormat1 struct {
	Coordinate int16
}

type BaseCoordTableFormat2 struct {
	Coordinate     int16
	ReferenceGlyph uint16
	BaseCoordPoint uint16
}

type BaseCoordTableFormat3 struct {
	parentData []byte
	Coordinate int16

	// Offset to a DeviceTable or a VariationIndexTable, relative to BaseCoordTable
	DeviceOffset Offset16[any]
}
func ParseAxisTable(buf []byte, out *AxisTable) int {
	*out = AxisTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.baseTagListOffset)
	parseOffset16(buf[2:4], &out.baseScriptListOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *AxisTable) BaseTagList(into *BaseTagListTable) bool {
	// FIXME: check bounds
	if tbl.baseTagListOffset == 0 {
		return false
	}
	ParseBaseTagListTable(tbl.data[tbl.baseTagListOffset:], into)
	return true
}

func (tbl *AxisTable) BaseScriptList(into *BaseScriptListTable) bool {
	// FIXME: check bounds
	if tbl.baseScriptListOffset == 0 {
		return false
	}
	ParseBaseScriptListTable(tbl.data[tbl.baseScriptListOffset:], into)
	return true
}

func ParseBASETable(buf []byte, out *BASETable) int {
	*out = BASETable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseOffset16(buf[4:6], &out.horizAxisOffset)
	parseOffset16(buf[6:8], &out.vertAxisOffset)

	if out.MajorVersion < 1 {
		return dynSize
	}
	if out.MajorVersion == 1 && out.MinorVersion < 1 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseOffset32(buf[8:12], &out.itemVarStoreOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *BASETable) HorizAxis(into *AxisTable) bool {
	// FIXME: check bounds
	if tbl.horizAxisOffset == 0 {
		return false
	}
	ParseAxisTable(tbl.data[tbl.horizAxisOffset:], into)
	return true
}

func (tbl *BASETable) VertAxis(into *AxisTable) bool {
	// FIXME: check bounds
	if tbl.vertAxisOffset == 0 {
		return false
	}
	ParseAxisTable(tbl.data[tbl.vertAxisOffset:], into)
	return true
}

func (tbl *BASETable) ItemVarStore(into *ItemVariationStoreTable) bool {
	// FIXME: check bounds
	if tbl.itemVarStoreOffset == 0 {
		return false
	}
	ParseItemVariationStoreTable(tbl.data[tbl.itemVarStoreOffset:], into)
	return true
}

func ParseBaseCoordTable(buf []byte, out *BaseCoordTable) int {
	*out = BaseCoordTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 1:
		parseBaseCoordTableFormat1(buf[2:4], &out.Format1)
	case 2:
		parseBaseCoordTableFormat2(buf[2:8], &out.Format2)
	case 3:
		parseBaseCoordTableFormat3(buf[2:6], buf, &out.Format3)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseBaseCoordTableFormat1(buf []byte, out *BaseCoordTableFormat1) int {
	*out = BaseCoordTableFormat1{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.Coordinate)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseBaseCoordTableFormat2(buf []byte, out *BaseCoordTableFormat2) int {
	*out = BaseCoordTableFormat2{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.Coordinate)
	parseUint16(buf[2:4], &out.ReferenceGlyph)
	parseUint16(buf[4:6], &out.BaseCoordPoint)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseBaseCoordTableFormat3(buf, parentBuf []byte, out *BaseCoordTableFormat3) int {
	*out = BaseCoordTableFormat3{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.Coordinate)
	parseOffset16(buf[2:4], &out.DeviceOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseBaseLangSysRecord(buf, parentBuf []byte, out *BaseLangSysRecord) int {
	*out = BaseLangSysRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseTag(buf[0:4], &out.Tag)
	parseOffset16(buf[4:6], &out.minMaxOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *BaseLangSysRecord) MinMax(into *MinMaxTable) bool {
	// FIXME: check bounds
	if tbl.minMaxOffset == 0 {
		return false
	}
	ParseMinMaxTable(tbl.parentData[tbl.minMaxOffset:], into)
	return true
}

func ParseBaseScriptListTable(buf []byte, out *BaseScriptListTable) int {
	*out = BaseScriptListTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.baseScriptCount)
	{
		n := int(out.baseScriptCount)
		/* FIXME: check that buf is long enough */
		out.baseScriptRecords = buf[2 : 2+n*6]
		dynSize += n * 6
		buf = buf[2+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *BaseScriptListTable) BaseScriptRecord(i int) BaseScriptRecord {
	var out BaseScriptRecord
	parseBaseScriptRecord(tbl.baseScriptRecords[i*6:(i+1)*6:len(tbl.baseScriptRecords)], tbl.data, &out)
	return out
}

func (tbl *BaseScriptListTable) BaseScriptRecords() iter.Seq2[int, BaseScriptRecord] {
	return func(yield func(int, BaseScriptRecord) bool) {
		for i := range int(tbl.baseScriptCount) {
			if !yield(i, tbl.BaseScriptRecord(i)) {
				return
			}
		}
	}
}

func parseBaseScriptRecord(buf, parentBuf []byte, out *BaseScriptRecord) int {
	*out = BaseScriptRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseTag(buf[0:4], &out.Tag)
	parseOffset16(buf[4:6], &out.baseScriptOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *BaseScriptRecord) BaseScript(into *BaseScriptTable) bool {
	// FIXME: check bounds
	if tbl.baseScriptOffset == 0 {
		return false
	}
	ParseBaseScriptTable(tbl.parentData[tbl.baseScriptOffset:], into)
	return true
}

func ParseBaseScriptTable(buf []byte, out *BaseScriptTable) int {
	*out = BaseScriptTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.baseValuesOffset)
	parseOffset16(buf[2:4], &out.DefaultMinMaxOffset)
	parseUint16(buf[4:6], &out.baseLangSysCount)
	{
		n := int(out.baseLangSysCount)
		/* FIXME: check that buf is long enough */
		out.baseLangSysRecords = buf[6 : 6+n*6]
		dynSize += n * 6
		buf = buf[6+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *BaseScriptTable) BaseValues(into *BaseValuesTable) bool {
	// FIXME: check bounds
	if tbl.baseValuesOffset == 0 {
		return false
	}
	ParseBaseValuesTable(tbl.data[tbl.baseValuesOffset:], into)
	return true
}

func (tbl *BaseScriptTable) BaseLangSysRecord(i int) BaseLangSysRecord {
	var out BaseLangSysRecord
	parseBaseLangSysRecord(tbl.baseLangSysRecords[i*6:(i+1)*6:len(tbl.baseLangSysRecords)], tbl.data, &out)
	return out
}

func (tbl *BaseScriptTable) BaseLangSysRecords() iter.Seq2[int, BaseLangSysRecord] {
	return func(yield func(int, BaseLangSysRecord) bool) {
		for i := range int(tbl.baseLangSysCount) {
			if !yield(i, tbl.BaseLangSysRecord(i)) {
				return
			}
		}
	}
}

func ParseBaseTagListTable(buf []byte, out *BaseTagListTable) int {
	*out = BaseTagListTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.baseTagCount)
	{
		n := int(out.baseTagCount)
		/* FIXME: check that buf is long enough */
		out.baselineTags = buf[2 : 2+n*4]
		dynSize += n * 4
		buf = buf[2+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *BaseTagListTable) BaselineTag(i int) Tag {
	var out Tag
	parseTag(tbl.baselineTags[i*4:(i+1)*4:len(tbl.baselineTags)], &out)
	return out
}

func (tbl *BaseTagListTable) BaselineTags() iter.Seq2[int, Tag] {
	return func(yield func(int, Tag) bool) {
		for i := range int(tbl.baseTagCount) {
			if !yield(i, tbl.BaselineTag(i)) {
				return
			}
		}
	}
}

func ParseBaseValuesTable(buf []byte, out *BaseValuesTable) int {
	*out = BaseValuesTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.DefaultBaselineIndex)
	parseUint16(buf[2:4], &out.baseCoordCount)
	{
		n := int(out.baseCoordCount)
		/* FIXME: check that buf is long enough */
		out.baseCoordOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func parseFeatMinMaxRecord(buf []byte, out *FeatMinMaxRecord) int {
	*out = FeatMinMaxRecord{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseTag(buf[0:4], &out.FeatureTableTag)
	parseOffset16(buf[4:6], &out.minCoordOffset)
	parseOffset16(buf[6:8], &out.maxCoordOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *FeatMinMaxRecord) MinCoord(into *BaseCoordTable) bool {
	// FIXME: check bounds
	if tbl.minCoordOffset == 0 {
		return false
	}
	ParseBaseCoordTable(tbl.data[tbl.minCoordOffset:], into)
	return true
}

func (tbl *FeatMinMaxRecord) MaxCoord(into *BaseCoordTable) bool {
	// FIXME: check bounds
	if tbl.maxCoordOffset == 0 {
		return false
	}
	ParseBaseCoordTable(tbl.data[tbl.maxCoordOffset:], into)
	return true
}

func ParseMinMaxTable(buf []byte, out *MinMaxTable) int {
	*out = MinMaxTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.minCoordOffset)
	parseOffset16(buf[2:4], &out.maxCoordOffset)
	parseUint16(buf[4:6], &out.featMinMaxCount)
	{
		n := int(out.featMinMaxCount)
		/* FIXME: check that buf is long enough */
		out.featMinMaxRecords = buf[6 : 6+n*8]
		dynSize += n * 8
		buf = buf[6+n*8:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *MinMaxTable) MinCoord(into *BaseCoordTable) bool {
	// FIXME: check bounds
	if tbl.minCoordOffset == 0 {
		return false
	}
	ParseBaseCoordTable(tbl.data[tbl.minCoordOffset:], into)
	return true
}

func (tbl *MinMaxTable) MaxCoord(into *BaseCoordTable) bool {
	// FIXME: check bounds
	if tbl.maxCoordOffset == 0 {
		return false
	}
	ParseBaseCoordTable(tbl.data[tbl.maxCoordOffset:], into)
	return true
}

func (tbl *MinMaxTable) FeatMinMaxRecord(i int) FeatMinMaxRecord {
	var out FeatMinMaxRecord
	parseFeatMinMaxRecord(tbl.featMinMaxRecords[i*8:(i+1)*8:len(tbl.featMinMaxRecords)], &out)
	return out
}

func (tbl *MinMaxTable) FeatMinMaxRecords() iter.Seq2[int, FeatMinMaxRecord] {
	return func(yield func(int, FeatMinMaxRecord) bool) {
		for i := range int(tbl.featMinMaxCount) {
			if !yield(i, tbl.FeatMinMaxRecord(i)) {
				return
			}
		}
	}
}

