// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type CmapTable struct {
	data []byte

	Version uint16

	encodingRecords Slice[EncodingRecord]
}

type EncodingRecord struct {
	parentData []byte

	PlatformID     PlatformID
	EncodingID     EncodingID
	subtableOffset Offset32[CmapSubtable]
}

type CmapSubtable struct {
	Format  uint16
	Format0 CmapSubtableFormat0
	// TODO(dh): Format 2 is silly and I don't care enough to support it at this point. It
	// is, however, required for Big5 and ShiftJIS.
	Format4 CmapSubtableFormat4
	Format6 CmapSubtableFormat6
	// TODO(dh): Format 8 allows for mixing 16-bit and 32-bit but isn't commonly used or
	// supported. Harfbuzz doesn't support it, for example.
	Format10 CmapSubtableFormat10
	Format12 CmapSubtableFormat12
	Format13 CmapSubtableFormat13
	Format14 CmapSubtableFormat14
}

// CmapSubtableFormat0 maps 8-bit character codes to glyph indices.
type CmapSubtableFormat0 struct {
	Length   uint16
	Language uint16
	// XXX it is not clear if GlyphIDs is guaranteed to be 256 bytes long, or if Length
	// can cap it
	GlyphIDs *[256]byte
}

// CmapSubtableFormat4 maps 16-bit characters to glyph indices, supporting multiple
// segments. Used for Unicode BMP.
type CmapSubtableFormat4 struct {
	Length   uint16
	Language uint16

	endCodes Slice[uint16]

	startCodes     Slice[uint16]
	idDeltas       Slice[int16]
	idRangeOffsets Slice[uint16]
	glyphIDs       Slice[uint16]
}

// CmapSubtableFormat6 maps 16-bit characters to glyph indices, supporting a single
// segment.
type CmapSubtableFormat6 struct {
	Length    uint16
	Language  uint16
	FirstCode uint16

	glyphIDs Slice[uint16]
}

type SequentialMapGroupRecord struct {
	StartCharCode uint32
	EndCharCode   uint32
	StartGlyphID  uint32
}

// CmapSubtableFormat10 is the 32-bit equivalent of CmapSubtableFormat6.
type CmapSubtableFormat10 struct {
	Length        uint32
	Language      uint32
	StartCharCode uint32

	glyphIDs Slice[uint16]
}

// CmapSubtableFormat12 maps 32-bit characters to glyph indices, supporting multiple
// segments. Used for the full range of Unicode.
type CmapSubtableFormat12 struct {
	Length   uint32
	Language uint32

	groups Slice[SequentialMapGroupRecord]
}

// CmapSubtableFormat13 is similar to CmapSubtableFormat12, but is used for mapping many
// characters to the same glyphs.
type CmapSubtableFormat13 struct {
	Length   uint32
	Language uint32

	groups Slice[ConstantMapGroupRecord]
}

type ConstantMapGroupRecord struct {
	StartCharCode uint32
	EndCharCode   uint32
	GlyphID       uint32
}

// CmapSubtableFormat14 maps Unicode variation selector sequences to glyphs.
type CmapSubtableFormat14 struct {
	Length uint32

	varSelectors Slice[VariationSelectorRecord]
}

type VariationSelectorRecord struct {
	VarSelector         Uint24
	DefaultUVSOffset    Offset32[DefaultUVSTable]
	NonDefaultUVSOffset Offset32[NonDefaultUVSTable]
}

type DefaultUVSTable struct {
	ranges Slice[UnicodeRangeRecord]
}

type UnicodeRangeRecord struct {
	StartUnicodeValue Uint24
	AdditionalCount   uint8
}

type NonDefaultUVSTable struct {
	uvsMappings Slice[UVSMappingRecord]
}

type UVSMappingRecord struct {
	UnicodeValue Uint24
	GlyphID      uint16
}
func parseCmapSubtable(buf []byte, out *CmapSubtable) int {
	*out = CmapSubtable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 0:
		parseCmapSubtableFormat0(buf[2:262], &out.Format0)
	case 4:
		dynSize += parseCmapSubtableFormat4(buf[2:], &out.Format4)
	case 6:
		dynSize += parseCmapSubtableFormat6(buf[2:], &out.Format6)
	case 10:
		dynSize += parseCmapSubtableFormat10(buf[2:], &out.Format10)
	case 12:
		dynSize += parseCmapSubtableFormat12(buf[2:], &out.Format12)
	case 13:
		dynSize += parseCmapSubtableFormat13(buf[2:], &out.Format13)
	case 14:
		dynSize += parseCmapSubtableFormat14(buf[2:], &out.Format14)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseCmapSubtableFormat0(buf []byte, out *CmapSubtableFormat0) int {
	*out = CmapSubtableFormat0{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 260 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Length)
	parseUint16(buf[2:4], &out.Language)
	out.GlyphIDs = (*[256]byte)(buf[4:260])
	_ = buf
	_ = origBuf
	return dynSize
}

func parseCmapSubtableFormat10(buf []byte, out *CmapSubtableFormat10) int {
	*out = CmapSubtableFormat10{}
	origBuf := buf
	var dynSize int
	var numChars uint32

	/* FIXME return error */
	if len(buf) < 18 {
		return dynSize
	}
	parseUint32(buf[2:6], &out.Length)
	parseUint32(buf[6:10], &out.Language)
	parseUint32(buf[10:14], &out.StartCharCode)
	parseUint32(buf[14:18], &numChars)
	{
		n := int(numChars)
		/* FIXME: check that buf is long enough */
		out.glyphIDs = buf[18 : 18+n*2]
		dynSize += n * 2
		buf = buf[18+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapSubtableFormat10) GlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.glyphIDs[i*2:(i+1)*2:len(tbl.glyphIDs)], &out)
	return out
}

func (tbl *CmapSubtableFormat10) GlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumGlyphIDs() {
			if !yield(i, tbl.GlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat10) NumGlyphIDs() int {
	return len(tbl.glyphIDs) / 2
}

func parseCmapSubtableFormat12(buf []byte, out *CmapSubtableFormat12) int {
	*out = CmapSubtableFormat12{}
	origBuf := buf
	var dynSize int
	var numGroups uint32

	/* FIXME return error */
	if len(buf) < 14 {
		return dynSize
	}
	parseUint32(buf[2:6], &out.Length)
	parseUint32(buf[6:10], &out.Language)
	parseUint32(buf[10:14], &numGroups)
	{
		n := int(numGroups)
		/* FIXME: check that buf is long enough */
		out.groups = buf[14 : 14+n*12]
		dynSize += n * 12
		buf = buf[14+n*12:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapSubtableFormat12) Group(i int) SequentialMapGroupRecord {
	var out SequentialMapGroupRecord
	parseSequentialMapGroupRecord(tbl.groups[i*12:(i+1)*12:len(tbl.groups)], &out)
	return out
}

func (tbl *CmapSubtableFormat12) Groups() iter.Seq2[int, SequentialMapGroupRecord] {
	return func(yield func(int, SequentialMapGroupRecord) bool) {
		for i := range tbl.NumGroups() {
			if !yield(i, tbl.Group(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat12) NumGroups() int {
	return len(tbl.groups) / 12
}

func parseCmapSubtableFormat13(buf []byte, out *CmapSubtableFormat13) int {
	*out = CmapSubtableFormat13{}
	origBuf := buf
	var dynSize int
	var numGroups uint32

	/* FIXME return error */
	if len(buf) < 14 {
		return dynSize
	}
	parseUint32(buf[2:6], &out.Length)
	parseUint32(buf[6:10], &out.Language)
	parseUint32(buf[10:14], &numGroups)
	{
		n := int(numGroups)
		/* FIXME: check that buf is long enough */
		out.groups = buf[14 : 14+n*12]
		dynSize += n * 12
		buf = buf[14+n*12:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapSubtableFormat13) Group(i int) ConstantMapGroupRecord {
	var out ConstantMapGroupRecord
	parseConstantMapGroupRecord(tbl.groups[i*12:(i+1)*12:len(tbl.groups)], &out)
	return out
}

func (tbl *CmapSubtableFormat13) Groups() iter.Seq2[int, ConstantMapGroupRecord] {
	return func(yield func(int, ConstantMapGroupRecord) bool) {
		for i := range tbl.NumGroups() {
			if !yield(i, tbl.Group(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat13) NumGroups() int {
	return len(tbl.groups) / 12
}

func parseCmapSubtableFormat14(buf []byte, out *CmapSubtableFormat14) int {
	*out = CmapSubtableFormat14{}
	origBuf := buf
	var dynSize int
	var numVarSelectorRecords uint32

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.Length)
	parseUint32(buf[4:8], &numVarSelectorRecords)
	{
		n := int(numVarSelectorRecords)
		/* FIXME: check that buf is long enough */
		out.varSelectors = buf[8 : 8+n*12]
		dynSize += n * 12
		buf = buf[8+n*12:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapSubtableFormat14) VarSelector(i int) VariationSelectorRecord {
	var out VariationSelectorRecord
	parseVariationSelectorRecord(tbl.varSelectors[i*12:(i+1)*12:len(tbl.varSelectors)], &out)
	return out
}

func (tbl *CmapSubtableFormat14) VarSelectors() iter.Seq2[int, VariationSelectorRecord] {
	return func(yield func(int, VariationSelectorRecord) bool) {
		for i := range tbl.NumVarSelectors() {
			if !yield(i, tbl.VarSelector(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat14) NumVarSelectors() int {
	return len(tbl.varSelectors) / 12
}

func parseCmapSubtableFormat4(buf []byte, out *CmapSubtableFormat4) int {
	*out = CmapSubtableFormat4{}
	origBuf := buf
	var dynSize int
	var segCountX2 uint16

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Length)
	parseUint16(buf[2:4], &out.Language)
	parseUint16(buf[4:6], &segCountX2)
	{
		n := int(segCountX2 / 2)
		/* FIXME: check that buf is long enough */
		out.endCodes = buf[12 : 12+n*2]
		dynSize += n * 2
		buf = buf[12+n*2:]
	}

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	{
		n := int(segCountX2 / 2)
		/* FIXME: check that buf is long enough */
		out.startCodes = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	{
		n := int(segCountX2 / 2)
		/* FIXME: check that buf is long enough */
		out.idDeltas = buf[0 : 0+n*2]
		dynSize += n * 2
		buf = buf[0+n*2:]
	}

	{
		n := int(segCountX2 / 2)
		/* FIXME: check that buf is long enough */
		out.idRangeOffsets = buf[0 : 0+n*2]
		dynSize += n * 2
		buf = buf[0+n*2:]
	}

	{
		out.glyphIDs = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapSubtableFormat4) EndCode(i int) uint16 {
	var out uint16
	parseUint16(tbl.endCodes[i*2:(i+1)*2:len(tbl.endCodes)], &out)
	return out
}

func (tbl *CmapSubtableFormat4) EndCodes() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumEndCodes() {
			if !yield(i, tbl.EndCode(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat4) NumEndCodes() int {
	return len(tbl.endCodes) / 2
}

func (tbl *CmapSubtableFormat4) StartCode(i int) uint16 {
	var out uint16
	parseUint16(tbl.startCodes[i*2:(i+1)*2:len(tbl.startCodes)], &out)
	return out
}

func (tbl *CmapSubtableFormat4) StartCodes() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumStartCodes() {
			if !yield(i, tbl.StartCode(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat4) NumStartCodes() int {
	return len(tbl.startCodes) / 2
}

func (tbl *CmapSubtableFormat4) IDDelta(i int) int16 {
	var out int16
	parseInt16(tbl.idDeltas[i*2:(i+1)*2:len(tbl.idDeltas)], &out)
	return out
}

func (tbl *CmapSubtableFormat4) IdDeltas() iter.Seq2[int, int16] {
	return func(yield func(int, int16) bool) {
		for i := range tbl.NumIdDeltas() {
			if !yield(i, tbl.IDDelta(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat4) NumIdDeltas() int {
	return len(tbl.idDeltas) / 2
}

func (tbl *CmapSubtableFormat4) IDRangeOffset(i int) uint16 {
	var out uint16
	parseUint16(tbl.idRangeOffsets[i*2:(i+1)*2:len(tbl.idRangeOffsets)], &out)
	return out
}

func (tbl *CmapSubtableFormat4) IdRangeOffsets() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumIdRangeOffsets() {
			if !yield(i, tbl.IDRangeOffset(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat4) NumIdRangeOffsets() int {
	return len(tbl.idRangeOffsets) / 2
}

func (tbl *CmapSubtableFormat4) GlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.glyphIDs[i*2:(i+1)*2:len(tbl.glyphIDs)], &out)
	return out
}

func (tbl *CmapSubtableFormat4) GlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumGlyphIDs() {
			if !yield(i, tbl.GlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat4) NumGlyphIDs() int {
	return len(tbl.glyphIDs) / 2
}

func parseCmapSubtableFormat6(buf []byte, out *CmapSubtableFormat6) int {
	*out = CmapSubtableFormat6{}
	origBuf := buf
	var dynSize int
	var entryCount uint16

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Length)
	parseUint16(buf[2:4], &out.Language)
	parseUint16(buf[4:6], &out.FirstCode)
	parseUint16(buf[6:8], &entryCount)
	{
		n := int(entryCount)
		/* FIXME: check that buf is long enough */
		out.glyphIDs = buf[8 : 8+n*2]
		dynSize += n * 2
		buf = buf[8+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapSubtableFormat6) GlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.glyphIDs[i*2:(i+1)*2:len(tbl.glyphIDs)], &out)
	return out
}

func (tbl *CmapSubtableFormat6) GlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumGlyphIDs() {
			if !yield(i, tbl.GlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *CmapSubtableFormat6) NumGlyphIDs() int {
	return len(tbl.glyphIDs) / 2
}

func ParseCmapTable(buf []byte, out *CmapTable) int {
	*out = CmapTable{}
	origBuf := buf
	var dynSize int
	var numTables uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseUint16(buf[2:4], &numTables)
	{
		n := int(numTables)
		/* FIXME: check that buf is long enough */
		out.encodingRecords = buf[4 : 4+n*8]
		dynSize += n * 8
		buf = buf[4+n*8:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CmapTable) EncodingRecord(i int) EncodingRecord {
	var out EncodingRecord
	parseEncodingRecord(tbl.encodingRecords[i*8:(i+1)*8:len(tbl.encodingRecords)], tbl.data, &out)
	return out
}

func (tbl *CmapTable) EncodingRecords() iter.Seq2[int, EncodingRecord] {
	return func(yield func(int, EncodingRecord) bool) {
		for i := range tbl.NumEncodingRecords() {
			if !yield(i, tbl.EncodingRecord(i)) {
				return
			}
		}
	}
}

func (tbl *CmapTable) NumEncodingRecords() int {
	return len(tbl.encodingRecords) / 8
}

func parseConstantMapGroupRecord(buf []byte, out *ConstantMapGroupRecord) int {
	*out = ConstantMapGroupRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.StartCharCode)
	parseUint32(buf[4:8], &out.EndCharCode)
	parseUint32(buf[8:12], &out.GlyphID)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseDefaultUVSTable(buf []byte, out *DefaultUVSTable) int {
	*out = DefaultUVSTable{}
	origBuf := buf
	var dynSize int
	var numUnicodeValueRanges uint32

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint32(buf[0:4], &numUnicodeValueRanges)
	{
		n := int(numUnicodeValueRanges)
		/* FIXME: check that buf is long enough */
		out.ranges = buf[4 : 4+n*5]
		dynSize += n * 5
		buf = buf[4+n*5:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *DefaultUVSTable) Range(i int) UnicodeRangeRecord {
	var out UnicodeRangeRecord
	parseUnicodeRangeRecord(tbl.ranges[i*5:(i+1)*5:len(tbl.ranges)], &out)
	return out
}

func (tbl *DefaultUVSTable) Ranges() iter.Seq2[int, UnicodeRangeRecord] {
	return func(yield func(int, UnicodeRangeRecord) bool) {
		for i := range tbl.NumRanges() {
			if !yield(i, tbl.Range(i)) {
				return
			}
		}
	}
}

func (tbl *DefaultUVSTable) NumRanges() int {
	return len(tbl.ranges) / 5
}

func parseEncodingRecord(buf, parentBuf []byte, out *EncodingRecord) int {
	*out = EncodingRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parsePlatformID(buf[0:2], &out.PlatformID)
	parseEncodingID(buf[2:4], &out.EncodingID)
	parseOffset32(buf[4:8], &out.subtableOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *EncodingRecord) Subtable(into *CmapSubtable) bool {
	// FIXME: check bounds
	if tbl.subtableOffset == 0 {
		return false
	}
	parseCmapSubtable(tbl.parentData[tbl.subtableOffset:], into)
	return true
}

func ParseNonDefaultUVSTable(buf []byte, out *NonDefaultUVSTable) int {
	*out = NonDefaultUVSTable{}
	origBuf := buf
	var dynSize int
	var numUVSMappings uint32

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint32(buf[0:4], &numUVSMappings)
	{
		n := int(numUVSMappings)
		/* FIXME: check that buf is long enough */
		out.uvsMappings = buf[4 : 4+n*6]
		dynSize += n * 6
		buf = buf[4+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *NonDefaultUVSTable) UvsMapping(i int) UVSMappingRecord {
	var out UVSMappingRecord
	parseUVSMappingRecord(tbl.uvsMappings[i*6:(i+1)*6:len(tbl.uvsMappings)], &out)
	return out
}

func (tbl *NonDefaultUVSTable) UvsMappings() iter.Seq2[int, UVSMappingRecord] {
	return func(yield func(int, UVSMappingRecord) bool) {
		for i := range tbl.NumUvsMappings() {
			if !yield(i, tbl.UvsMapping(i)) {
				return
			}
		}
	}
}

func (tbl *NonDefaultUVSTable) NumUvsMappings() int {
	return len(tbl.uvsMappings) / 6
}

func parseSequentialMapGroupRecord(buf []byte, out *SequentialMapGroupRecord) int {
	*out = SequentialMapGroupRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.StartCharCode)
	parseUint32(buf[4:8], &out.EndCharCode)
	parseUint32(buf[8:12], &out.StartGlyphID)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseUVSMappingRecord(buf []byte, out *UVSMappingRecord) int {
	*out = UVSMappingRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint24(buf[0:4], &out.UnicodeValue)
	parseUint16(buf[4:6], &out.GlyphID)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseUnicodeRangeRecord(buf []byte, out *UnicodeRangeRecord) int {
	*out = UnicodeRangeRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 5 {
		return dynSize
	}
	parseUint24(buf[0:4], &out.StartUnicodeValue)
	out.AdditionalCount = buf[4:5][0]
	_ = buf
	_ = origBuf
	return dynSize
}

func parseVariationSelectorRecord(buf []byte, out *VariationSelectorRecord) int {
	*out = VariationSelectorRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint24(buf[0:4], &out.VarSelector)
	parseOffset32(buf[4:8], &out.DefaultUVSOffset)
	parseOffset32(buf[8:12], &out.NonDefaultUVSOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

