// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

import (
	"encoding/binary"
)

type ScriptListTable struct {
	data []byte

	scriptRecords Slice[ScriptRecord]
}

type ScriptRecord struct {
	parentData []byte

	ScriptTag    Tag
	scriptOffset Offset16[ScriptTable]
}

type ScriptTable struct {
	data []byte

	defaultLangSysOffset Offset16[LangSysTable]

	langSysRecords Slice[LangSysRecord]
}

type LangSysRecord struct {
	parentData []byte

	LangSysTag    Tag
	langSysOffset Offset16[LangSysTable]
}

type LangSysTable struct {
	RequiredFeatureIndex uint16

	featureIndices Slice[uint16]
}

type FeatureListTable struct {
	data []byte

	featureRecords Slice[FeatureRecord]
}

type FeatureRecord struct {
	parentData []byte

	FeatureTag    Tag
	featureOffset Offset16[FeatureTable]
}

type FeatureTable struct {
	data []byte

	// May be one of various feature parameter tables
	featureParamsOffset Offset16[any]

	lookupListIndices Slice[uint16]
}

type FeatureParamsCvTable struct {
	Format  uint16
	Format0 FeatureParamsCvTableFormat0
}

type FeatureParamsCvTableFormat0 struct {
	FeatUILabelNameID       uint16
	FeatUITooltipTextNameID uint16
	SampleTextNameID        uint16
	NumNamedParameters      uint16
	FirstParamUILabelNameID uint16

	characters Slice[Uint24]
}

type LookupListTable struct {
	data []byte

	lookupOffsets Slice[Offset16[LookupTable]]
}

type LookupTable struct {
	data []byte

	LookupType uint16
	LookupFlag uint16

	// XXX figure out the right type for the offset tparam
	subtableOffsets  Slice[Offset16[any]]
	MarkFilteringSet uint16
}

type CoverageTable struct {
	data []byte

	CoverageFormat uint16
	Format1        CoverageTableFormat1
	Format2        CoverageTableFormat2
}

type CoverageTableFormat1 struct {
	glyphArray Slice[uint16]
}

type CoverageTableFormat2 struct {
	data []byte

	rangeRecords Slice[RangeRecord]
}

type RangeRecord struct {
	StartGlyphID       uint16
	EndGlyphID         uint16
	StartCoverageIndex uint16
}

type ClassDefTable struct {
	ClassFormat uint16
	Format1     ClassDefTableFormat1
	Format2     ClassDefTableFormat2
}

type ClassDefTableFormat1 struct {
	StartGlyphID uint16

	classValueArray Slice[uint16]
}

type ClassDefTableFormat2 struct {
	classRangeRecords Slice[ClassRangeRecord]
}

type ClassRangeRecord struct {
	StartGlyphID uint16
	EndGlyphID   uint16
	Class        uint16
}

type SequenceLookupRecord struct {
	SequenceIndex   uint16
	LookupListIndex uint16
}

type SequenceContextTable struct {
	data []byte

	Format  uint16
	Format1 SequenceContextTableFormat1
	Format2 SequenceContextTableFormat2
	Format3 SequenceContextTableFormat3
}

type SequenceContextTableFormat1 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]

	seqRuleSetOffsets Slice[Offset16[SequenceRuleSetTable]]
}

type SequenceRuleSetTable struct {
	data []byte

	seqRuleOffsets Slice[Offset16[SequenceRuleTable]]
}

type SequenceRuleTable struct {
	data []byte

	inputSequence    Slice[uint16]
	seqLookupRecords Slice[SequenceLookupRecord]
}

type SequenceContextTableFormat2 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]
	classDefOffset Offset16[ClassDefTable]

	classSeqRuleSetOffsets Slice[Offset16[ClassSequenceRuleSetTable]]
}

type ClassSequenceRuleSetTable struct {
	classSeqRuleOffsets Slice[Offset16[ClassSequenceRuleTable]]
}

type ClassSequenceRuleTable struct {
	inputSequence    Slice[uint16]
	seqLookupRecords Slice[SequenceLookupRecord]
}

type SequenceContextTableFormat3 struct {
	parentData []byte

	coverageOffsets  Slice[Offset16[CoverageTable]]
	seqLookupRecords Slice[SequenceLookupRecord]
}

type FeatureVariationsTable struct {
	data []byte

	MajorVersion uint16
	MinorVersion uint16

	featureVariationRecords Slice[FeatureVariationRecord]
}

type FeatureVariationRecord struct {
	parentData []byte

	conditionSetOffset             Offset32[ConditionSetTable]
	featureTableSubstitutionOffset Offset32[FeatureTableSubstitutionTable]
}

type ConditionSetTable struct {
	data []byte

	conditions Slice[Offset32[ConditionTable]]
}

type ConditionTable struct {
	Format  uint16
	Format1 ConditionTableFormat1
}

type ConditionTableFormat1 struct {
	axisIndex           uint16
	FilterRangeMinValue Int2_14
	FilterRangeMaxValue Int2_14
}

type FeatureTableSubstitutionTable struct {
	data []byte

	MajorVersion uint16
	MinorVersion uint16

	substitutions Slice[FeatureTableSubstitutionRecord]
}

type FeatureTableSubstitutionRecord struct {
	parentData []byte

	FeatureIndex           uint16
	alternateFeatureOffset Offset32[FeatureTable]
}

type DeviceOrVariationIndexTable struct {
	DeltaFormat    uint16
	Device         DeviceTable
	VariationIndex VariationIndexTable
}

func ParseDeviceOrVariationIndexTable(data []byte, out *DeviceOrVariationIndexTable) int {
	*out = DeviceOrVariationIndexTable{}
	out.DeltaFormat = binary.BigEndian.Uint16(data[4:6])
	switch out.DeltaFormat {
	case 1, 2, 3:
		return ParseDeviceTable(data, &out.Device)
	case 0x8000:
		return ParseVariationIndexTable(data, &out.VariationIndex)
	default:
		// XXX return error
		return 0
	}
}

type DeviceTable struct {
	StartSize   uint16
	EndSize     uint16
	DeltaFormat uint16
	deltaValues Slice[uint16]
}

type VariationIndexTable struct {
	DeltaSetOuterIndex uint16
	DeltaSetInnerIndex uint16
	DeltaFormat        uint16
}
func ParseClassDefTable(buf []byte, out *ClassDefTable) int {
	*out = ClassDefTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.ClassFormat)

	switch out.ClassFormat {
	case 1:
		dynSize += parseClassDefTableFormat1(buf[2:], &out.Format1)
	case 2:
		dynSize += parseClassDefTableFormat2(buf[2:], &out.Format2)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseClassDefTableFormat1(buf []byte, out *ClassDefTableFormat1) int {
	*out = ClassDefTableFormat1{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.StartGlyphID)
	parseUint16(buf[2:4], &glyphCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.classValueArray = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ClassDefTableFormat1) GetClassValueArray(i int) uint16 {
	var out uint16
	parseUint16(tbl.classValueArray[i*2:(i+1)*2:len(tbl.classValueArray)], &out)
	return out
}

func (tbl *ClassDefTableFormat1) ClassValueArray() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumClassValueArray() {
			if !yield(i, tbl.GetClassValueArray(i)) {
				return
			}
		}
	}
}

func (tbl *ClassDefTableFormat1) NumClassValueArray() int {
	return len(tbl.classValueArray) / 2
}

func parseClassDefTableFormat2(buf []byte, out *ClassDefTableFormat2) int {
	*out = ClassDefTableFormat2{}
	origBuf := buf
	var dynSize int
	var classRangeCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &classRangeCount)
	{
		n := int(classRangeCount)
		/* FIXME: check that buf is long enough */
		out.classRangeRecords = buf[2 : 2+n*6]
		dynSize += n * 6
		buf = buf[2+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ClassDefTableFormat2) ClassRangeRecord(i int) ClassRangeRecord {
	var out ClassRangeRecord
	parseClassRangeRecord(tbl.classRangeRecords[i*6:(i+1)*6:len(tbl.classRangeRecords)], &out)
	return out
}

func (tbl *ClassDefTableFormat2) ClassRangeRecords() iter.Seq2[int, ClassRangeRecord] {
	return func(yield func(int, ClassRangeRecord) bool) {
		for i := range tbl.NumClassRangeRecords() {
			if !yield(i, tbl.ClassRangeRecord(i)) {
				return
			}
		}
	}
}

func (tbl *ClassDefTableFormat2) NumClassRangeRecords() int {
	return len(tbl.classRangeRecords) / 6
}

func parseClassRangeRecord(buf []byte, out *ClassRangeRecord) int {
	*out = ClassRangeRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.StartGlyphID)
	parseUint16(buf[2:4], &out.EndGlyphID)
	parseUint16(buf[4:6], &out.Class)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseClassSequenceRuleSetTable(buf []byte, out *ClassSequenceRuleSetTable) int {
	*out = ClassSequenceRuleSetTable{}
	origBuf := buf
	var dynSize int
	var classSeqRuleCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &classSeqRuleCount)
	{
		n := int(classSeqRuleCount)
		/* FIXME: check that buf is long enough */
		out.classSeqRuleOffsets = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ClassSequenceRuleSetTable) NumClassSeqRuleOffsets() int {
	return len(tbl.classSeqRuleOffsets) / 2
}

func ParseClassSequenceRuleTable(buf []byte, out *ClassSequenceRuleTable) int {
	*out = ClassSequenceRuleTable{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16
	var seqLookupCount uint16

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	parseUint16(buf[2:4], &seqLookupCount)
	{
		n := int(glyphCount - 1)
		/* FIXME: check that buf is long enough */
		out.inputSequence = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	{
		n := int(seqLookupCount)
		/* FIXME: check that buf is long enough */
		out.seqLookupRecords = buf[0 : 0+n*4]
		dynSize += n * 4
		buf = buf[0+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ClassSequenceRuleTable) GetInputSequence(i int) uint16 {
	var out uint16
	parseUint16(tbl.inputSequence[i*2:(i+1)*2:len(tbl.inputSequence)], &out)
	return out
}

func (tbl *ClassSequenceRuleTable) InputSequence() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumInputSequence() {
			if !yield(i, tbl.GetInputSequence(i)) {
				return
			}
		}
	}
}

func (tbl *ClassSequenceRuleTable) NumInputSequence() int {
	return len(tbl.inputSequence) / 2
}

func (tbl *ClassSequenceRuleTable) SeqLookupRecord(i int) SequenceLookupRecord {
	var out SequenceLookupRecord
	parseSequenceLookupRecord(tbl.seqLookupRecords[i*4:(i+1)*4:len(tbl.seqLookupRecords)], &out)
	return out
}

func (tbl *ClassSequenceRuleTable) SeqLookupRecords() iter.Seq2[int, SequenceLookupRecord] {
	return func(yield func(int, SequenceLookupRecord) bool) {
		for i := range tbl.NumSeqLookupRecords() {
			if !yield(i, tbl.SeqLookupRecord(i)) {
				return
			}
		}
	}
}

func (tbl *ClassSequenceRuleTable) NumSeqLookupRecords() int {
	return len(tbl.seqLookupRecords) / 4
}

func ParseConditionSetTable(buf []byte, out *ConditionSetTable) int {
	*out = ConditionSetTable{}
	origBuf := buf
	var dynSize int
	var conditionCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &conditionCount)
	{
		n := int(conditionCount)
		/* FIXME: check that buf is long enough */
		out.conditions = buf[2 : 2+n*4]
		dynSize += n * 4
		buf = buf[2+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ConditionSetTable) NumConditions() int {
	return len(tbl.conditions) / 4
}

func ParseConditionTable(buf []byte, out *ConditionTable) int {
	*out = ConditionTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 1:
		parseConditionTableFormat1(buf[2:8], &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseConditionTableFormat1(buf []byte, out *ConditionTableFormat1) int {
	*out = ConditionTableFormat1{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.axisIndex)
	parseInt2_14(buf[2:4], &out.FilterRangeMinValue)
	parseInt2_14(buf[4:6], &out.FilterRangeMaxValue)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseCoverageTable(buf []byte, out *CoverageTable) int {
	*out = CoverageTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.CoverageFormat)

	switch out.CoverageFormat {
	case 1:
		dynSize += parseCoverageTableFormat1(buf[2:], &out.Format1)
	case 2:
		dynSize += parseCoverageTableFormat2(buf[2:], &out.Format2)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseCoverageTableFormat1(buf []byte, out *CoverageTableFormat1) int {
	*out = CoverageTableFormat1{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.glyphArray = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CoverageTableFormat1) GetGlyphArray(i int) uint16 {
	var out uint16
	parseUint16(tbl.glyphArray[i*2:(i+1)*2:len(tbl.glyphArray)], &out)
	return out
}

func (tbl *CoverageTableFormat1) GlyphArray() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumGlyphArray() {
			if !yield(i, tbl.GetGlyphArray(i)) {
				return
			}
		}
	}
}

func (tbl *CoverageTableFormat1) NumGlyphArray() int {
	return len(tbl.glyphArray) / 2
}

func parseCoverageTableFormat2(buf []byte, out *CoverageTableFormat2) int {
	*out = CoverageTableFormat2{}
	origBuf := buf
	var dynSize int
	var rangeCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &rangeCount)
	{
		n := int(rangeCount)
		/* FIXME: check that buf is long enough */
		out.rangeRecords = buf[2 : 2+n*6]
		dynSize += n * 6
		buf = buf[2+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CoverageTableFormat2) RangeRecord(i int) RangeRecord {
	var out RangeRecord
	parseRangeRecord(tbl.rangeRecords[i*6:(i+1)*6:len(tbl.rangeRecords)], &out)
	return out
}

func (tbl *CoverageTableFormat2) RangeRecords() iter.Seq2[int, RangeRecord] {
	return func(yield func(int, RangeRecord) bool) {
		for i := range tbl.NumRangeRecords() {
			if !yield(i, tbl.RangeRecord(i)) {
				return
			}
		}
	}
}

func (tbl *CoverageTableFormat2) NumRangeRecords() int {
	return len(tbl.rangeRecords) / 6
}

func ParseDeviceTable(buf []byte, out *DeviceTable) int {
	*out = DeviceTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.StartSize)
	parseUint16(buf[2:4], &out.EndSize)
	parseUint16(buf[4:6], &out.DeltaFormat)
	{
		out.deltaValues = buf[6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *DeviceTable) DeltaValue(i int) uint16 {
	var out uint16
	parseUint16(tbl.deltaValues[i*2:(i+1)*2:len(tbl.deltaValues)], &out)
	return out
}

func (tbl *DeviceTable) DeltaValues() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumDeltaValues() {
			if !yield(i, tbl.DeltaValue(i)) {
				return
			}
		}
	}
}

func (tbl *DeviceTable) NumDeltaValues() int {
	return len(tbl.deltaValues) / 2
}

func ParseFeatureListTable(buf []byte, out *FeatureListTable) int {
	*out = FeatureListTable{}
	origBuf := buf
	var dynSize int
	var featureCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &featureCount)
	{
		n := int(featureCount)
		/* FIXME: check that buf is long enough */
		out.featureRecords = buf[2 : 2+n*6]
		dynSize += n * 6
		buf = buf[2+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *FeatureListTable) FeatureRecord(i int) FeatureRecord {
	var out FeatureRecord
	parseFeatureRecord(tbl.featureRecords[i*6:(i+1)*6:len(tbl.featureRecords)], tbl.data, &out)
	return out
}

func (tbl *FeatureListTable) FeatureRecords() iter.Seq2[int, FeatureRecord] {
	return func(yield func(int, FeatureRecord) bool) {
		for i := range tbl.NumFeatureRecords() {
			if !yield(i, tbl.FeatureRecord(i)) {
				return
			}
		}
	}
}

func (tbl *FeatureListTable) NumFeatureRecords() int {
	return len(tbl.featureRecords) / 6
}

func ParseFeatureParamsCvTable(buf []byte, out *FeatureParamsCvTable) int {
	*out = FeatureParamsCvTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 0:
		dynSize += parseFeatureParamsCvTableFormat0(buf[2:], &out.Format0)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseFeatureParamsCvTableFormat0(buf []byte, out *FeatureParamsCvTableFormat0) int {
	*out = FeatureParamsCvTableFormat0{}
	origBuf := buf
	var dynSize int
	var charCount uint16

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.FeatUILabelNameID)
	parseUint16(buf[2:4], &out.FeatUITooltipTextNameID)
	parseUint16(buf[4:6], &out.SampleTextNameID)
	parseUint16(buf[6:8], &out.NumNamedParameters)
	parseUint16(buf[8:10], &out.FirstParamUILabelNameID)
	parseUint16(buf[10:12], &charCount)
	{
		n := int(charCount)
		/* FIXME: check that buf is long enough */
		out.characters = buf[12 : 12+n*4]
		dynSize += n * 4
		buf = buf[12+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *FeatureParamsCvTableFormat0) Character(i int) Uint24 {
	var out Uint24
	parseUint24(tbl.characters[i*4:(i+1)*4:len(tbl.characters)], &out)
	return out
}

func (tbl *FeatureParamsCvTableFormat0) Characters() iter.Seq2[int, Uint24] {
	return func(yield func(int, Uint24) bool) {
		for i := range tbl.NumCharacters() {
			if !yield(i, tbl.Character(i)) {
				return
			}
		}
	}
}

func (tbl *FeatureParamsCvTableFormat0) NumCharacters() int {
	return len(tbl.characters) / 4
}

func parseFeatureRecord(buf, parentBuf []byte, out *FeatureRecord) int {
	*out = FeatureRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseTag(buf[0:4], &out.FeatureTag)
	parseOffset16(buf[4:6], &out.featureOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *FeatureRecord) Feature(into *FeatureTable) bool {
	// FIXME: check bounds
	if tbl.featureOffset == 0 {
		return false
	}
	ParseFeatureTable(tbl.parentData[tbl.featureOffset:], into)
	return true
}

func ParseFeatureTable(buf []byte, out *FeatureTable) int {
	*out = FeatureTable{}
	origBuf := buf
	var dynSize int
	var lookupIndexCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.featureParamsOffset)
	parseUint16(buf[2:4], &lookupIndexCount)
	{
		n := int(lookupIndexCount)
		/* FIXME: check that buf is long enough */
		out.lookupListIndices = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *FeatureTable) LookupListIndice(i int) uint16 {
	var out uint16
	parseUint16(tbl.lookupListIndices[i*2:(i+1)*2:len(tbl.lookupListIndices)], &out)
	return out
}

func (tbl *FeatureTable) LookupListIndices() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumLookupListIndices() {
			if !yield(i, tbl.LookupListIndice(i)) {
				return
			}
		}
	}
}

func (tbl *FeatureTable) NumLookupListIndices() int {
	return len(tbl.lookupListIndices) / 2
}

func parseFeatureTableSubstitutionRecord(buf, parentBuf []byte, out *FeatureTableSubstitutionRecord) int {
	*out = FeatureTableSubstitutionRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.FeatureIndex)
	parseOffset32(buf[2:6], &out.alternateFeatureOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *FeatureTableSubstitutionRecord) AlternateFeature(into *FeatureTable) bool {
	// FIXME: check bounds
	if tbl.alternateFeatureOffset == 0 {
		return false
	}
	ParseFeatureTable(tbl.parentData[tbl.alternateFeatureOffset:], into)
	return true
}

func ParseFeatureTableSubstitutionTable(buf []byte, out *FeatureTableSubstitutionTable) int {
	*out = FeatureTableSubstitutionTable{}
	origBuf := buf
	var dynSize int
	var substitutionCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseUint16(buf[4:6], &substitutionCount)
	{
		n := int(substitutionCount)
		/* FIXME: check that buf is long enough */
		out.substitutions = buf[6 : 6+n*6]
		dynSize += n * 6
		buf = buf[6+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *FeatureTableSubstitutionTable) Substitution(i int) FeatureTableSubstitutionRecord {
	var out FeatureTableSubstitutionRecord
	parseFeatureTableSubstitutionRecord(tbl.substitutions[i*6:(i+1)*6:len(tbl.substitutions)], tbl.data, &out)
	return out
}

func (tbl *FeatureTableSubstitutionTable) Substitutions() iter.Seq2[int, FeatureTableSubstitutionRecord] {
	return func(yield func(int, FeatureTableSubstitutionRecord) bool) {
		for i := range tbl.NumSubstitutions() {
			if !yield(i, tbl.Substitution(i)) {
				return
			}
		}
	}
}

func (tbl *FeatureTableSubstitutionTable) NumSubstitutions() int {
	return len(tbl.substitutions) / 6
}

func parseFeatureVariationRecord(buf, parentBuf []byte, out *FeatureVariationRecord) int {
	*out = FeatureVariationRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseOffset32(buf[0:4], &out.conditionSetOffset)
	parseOffset32(buf[4:8], &out.featureTableSubstitutionOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *FeatureVariationRecord) ConditionSet(into *ConditionSetTable) bool {
	// FIXME: check bounds
	if tbl.conditionSetOffset == 0 {
		return false
	}
	ParseConditionSetTable(tbl.parentData[tbl.conditionSetOffset:], into)
	return true
}

func (tbl *FeatureVariationRecord) FeatureTableSubstitution(into *FeatureTableSubstitutionTable) bool {
	// FIXME: check bounds
	if tbl.featureTableSubstitutionOffset == 0 {
		return false
	}
	ParseFeatureTableSubstitutionTable(tbl.parentData[tbl.featureTableSubstitutionOffset:], into)
	return true
}

func ParseFeatureVariationsTable(buf []byte, out *FeatureVariationsTable) int {
	*out = FeatureVariationsTable{}
	origBuf := buf
	var dynSize int
	var featureVariationRecordCount uint32
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseUint32(buf[4:8], &featureVariationRecordCount)
	{
		n := int(featureVariationRecordCount)
		/* FIXME: check that buf is long enough */
		out.featureVariationRecords = buf[8 : 8+n*8]
		dynSize += n * 8
		buf = buf[8+n*8:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *FeatureVariationsTable) FeatureVariationRecord(i int) FeatureVariationRecord {
	var out FeatureVariationRecord
	parseFeatureVariationRecord(tbl.featureVariationRecords[i*8:(i+1)*8:len(tbl.featureVariationRecords)], tbl.data, &out)
	return out
}

func (tbl *FeatureVariationsTable) FeatureVariationRecords() iter.Seq2[int, FeatureVariationRecord] {
	return func(yield func(int, FeatureVariationRecord) bool) {
		for i := range tbl.NumFeatureVariationRecords() {
			if !yield(i, tbl.FeatureVariationRecord(i)) {
				return
			}
		}
	}
}

func (tbl *FeatureVariationsTable) NumFeatureVariationRecords() int {
	return len(tbl.featureVariationRecords) / 8
}

func parseLangSysRecord(buf, parentBuf []byte, out *LangSysRecord) int {
	*out = LangSysRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseTag(buf[0:4], &out.LangSysTag)
	parseOffset16(buf[4:6], &out.langSysOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *LangSysRecord) LangSys(into *LangSysTable) bool {
	// FIXME: check bounds
	if tbl.langSysOffset == 0 {
		return false
	}
	ParseLangSysTable(tbl.parentData[tbl.langSysOffset:], into)
	return true
}

func ParseLangSysTable(buf []byte, out *LangSysTable) int {
	*out = LangSysTable{}
	origBuf := buf
	var dynSize int
	var featureIndexCount uint16

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.RequiredFeatureIndex)
	parseUint16(buf[4:6], &featureIndexCount)
	{
		n := int(featureIndexCount)
		/* FIXME: check that buf is long enough */
		out.featureIndices = buf[6 : 6+n*2]
		dynSize += n * 2
		buf = buf[6+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LangSysTable) FeatureIndice(i int) uint16 {
	var out uint16
	parseUint16(tbl.featureIndices[i*2:(i+1)*2:len(tbl.featureIndices)], &out)
	return out
}

func (tbl *LangSysTable) FeatureIndices() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumFeatureIndices() {
			if !yield(i, tbl.FeatureIndice(i)) {
				return
			}
		}
	}
}

func (tbl *LangSysTable) NumFeatureIndices() int {
	return len(tbl.featureIndices) / 2
}

func ParseLookupListTable(buf []byte, out *LookupListTable) int {
	*out = LookupListTable{}
	origBuf := buf
	var dynSize int
	var lookupCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &lookupCount)
	{
		n := int(lookupCount)
		/* FIXME: check that buf is long enough */
		out.lookupOffsets = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LookupListTable) NumLookupOffsets() int {
	return len(tbl.lookupOffsets) / 2
}

func ParseLookupTable(buf []byte, out *LookupTable) int {
	*out = LookupTable{}
	origBuf := buf
	var dynSize int
	var subTableCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.LookupType)
	parseUint16(buf[2:4], &out.LookupFlag)
	parseUint16(buf[4:6], &subTableCount)
	{
		n := int(subTableCount)
		/* FIXME: check that buf is long enough */
		out.subtableOffsets = buf[6 : 6+n*2]
		dynSize += n * 2
		buf = buf[6+n*2:]
	}

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MarkFilteringSet)
	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LookupTable) NumSubtableOffsets() int {
	return len(tbl.subtableOffsets) / 2
}

func parseRangeRecord(buf []byte, out *RangeRecord) int {
	*out = RangeRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.StartGlyphID)
	parseUint16(buf[2:4], &out.EndGlyphID)
	parseUint16(buf[4:6], &out.StartCoverageIndex)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseScriptListTable(buf []byte, out *ScriptListTable) int {
	*out = ScriptListTable{}
	origBuf := buf
	var dynSize int
	var scriptCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &scriptCount)
	{
		n := int(scriptCount)
		/* FIXME: check that buf is long enough */
		out.scriptRecords = buf[2 : 2+n*6]
		dynSize += n * 6
		buf = buf[2+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ScriptListTable) ScriptRecord(i int) ScriptRecord {
	var out ScriptRecord
	parseScriptRecord(tbl.scriptRecords[i*6:(i+1)*6:len(tbl.scriptRecords)], tbl.data, &out)
	return out
}

func (tbl *ScriptListTable) ScriptRecords() iter.Seq2[int, ScriptRecord] {
	return func(yield func(int, ScriptRecord) bool) {
		for i := range tbl.NumScriptRecords() {
			if !yield(i, tbl.ScriptRecord(i)) {
				return
			}
		}
	}
}

func (tbl *ScriptListTable) NumScriptRecords() int {
	return len(tbl.scriptRecords) / 6
}

func parseScriptRecord(buf, parentBuf []byte, out *ScriptRecord) int {
	*out = ScriptRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseTag(buf[0:4], &out.ScriptTag)
	parseOffset16(buf[4:6], &out.scriptOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *ScriptRecord) Script(into *ScriptTable) bool {
	// FIXME: check bounds
	if tbl.scriptOffset == 0 {
		return false
	}
	ParseScriptTable(tbl.parentData[tbl.scriptOffset:], into)
	return true
}

func ParseScriptTable(buf []byte, out *ScriptTable) int {
	*out = ScriptTable{}
	origBuf := buf
	var dynSize int
	var langSysCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.defaultLangSysOffset)
	parseUint16(buf[2:4], &langSysCount)
	{
		n := int(langSysCount)
		/* FIXME: check that buf is long enough */
		out.langSysRecords = buf[4 : 4+n*6]
		dynSize += n * 6
		buf = buf[4+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *ScriptTable) DefaultLangSys(into *LangSysTable) bool {
	// FIXME: check bounds
	if tbl.defaultLangSysOffset == 0 {
		return false
	}
	ParseLangSysTable(tbl.data[tbl.defaultLangSysOffset:], into)
	return true
}

func (tbl *ScriptTable) LangSysRecord(i int) LangSysRecord {
	var out LangSysRecord
	parseLangSysRecord(tbl.langSysRecords[i*6:(i+1)*6:len(tbl.langSysRecords)], tbl.data, &out)
	return out
}

func (tbl *ScriptTable) LangSysRecords() iter.Seq2[int, LangSysRecord] {
	return func(yield func(int, LangSysRecord) bool) {
		for i := range tbl.NumLangSysRecords() {
			if !yield(i, tbl.LangSysRecord(i)) {
				return
			}
		}
	}
}

func (tbl *ScriptTable) NumLangSysRecords() int {
	return len(tbl.langSysRecords) / 6
}

func ParseSequenceContextTable(buf []byte, out *SequenceContextTable) int {
	*out = SequenceContextTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 1:
		dynSize += parseSequenceContextTableFormat1(buf[2:], buf, &out.Format1)
	case 2:
		dynSize += parseSequenceContextTableFormat2(buf[2:], buf, &out.Format2)
	case 3:
		dynSize += parseSequenceContextTableFormat3(buf[2:], buf, &out.Format3)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseSequenceContextTableFormat1(buf, parentBuf []byte, out *SequenceContextTableFormat1) int {
	*out = SequenceContextTableFormat1{}
	origBuf := buf
	var dynSize int
	var seqRuleSetCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &seqRuleSetCount)
	{
		n := int(seqRuleSetCount)
		/* FIXME: check that buf is long enough */
		out.seqRuleSetOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *SequenceContextTableFormat1) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *SequenceContextTableFormat1) NumSeqRuleSetOffsets() int {
	return len(tbl.seqRuleSetOffsets) / 2
}

func parseSequenceContextTableFormat2(buf, parentBuf []byte, out *SequenceContextTableFormat2) int {
	*out = SequenceContextTableFormat2{}
	origBuf := buf
	var dynSize int
	var classSeqRuleSetCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseOffset16(buf[2:4], &out.classDefOffset)
	parseUint16(buf[4:6], &classSeqRuleSetCount)
	{
		n := int(classSeqRuleSetCount)
		/* FIXME: check that buf is long enough */
		out.classSeqRuleSetOffsets = buf[6 : 6+n*2]
		dynSize += n * 2
		buf = buf[6+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *SequenceContextTableFormat2) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *SequenceContextTableFormat2) ClassDef(into *ClassDefTable) bool {
	// FIXME: check bounds
	if tbl.classDefOffset == 0 {
		return false
	}
	ParseClassDefTable(tbl.parentData[tbl.classDefOffset:], into)
	return true
}

func (tbl *SequenceContextTableFormat2) NumClassSeqRuleSetOffsets() int {
	return len(tbl.classSeqRuleSetOffsets) / 2
}

func parseSequenceContextTableFormat3(buf, parentBuf []byte, out *SequenceContextTableFormat3) int {
	*out = SequenceContextTableFormat3{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16
	var seqLookupCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	parseUint16(buf[2:4], &seqLookupCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.coverageOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	{
		n := int(seqLookupCount)
		/* FIXME: check that buf is long enough */
		out.seqLookupRecords = buf[0 : 0+n*4]
		dynSize += n * 4
		buf = buf[0+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SequenceContextTableFormat3) NumCoverageOffsets() int {
	return len(tbl.coverageOffsets) / 2
}

func (tbl *SequenceContextTableFormat3) SeqLookupRecord(i int) SequenceLookupRecord {
	var out SequenceLookupRecord
	parseSequenceLookupRecord(tbl.seqLookupRecords[i*4:(i+1)*4:len(tbl.seqLookupRecords)], &out)
	return out
}

func (tbl *SequenceContextTableFormat3) SeqLookupRecords() iter.Seq2[int, SequenceLookupRecord] {
	return func(yield func(int, SequenceLookupRecord) bool) {
		for i := range tbl.NumSeqLookupRecords() {
			if !yield(i, tbl.SeqLookupRecord(i)) {
				return
			}
		}
	}
}

func (tbl *SequenceContextTableFormat3) NumSeqLookupRecords() int {
	return len(tbl.seqLookupRecords) / 4
}

func parseSequenceLookupRecord(buf []byte, out *SequenceLookupRecord) int {
	*out = SequenceLookupRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SequenceIndex)
	parseUint16(buf[2:4], &out.LookupListIndex)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseSequenceRuleSetTable(buf []byte, out *SequenceRuleSetTable) int {
	*out = SequenceRuleSetTable{}
	origBuf := buf
	var dynSize int
	var seqRuleCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &seqRuleCount)
	{
		n := int(seqRuleCount)
		/* FIXME: check that buf is long enough */
		out.seqRuleOffsets = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SequenceRuleSetTable) NumSeqRuleOffsets() int {
	return len(tbl.seqRuleOffsets) / 2
}

func ParseSequenceRuleTable(buf []byte, out *SequenceRuleTable) int {
	*out = SequenceRuleTable{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16
	var seqLookupCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	parseUint16(buf[2:4], &seqLookupCount)
	{
		n := int(glyphCount - 1)
		/* FIXME: check that buf is long enough */
		out.inputSequence = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	{
		n := int(seqLookupCount)
		/* FIXME: check that buf is long enough */
		out.seqLookupRecords = buf[0 : 0+n*4]
		dynSize += n * 4
		buf = buf[0+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SequenceRuleTable) GetInputSequence(i int) uint16 {
	var out uint16
	parseUint16(tbl.inputSequence[i*2:(i+1)*2:len(tbl.inputSequence)], &out)
	return out
}

func (tbl *SequenceRuleTable) InputSequence() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumInputSequence() {
			if !yield(i, tbl.GetInputSequence(i)) {
				return
			}
		}
	}
}

func (tbl *SequenceRuleTable) NumInputSequence() int {
	return len(tbl.inputSequence) / 2
}

func (tbl *SequenceRuleTable) SeqLookupRecord(i int) SequenceLookupRecord {
	var out SequenceLookupRecord
	parseSequenceLookupRecord(tbl.seqLookupRecords[i*4:(i+1)*4:len(tbl.seqLookupRecords)], &out)
	return out
}

func (tbl *SequenceRuleTable) SeqLookupRecords() iter.Seq2[int, SequenceLookupRecord] {
	return func(yield func(int, SequenceLookupRecord) bool) {
		for i := range tbl.NumSeqLookupRecords() {
			if !yield(i, tbl.SeqLookupRecord(i)) {
				return
			}
		}
	}
}

func (tbl *SequenceRuleTable) NumSeqLookupRecords() int {
	return len(tbl.seqLookupRecords) / 4
}

func ParseVariationIndexTable(buf []byte, out *VariationIndexTable) int {
	*out = VariationIndexTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.DeltaSetOuterIndex)
	parseUint16(buf[2:4], &out.DeltaSetInnerIndex)
	parseUint16(buf[4:6], &out.DeltaFormat)
	_ = buf
	_ = origBuf
	return dynSize
}

