// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type CvtTable struct {
	values Slice[int16]
}
func ParseCvtTable(buf []byte, out *CvtTable) int {
	*out = CvtTable{}
	origBuf := buf
	var dynSize int

	{
		out.values = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *CvtTable) Value(i int) int16 {
	var out int16
	parseInt16(tbl.values[i*2:(i+1)*2:len(tbl.values)], &out)
	return out
}

func (tbl *CvtTable) Values() iter.Seq2[int, int16] {
	return func(yield func(int, int16) bool) {
		for i := range tbl.NumValues() {
			if !yield(i, tbl.Value(i)) {
				return
			}
		}
	}
}

func (tbl *CvtTable) NumValues() int {
	return len(tbl.values) / 2
}

