// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type DSIGTable struct {
	data []byte

	Version uint32

	Flags            uint16
	signatureRecords Slice[SignatureRecord]
}

type SignatureRecord struct {
	parentData []byte

	Format        uint32
	Length        uint32
	format1Offset Offset32[SignatureBlockFormat1]
}

type SignatureBlockFormat1 struct {
	signatureLength uint32
	Signature       []byte
}
func ParseDSIGTable(buf []byte, out *DSIGTable) int {
	*out = DSIGTable{}
	origBuf := buf
	var dynSize int
	var numSignatures uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.Version)
	parseUint16(buf[4:6], &numSignatures)
	parseUint16(buf[6:8], &out.Flags)
	{
		n := int(out.Flags)
		/* FIXME: check that buf is long enough */
		out.signatureRecords = buf[8 : 8+n*12]
		dynSize += n * 12
		buf = buf[8+n*12:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *DSIGTable) SignatureRecord(i int) SignatureRecord {
	var out SignatureRecord
	parseSignatureRecord(tbl.signatureRecords[i*12:(i+1)*12:len(tbl.signatureRecords)], tbl.data, &out)
	return out
}

func (tbl *DSIGTable) SignatureRecords() iter.Seq2[int, SignatureRecord] {
	return func(yield func(int, SignatureRecord) bool) {
		for i := range int(tbl.Flags) {
			if !yield(i, tbl.SignatureRecord(i)) {
				return
			}
		}
	}
}

func parseSignatureBlockFormat1(buf []byte, out *SignatureBlockFormat1) int {
	*out = SignatureBlockFormat1{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint32(buf[4:8], &out.signatureLength)
	{
		n := int(out.signatureLength)
		/* FIXME: check that buf is long enough */
		out.Signature = buf[8 : 8+n*1]
		dynSize += n * 1
		buf = buf[8+n*1:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func parseSignatureRecord(buf, parentBuf []byte, out *SignatureRecord) int {
	*out = SignatureRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.Format)
	parseUint32(buf[4:8], &out.Length)

	switch out.Format {
	case 1:
		parseOffset32(buf[8:12], &out.format1Offset)
	}
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *SignatureRecord) Format1(into *SignatureBlockFormat1) bool {
	// FIXME: check bounds
	if tbl.format1Offset == 0 {
		return false
	}
	parseSignatureBlockFormat1(tbl.parentData[tbl.format1Offset:], into)
	return true
}


