// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type EBLCTable struct {
	data []byte

	MajorVersion uint16
	MinorVersion uint16

	bitmapSizes Slice[BitmapSizeRecord]
}

type BitmapSizeRecord struct {
	parentData []byte

	Hori            SbitLineMetricsRecord
	Vert            SbitLineMetricsRecord
	StartGlyphIndex uint16
	EndGlyphIndex   uint16
	PpemX           uint8
	PpemY           uint8
	BitDepth        uint8
	Flags           int8

	// XXX IndexSubtableRecord has offsets relative to indexSubtableListOffset, so we need
	// to set its parentData to this.parentData[indexSubtableListOffset:]
	indexSubtableRecords Slice[IndexSubtableRecord]
}

type SbitLineMetricsRecord struct {
	Ascender              int8
	Descender             int8
	WidthMax              uint8
	CaretSlopeNumerator   int8
	CaretSlopeDenominator int8
	CaretOffset           int8
	MinOriginSB           int8
	MinAdvanceSB          int8
	MaxBeforeBL           int8
	MinAfterBL            int8
}

type IndexSubtableRecord struct {
	parentData []byte

	FirstGlyphIndex     uint16
	LastGlyphIndex      uint16
	indexSubtableOffset Offset32[IndexSubtable]
}

type IndexSubtable struct {
	IndexFormat     uint16
	ImageFormat     uint16
	ImageDataOffset uint32

	Format1 IndexSubtableFormat1
	Format2 IndexSubtableFormat2
	Format3 IndexSubtableFormat3
	Format4 IndexSubtableFormat4
	Format5 IndexSubtableFormat5
}

type IndexSubtableFormat1 struct {
	sbitOffsets Slice[uint32]
}

type IndexSubtableFormat2 struct {
	ImageSize  uint32
	BigMetrics BigGlyphMetricsRecord
}

type IndexSubtableFormat3 struct {
	sbitOffsets Slice[uint16]
}

type IndexSubtableFormat4 struct {
	glyphs Slice[GlyphIDOffsetPairRecord]
}

type GlyphIDOffsetPairRecord struct {
	GlyphID    uint16
	SbitOffset uint16
}

type IndexSubtableFormat5 struct {
	ImageSize  uint32
	BigMetrics BigGlyphMetricsRecord

	glyphIDs Slice[uint16]
}

type BigGlyphMetricsRecord struct {
	Height       uint8
	Width        uint8
	HoribearingX int8
	HoriBearingY int8
	HoriAdvance  uint8
	VertBearingX int8
	VertBearingY int8
	VertAdvance  uint8
}
func parseBigGlyphMetricsRecord(buf []byte, out *BigGlyphMetricsRecord) int {
	*out = BigGlyphMetricsRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	out.Height = buf[0:1][0]
	out.Width = buf[1:2][0]
	out.HoribearingX = int8(buf[2:3][0])
	out.HoriBearingY = int8(buf[3:4][0])
	out.HoriAdvance = buf[4:5][0]
	out.VertBearingX = int8(buf[5:6][0])
	out.VertBearingY = int8(buf[6:7][0])
	out.VertAdvance = buf[7:8][0]
	_ = buf
	_ = origBuf
	return dynSize
}

func parseBitmapSizeRecord(buf, parentBuf []byte, out *BitmapSizeRecord) int {
	*out = BitmapSizeRecord{}
	origBuf := buf
	var dynSize int
	var indexSubtableListOffset uint32
	var indexSubtableListSize uint32
	var numberOfIndexSubtables uint32
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 48 {
		return dynSize
	}
	parseUint32(buf[0:4], &indexSubtableListOffset)
	parseUint32(buf[4:8], &indexSubtableListSize)
	parseUint32(buf[8:12], &numberOfIndexSubtables)
	parseSbitLineMetricsRecord(buf[16:28], &out.Hori)
	parseSbitLineMetricsRecord(buf[28:40], &out.Vert)
	parseUint16(buf[40:42], &out.StartGlyphIndex)
	parseUint16(buf[42:44], &out.EndGlyphIndex)
	out.PpemX = buf[44:45][0]
	out.PpemY = buf[45:46][0]
	out.BitDepth = buf[46:47][0]
	out.Flags = int8(buf[47:48][0])
	{
		n := int(numberOfIndexSubtables)
		start := int(indexSubtableListOffset)
		/* FIXME: check that buf is long enough */
		out.indexSubtableRecords = parentBuf[start : start+n*8]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *BitmapSizeRecord) IndexSubtableRecord(i int) IndexSubtableRecord {
	var out IndexSubtableRecord
	parseIndexSubtableRecord(tbl.indexSubtableRecords[i*8:(i+1)*8:len(tbl.indexSubtableRecords)], tbl.parentData, &out)
	return out
}

func (tbl *BitmapSizeRecord) IndexSubtableRecords() iter.Seq2[int, IndexSubtableRecord] {
	return func(yield func(int, IndexSubtableRecord) bool) {
		for i := range tbl.NumIndexSubtableRecords() {
			if !yield(i, tbl.IndexSubtableRecord(i)) {
				return
			}
		}
	}
}

func (tbl *BitmapSizeRecord) NumIndexSubtableRecords() int {
	return len(tbl.indexSubtableRecords) / 8
}

func ParseEBLCTable(buf []byte, out *EBLCTable) int {
	*out = EBLCTable{}
	origBuf := buf
	var dynSize int
	var numSizes uint32
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 2 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseUint32(buf[4:8], &numSizes)
	{
		n := int(numSizes)
		/* FIXME: check that buf is long enough */
		out.bitmapSizes = buf[8 : 8+n*48]
		dynSize += n * 48
		buf = buf[8+n*48:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *EBLCTable) BitmapSize(i int) BitmapSizeRecord {
	var out BitmapSizeRecord
	parseBitmapSizeRecord(tbl.bitmapSizes[i*48:(i+1)*48:len(tbl.bitmapSizes)], tbl.data, &out)
	return out
}

func (tbl *EBLCTable) BitmapSizes() iter.Seq2[int, BitmapSizeRecord] {
	return func(yield func(int, BitmapSizeRecord) bool) {
		for i := range tbl.NumBitmapSizes() {
			if !yield(i, tbl.BitmapSize(i)) {
				return
			}
		}
	}
}

func (tbl *EBLCTable) NumBitmapSizes() int {
	return len(tbl.bitmapSizes) / 48
}

func parseGlyphIDOffsetPairRecord(buf []byte, out *GlyphIDOffsetPairRecord) int {
	*out = GlyphIDOffsetPairRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.GlyphID)
	parseUint16(buf[2:4], &out.SbitOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseIndexSubtable(buf []byte, out *IndexSubtable) int {
	*out = IndexSubtable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.IndexFormat)
	parseUint16(buf[2:4], &out.ImageFormat)
	parseUint32(buf[4:8], &out.ImageDataOffset)

	switch out.IndexFormat {
	case 1:
		dynSize += parseIndexSubtableFormat1(buf[8:], &out.Format1)
	case 2:
		parseIndexSubtableFormat2(buf[8:20], &out.Format2)
	case 3:
		dynSize += parseIndexSubtableFormat3(buf[8:], &out.Format3)
	case 4:
		dynSize += parseIndexSubtableFormat4(buf[8:], &out.Format4)
	case 5:
		dynSize += parseIndexSubtableFormat5(buf[8:], &out.Format5)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseIndexSubtableFormat1(buf []byte, out *IndexSubtableFormat1) int {
	*out = IndexSubtableFormat1{}
	origBuf := buf
	var dynSize int

	{
		out.sbitOffsets = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *IndexSubtableFormat1) SbitOffset(i int) uint32 {
	var out uint32
	parseUint32(tbl.sbitOffsets[i*4:(i+1)*4:len(tbl.sbitOffsets)], &out)
	return out
}

func (tbl *IndexSubtableFormat1) SbitOffsets() iter.Seq2[int, uint32] {
	return func(yield func(int, uint32) bool) {
		for i := range tbl.NumSbitOffsets() {
			if !yield(i, tbl.SbitOffset(i)) {
				return
			}
		}
	}
}

func (tbl *IndexSubtableFormat1) NumSbitOffsets() int {
	return len(tbl.sbitOffsets) / 4
}

func parseIndexSubtableFormat2(buf []byte, out *IndexSubtableFormat2) int {
	*out = IndexSubtableFormat2{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.ImageSize)
	parseBigGlyphMetricsRecord(buf[4:12], &out.BigMetrics)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseIndexSubtableFormat3(buf []byte, out *IndexSubtableFormat3) int {
	*out = IndexSubtableFormat3{}
	origBuf := buf
	var dynSize int

	{
		out.sbitOffsets = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *IndexSubtableFormat3) SbitOffset(i int) uint16 {
	var out uint16
	parseUint16(tbl.sbitOffsets[i*2:(i+1)*2:len(tbl.sbitOffsets)], &out)
	return out
}

func (tbl *IndexSubtableFormat3) SbitOffsets() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumSbitOffsets() {
			if !yield(i, tbl.SbitOffset(i)) {
				return
			}
		}
	}
}

func (tbl *IndexSubtableFormat3) NumSbitOffsets() int {
	return len(tbl.sbitOffsets) / 2
}

func parseIndexSubtableFormat4(buf []byte, out *IndexSubtableFormat4) int {
	*out = IndexSubtableFormat4{}
	origBuf := buf
	var dynSize int
	var numGlyphs uint32

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint32(buf[0:4], &numGlyphs)
	{
		n := int(numGlyphs + 1)
		/* FIXME: check that buf is long enough */
		out.glyphs = buf[4 : 4+n*4]
		dynSize += n * 4
		buf = buf[4+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *IndexSubtableFormat4) Glyph(i int) GlyphIDOffsetPairRecord {
	var out GlyphIDOffsetPairRecord
	parseGlyphIDOffsetPairRecord(tbl.glyphs[i*4:(i+1)*4:len(tbl.glyphs)], &out)
	return out
}

func (tbl *IndexSubtableFormat4) Glyphs() iter.Seq2[int, GlyphIDOffsetPairRecord] {
	return func(yield func(int, GlyphIDOffsetPairRecord) bool) {
		for i := range tbl.NumGlyphs() {
			if !yield(i, tbl.Glyph(i)) {
				return
			}
		}
	}
}

func (tbl *IndexSubtableFormat4) NumGlyphs() int {
	return len(tbl.glyphs) / 4
}

func parseIndexSubtableFormat5(buf []byte, out *IndexSubtableFormat5) int {
	*out = IndexSubtableFormat5{}
	origBuf := buf
	var dynSize int
	var numGlyphs uint32

	/* FIXME return error */
	if len(buf) < 16 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.ImageSize)
	parseBigGlyphMetricsRecord(buf[4:12], &out.BigMetrics)
	parseUint32(buf[12:16], &numGlyphs)
	{
		n := int(numGlyphs)
		/* FIXME: check that buf is long enough */
		out.glyphIDs = buf[16 : 16+n*2]
		dynSize += n * 2
		buf = buf[16+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *IndexSubtableFormat5) GlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.glyphIDs[i*2:(i+1)*2:len(tbl.glyphIDs)], &out)
	return out
}

func (tbl *IndexSubtableFormat5) GlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumGlyphIDs() {
			if !yield(i, tbl.GlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *IndexSubtableFormat5) NumGlyphIDs() int {
	return len(tbl.glyphIDs) / 2
}

func parseIndexSubtableRecord(buf, parentBuf []byte, out *IndexSubtableRecord) int {
	*out = IndexSubtableRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.FirstGlyphIndex)
	parseUint16(buf[2:4], &out.LastGlyphIndex)
	parseOffset32(buf[4:8], &out.indexSubtableOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *IndexSubtableRecord) IndexSubtable(into *IndexSubtable) bool {
	// FIXME: check bounds
	if tbl.indexSubtableOffset == 0 {
		return false
	}
	parseIndexSubtable(tbl.parentData[tbl.indexSubtableOffset:], into)
	return true
}

func parseSbitLineMetricsRecord(buf []byte, out *SbitLineMetricsRecord) int {
	*out = SbitLineMetricsRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	out.Ascender = int8(buf[0:1][0])
	out.Descender = int8(buf[1:2][0])
	out.WidthMax = buf[2:3][0]
	out.CaretSlopeNumerator = int8(buf[3:4][0])
	out.CaretSlopeDenominator = int8(buf[4:5][0])
	out.CaretOffset = int8(buf[5:6][0])
	out.MinOriginSB = int8(buf[6:7][0])
	out.MinAdvanceSB = int8(buf[7:8][0])
	out.MaxBeforeBL = int8(buf[8:9][0])
	out.MinAfterBL = int8(buf[9:10][0])
	_ = buf
	_ = origBuf
	return dynSize
}

