// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "time"

type FFTMTable struct {
	Version          uint32
	Fontforge        time.Time
	FontCreation     time.Time
	FontModification time.Time
}
func ParseFFTMTable(buf []byte, out *FFTMTable) int {
	*out = FFTMTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 28 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.Version)
	parseTime(buf[4:12], &out.Fontforge)
	parseTime(buf[12:20], &out.FontCreation)
	parseTime(buf[20:28], &out.FontModification)
	_ = buf
	_ = origBuf
	return dynSize
}

