// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type FpgmTable struct {
	Instructions []uint8
}
func ParseFpgmTable(buf []byte, out *FpgmTable) int {
	*out = FpgmTable{}
	origBuf := buf
	var dynSize int

	{
		out.Instructions = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

