// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type FvarTable struct {
	MajorVersion uint16
	MinorVersion uint16

	axisSize uint16

	instanceSize uint16

	axes Slice[VariationAxisRecord]

	// XXX parse instances
	// instances Slice[InstanceRecord]      `gen:"slice(offset=int(axesArrayOffset)+len(out.axes), count=instanceCount, size=instanceSize)"`
}

type VariationAxisRecord struct {
	Tag          Tag
	MinValue     Int16_16
	DefaultValue Int16_16
	MaxValue     Int16_16
	Flags        uint16
	NameID       NameID
}

// type InstanceRecord struct {
// 	Subfamily   NameID
// 	Flags       uint16
// 	Coordinates UserTuple

// 	_          sizeDelimiter
// 	PostScript NameID
// }

// type UserTuple struct {
// 	// XXX axisCount from FvarTable
// 	coordinates Slice[Int16_16] `gen:"slice(count=axisCount)"`
// }
func ParseFvarTable(buf []byte, out *FvarTable) int {
	*out = FvarTable{}
	origBuf := buf
	var dynSize int
	var axesArrayOffset uint16
	var axisCount uint16
	var instanceCount uint16

	/* FIXME return error */
	if len(buf) < 16 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseUint16(buf[4:6], &axesArrayOffset)
	parseUint16(buf[8:10], &axisCount)
	parseUint16(buf[10:12], &out.axisSize)
	parseUint16(buf[12:14], &instanceCount)
	parseUint16(buf[14:16], &out.instanceSize)
	{
		sz := int(out.axisSize)
		n := int(axisCount)
		start := int(axesArrayOffset)
		/* FIXME: check that buf is long enough */
		out.axes = origBuf[start : start+n*sz]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *FvarTable) Axis(i int) VariationAxisRecord {
	sz := int(tbl.axisSize)
	var out VariationAxisRecord
	parseVariationAxisRecord(tbl.axes[i*sz:(i+1)*sz:len(tbl.axes)], &out)
	return out
}

func (tbl *FvarTable) Axes() iter.Seq2[int, VariationAxisRecord] {
	return func(yield func(int, VariationAxisRecord) bool) {
		for i := range tbl.NumAxes() {
			if !yield(i, tbl.Axis(i)) {
				return
			}
		}
	}
}

func (tbl *FvarTable) NumAxes() int {
	return len(tbl.axes) / int(tbl.axisSize)
}

func parseVariationAxisRecord(buf []byte, out *VariationAxisRecord) int {
	*out = VariationAxisRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 20 {
		return dynSize
	}
	parseTag(buf[0:4], &out.Tag)
	parseInt16_16(buf[4:8], &out.MinValue)
	parseInt16_16(buf[8:12], &out.DefaultValue)
	parseInt16_16(buf[12:16], &out.MaxValue)
	parseUint16(buf[16:18], &out.Flags)
	parseNameID(buf[18:20], &out.NameID)
	_ = buf
	_ = origBuf
	return dynSize
}

