// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

const (
	GlyphClassBase      = 1
	GlyphClassLigature  = 2
	GlyphClassMark      = 3
	GlyphClassComponent = 4
)

type GDEFTable struct {
	data []byte

	MajorVersion             uint16
	MinorVersion             uint16
	glyphClassDefOffset      Offset16[ClassDefTable]
	attachListOffset         Offset16[AttachListTable]
	ligCaretListOffset       Offset16[LigCaretListTable]
	markAttachClassDefOffset Offset16[ClassDefTable]

	markGlyphSetDefOffset Offset16[MarkGlyphSetsTable]

	itemVarStoreOffset Offset32[ItemVariationStoreTable]
}

type AttachListTable struct {
	data []byte

	coverageOffset Offset16[CoverageTable]

	attachPointOffsets Slice[Offset16[AttachPointTable]]
}

type AttachPointTable struct {
	pointIndices Slice[uint16]
}

type LigCaretListTable struct {
	data []byte

	coverageOffset Offset16[CoverageTable]

	ligGlyphOffsets Slice[Offset16[LigGlyphTable]]
}

type LigGlyphTable struct {
	data []byte

	caretValueOffsets Slice[Offset16[CaretValueTable]]
}

type CaretValueTable struct {
	data []byte

	CaretValueFormat uint16
	Format1          CaretValueTableFormat1
	Format2          CaretValueTableFormat2
	Format3          CaretValueTableFormat3
}

type CaretValueTableFormat1 struct {
	Coordinate int16
}

type CaretValueTableFormat2 struct {
	CaretValuePointIndex uint16
}

type CaretValueTableFormat3 struct {
	parentData []byte

	Coordinate int16
	// Offset to Device table for non-variable fonts or to variation index table for
	// variable fonts.
	DeviceOffset Offset16[any]
}

type MarkGlyphSetsTable struct {
	data []byte

	Format  uint16
	Format1 MarkGlyphSetsTableFormat1
}

type MarkGlyphSetsTableFormat1 struct {
	parentData []byte

	coverageOffsets Slice[Offset32[CoverageTable]]
}
func ParseAttachListTable(buf []byte, out *AttachListTable) int {
	*out = AttachListTable{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &glyphCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.attachPointOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *AttachListTable) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.data[tbl.coverageOffset:], into)
	return true
}

func (tbl *AttachListTable) NumAttachPointOffsets() int {
	return len(tbl.attachPointOffsets) / 2
}

func ParseAttachPointTable(buf []byte, out *AttachPointTable) int {
	*out = AttachPointTable{}
	origBuf := buf
	var dynSize int
	var pointCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &pointCount)
	{
		n := int(pointCount)
		/* FIXME: check that buf is long enough */
		out.pointIndices = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *AttachPointTable) PointIndice(i int) uint16 {
	var out uint16
	parseUint16(tbl.pointIndices[i*2:(i+1)*2:len(tbl.pointIndices)], &out)
	return out
}

func (tbl *AttachPointTable) PointIndices() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumPointIndices() {
			if !yield(i, tbl.PointIndice(i)) {
				return
			}
		}
	}
}

func (tbl *AttachPointTable) NumPointIndices() int {
	return len(tbl.pointIndices) / 2
}

func ParseCaretValueTable(buf []byte, out *CaretValueTable) int {
	*out = CaretValueTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.CaretValueFormat)

	switch out.CaretValueFormat {
	case 1:
		parseCaretValueTableFormat1(buf[2:4], &out.Format1)
	case 2:
		parseCaretValueTableFormat2(buf[2:4], &out.Format2)
	case 3:
		parseCaretValueTableFormat3(buf[2:6], buf, &out.Format3)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseCaretValueTableFormat1(buf []byte, out *CaretValueTableFormat1) int {
	*out = CaretValueTableFormat1{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.Coordinate)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseCaretValueTableFormat2(buf []byte, out *CaretValueTableFormat2) int {
	*out = CaretValueTableFormat2{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.CaretValuePointIndex)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseCaretValueTableFormat3(buf, parentBuf []byte, out *CaretValueTableFormat3) int {
	*out = CaretValueTableFormat3{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.Coordinate)
	parseOffset16(buf[2:4], &out.DeviceOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseGDEFTable(buf []byte, out *GDEFTable) int {
	*out = GDEFTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseOffset16(buf[4:6], &out.glyphClassDefOffset)
	parseOffset16(buf[6:8], &out.attachListOffset)
	parseOffset16(buf[8:10], &out.ligCaretListOffset)
	parseOffset16(buf[10:12], &out.markAttachClassDefOffset)

	if out.MajorVersion < 1 {
		return dynSize
	}
	if out.MajorVersion == 1 && out.MinorVersion < 2 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 14 {
		return dynSize
	}
	parseOffset16(buf[12:14], &out.markGlyphSetDefOffset)

	if out.MajorVersion < 1 {
		return dynSize
	}
	if out.MajorVersion == 1 && out.MinorVersion < 3 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 18 {
		return dynSize
	}
	parseOffset32(buf[14:18], &out.itemVarStoreOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *GDEFTable) GlyphClassDef(into *ClassDefTable) bool {
	// FIXME: check bounds
	if tbl.glyphClassDefOffset == 0 {
		return false
	}
	ParseClassDefTable(tbl.data[tbl.glyphClassDefOffset:], into)
	return true
}

func (tbl *GDEFTable) AttachList(into *AttachListTable) bool {
	// FIXME: check bounds
	if tbl.attachListOffset == 0 {
		return false
	}
	ParseAttachListTable(tbl.data[tbl.attachListOffset:], into)
	return true
}

func (tbl *GDEFTable) LigCaretList(into *LigCaretListTable) bool {
	// FIXME: check bounds
	if tbl.ligCaretListOffset == 0 {
		return false
	}
	ParseLigCaretListTable(tbl.data[tbl.ligCaretListOffset:], into)
	return true
}

func (tbl *GDEFTable) MarkAttachClassDef(into *ClassDefTable) bool {
	// FIXME: check bounds
	if tbl.markAttachClassDefOffset == 0 {
		return false
	}
	ParseClassDefTable(tbl.data[tbl.markAttachClassDefOffset:], into)
	return true
}

func (tbl *GDEFTable) MarkGlyphSetDef(into *MarkGlyphSetsTable) bool {
	// FIXME: check bounds
	if tbl.markGlyphSetDefOffset == 0 {
		return false
	}
	ParseMarkGlyphSetsTable(tbl.data[tbl.markGlyphSetDefOffset:], into)
	return true
}

func (tbl *GDEFTable) ItemVarStore(into *ItemVariationStoreTable) bool {
	// FIXME: check bounds
	if tbl.itemVarStoreOffset == 0 {
		return false
	}
	ParseItemVariationStoreTable(tbl.data[tbl.itemVarStoreOffset:], into)
	return true
}

func ParseLigCaretListTable(buf []byte, out *LigCaretListTable) int {
	*out = LigCaretListTable{}
	origBuf := buf
	var dynSize int
	var ligGlyphCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &ligGlyphCount)
	{
		n := int(ligGlyphCount)
		/* FIXME: check that buf is long enough */
		out.ligGlyphOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *LigCaretListTable) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.data[tbl.coverageOffset:], into)
	return true
}

func (tbl *LigCaretListTable) NumLigGlyphOffsets() int {
	return len(tbl.ligGlyphOffsets) / 2
}

func ParseLigGlyphTable(buf []byte, out *LigGlyphTable) int {
	*out = LigGlyphTable{}
	origBuf := buf
	var dynSize int
	var caretCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &caretCount)
	{
		n := int(caretCount)
		/* FIXME: check that buf is long enough */
		out.caretValueOffsets = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LigGlyphTable) NumCaretValueOffsets() int {
	return len(tbl.caretValueOffsets) / 2
}

func ParseMarkGlyphSetsTable(buf []byte, out *MarkGlyphSetsTable) int {
	*out = MarkGlyphSetsTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 1:
		dynSize += parseMarkGlyphSetsTableFormat1(buf[2:], buf, &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseMarkGlyphSetsTableFormat1(buf, parentBuf []byte, out *MarkGlyphSetsTableFormat1) int {
	*out = MarkGlyphSetsTableFormat1{}
	origBuf := buf
	var dynSize int
	var markGlyphSetCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &markGlyphSetCount)
	{
		n := int(markGlyphSetCount)
		/* FIXME: check that buf is long enough */
		out.coverageOffsets = buf[2 : 2+n*4]
		dynSize += n * 4
		buf = buf[2+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *MarkGlyphSetsTableFormat1) NumCoverageOffsets() int {
	return len(tbl.coverageOffsets) / 4
}

