// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type GlyfTable struct {
	Data []byte
}

type SimpleGlyphTable struct {
	NumberOfContours int16
	XMin             int16
	YMin             int16
	XMax             int16
	YMax             int16

	endPtsOfContours  Slice[uint16]
	instructionLength uint16
	Instructions      []byte

	// Data contains arrays of flags and X and Y coordinates
	Data []byte
}

type CompositeGlyphTable struct {
	NumberOfContours int16
	XMin             int16
	YMin             int16
	XMax             int16
	YMax             int16

	Flags      uint16
	GlyphIndex uint16
	Data       []byte
}
func ParseCompositeGlyphTable(buf []byte, out *CompositeGlyphTable) int {
	*out = CompositeGlyphTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 14 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.NumberOfContours)
	parseInt16(buf[2:4], &out.XMin)
	parseInt16(buf[4:6], &out.YMin)
	parseInt16(buf[6:8], &out.XMax)
	parseInt16(buf[8:10], &out.YMax)
	parseUint16(buf[10:12], &out.Flags)
	parseUint16(buf[12:14], &out.GlyphIndex)
	{
		out.Data = buf[14:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func ParseGlyfTable(buf []byte, out *GlyfTable) int {
	*out = GlyfTable{}
	origBuf := buf
	var dynSize int

	{
		out.Data = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func ParseSimpleGlyphTable(buf []byte, out *SimpleGlyphTable) int {
	*out = SimpleGlyphTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 10 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.NumberOfContours)
	parseInt16(buf[2:4], &out.XMin)
	parseInt16(buf[4:6], &out.YMin)
	parseInt16(buf[6:8], &out.XMax)
	parseInt16(buf[8:10], &out.YMax)
	{
		n := int(out.NumberOfContours)
		/* FIXME: check that buf is long enough */
		out.endPtsOfContours = buf[10 : 10+n*2]
		dynSize += n * 2
		buf = buf[10+n*2:]
	}

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.instructionLength)
	{
		n := int(out.instructionLength)
		/* FIXME: check that buf is long enough */
		out.Instructions = buf[2 : 2+n*1]
		dynSize += n * 1
		buf = buf[2+n*1:]
	}

	{
		out.Data = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SimpleGlyphTable) EndPtsOfContour(i int) uint16 {
	var out uint16
	parseUint16(tbl.endPtsOfContours[i*2:(i+1)*2:len(tbl.endPtsOfContours)], &out)
	return out
}

func (tbl *SimpleGlyphTable) EndPtsOfContours() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range int(tbl.NumberOfContours) {
			if !yield(i, tbl.EndPtsOfContour(i)) {
				return
			}
		}
	}
}

