// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

const (
	GSUBLookTypeSingle                       = 1
	GSUBLookTypeMultiple                     = 2
	GSUBLookTypeAlternate                    = 3
	GSUBLookTypeLigature                     = 4
	GSUBLookTypeContext                      = 5
	GSUBLookTypeChainingContext              = 6
	GSUBLookTypeExtensionSubstitution        = 7
	GSUBLookTypeReverseChainingContextSingle = 8
)

type GSUBTable struct {
	data []byte

	MajorVersion      uint16
	MinorVersion      uint16
	scriptListOffset  Offset16[ScriptListTable]
	featureListOffset Offset16[FeatureListTable]
	lookupListOffset  Offset16[LookupListTable]

	featureVariationsOffset Offset32[FeatureVariationsTable]
}

type SingleSubstTable struct {
	SubstFormat uint16
	Format1     SingleSubstTableFormat1
	Format2     SingleSubstTableFormat2
}

type SingleSubstTableFormat1 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]
	DeltaGlyphID   uint16
}

type SingleSubstTableFormat2 struct {
	parentData []byte

	coverageOffset     Offset16[CoverageTable]
	glyphCount         uint16
	substituteGlyphIDs Slice[uint16]
}

type MultipleSubstTable struct {
	SubstFormat uint16
	Format1     MultipleSubstTableFormat1
}

type MultipleSubstTableFormat1 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]

	sequenceOffsets Slice[Offset16[SequenceTable]]
}

type SequenceTable struct {
	substituteGlyphIDs Slice[uint16]
}

type AlternateSubstTable struct {
	SubstFormat uint16
	Format1     AlternateSubstTableFormat1
}

type AlternateSubstTableFormat1 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]

	alternateSetOffsets Slice[Offset16[AlternateSetTable]]
}

type AlternateSetTable struct {
	alternateGlyphIDs Slice[uint16]
}

type LigatureSubstTable struct {
	SubstFormat uint16
	Format1     LigatureSubstTableFormat1
}

type LigatureSubstTableFormat1 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]

	ligatureSetOffsets Slice[Offset16[LigatureSetTable]]
}

type LigatureSetTable struct {
	ligatureOffsets Slice[Offset16[LigatureTable]]
}

type LigatureTable struct {
	LigatureGlyph uint16

	componentGlyphIDs Slice[uint16]
}

type ExtensionSubstTable struct {
	SubstFormat uint16
	Format1     ExtensionSubstTableFormat1
}

type ExtensionSubstTableFormat1 struct {
	parentData []byte

	ExtensionLookupType uint16
	ExtensionOffset     Offset32[any]
}

type ReverseChainSingleSubstTable struct {
	SubstFormat uint16
	Format1     ReverseChainSingleSubstTableFormat1
}

type ReverseChainSingleSubstTableFormat1 struct {
	parentData []byte

	coverageOffset Offset16[CoverageTable]

	backtrackCoverageOffsets Slice[Offset16[CoverageTable]]

	lookaheadCoverageOffsets Slice[Offset16[CoverageTable]]

	substituteGlyphIDs Slice[uint16]
}
func ParseAlternateSetTable(buf []byte, out *AlternateSetTable) int {
	*out = AlternateSetTable{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.alternateGlyphIDs = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *AlternateSetTable) AlternateGlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.alternateGlyphIDs[i*2:(i+1)*2:len(tbl.alternateGlyphIDs)], &out)
	return out
}

func (tbl *AlternateSetTable) AlternateGlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumAlternateGlyphIDs() {
			if !yield(i, tbl.AlternateGlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *AlternateSetTable) NumAlternateGlyphIDs() int {
	return len(tbl.alternateGlyphIDs) / 2
}

func ParseAlternateSubstTable(buf []byte, out *AlternateSubstTable) int {
	*out = AlternateSubstTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SubstFormat)

	switch out.SubstFormat {
	case 1:
		dynSize += parseAlternateSubstTableFormat1(buf[2:], buf, &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseAlternateSubstTableFormat1(buf, parentBuf []byte, out *AlternateSubstTableFormat1) int {
	*out = AlternateSubstTableFormat1{}
	origBuf := buf
	var dynSize int
	var alternateSetCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &alternateSetCount)
	{
		n := int(alternateSetCount)
		/* FIXME: check that buf is long enough */
		out.alternateSetOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *AlternateSubstTableFormat1) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *AlternateSubstTableFormat1) NumAlternateSetOffsets() int {
	return len(tbl.alternateSetOffsets) / 2
}

func ParseExtensionSubstTable(buf []byte, out *ExtensionSubstTable) int {
	*out = ExtensionSubstTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SubstFormat)

	switch out.SubstFormat {
	case 1:
		parseExtensionSubstTableFormat1(buf[2:8], buf, &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseExtensionSubstTableFormat1(buf, parentBuf []byte, out *ExtensionSubstTableFormat1) int {
	*out = ExtensionSubstTableFormat1{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.ExtensionLookupType)
	parseOffset32(buf[2:6], &out.ExtensionOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseGSUBTable(buf []byte, out *GSUBTable) int {
	*out = GSUBTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 10 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseOffset16(buf[4:6], &out.scriptListOffset)
	parseOffset16(buf[6:8], &out.featureListOffset)
	parseOffset16(buf[8:10], &out.lookupListOffset)

	if out.MajorVersion < 1 {
		return dynSize
	}
	if out.MajorVersion == 1 && out.MinorVersion < 1 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 14 {
		return dynSize
	}
	parseOffset32(buf[10:14], &out.featureVariationsOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *GSUBTable) ScriptList(into *ScriptListTable) bool {
	// FIXME: check bounds
	if tbl.scriptListOffset == 0 {
		return false
	}
	ParseScriptListTable(tbl.data[tbl.scriptListOffset:], into)
	return true
}

func (tbl *GSUBTable) FeatureList(into *FeatureListTable) bool {
	// FIXME: check bounds
	if tbl.featureListOffset == 0 {
		return false
	}
	ParseFeatureListTable(tbl.data[tbl.featureListOffset:], into)
	return true
}

func (tbl *GSUBTable) LookupList(into *LookupListTable) bool {
	// FIXME: check bounds
	if tbl.lookupListOffset == 0 {
		return false
	}
	ParseLookupListTable(tbl.data[tbl.lookupListOffset:], into)
	return true
}

func (tbl *GSUBTable) FeatureVariations(into *FeatureVariationsTable) bool {
	// FIXME: check bounds
	if tbl.featureVariationsOffset == 0 {
		return false
	}
	ParseFeatureVariationsTable(tbl.data[tbl.featureVariationsOffset:], into)
	return true
}

func ParseLigatureSetTable(buf []byte, out *LigatureSetTable) int {
	*out = LigatureSetTable{}
	origBuf := buf
	var dynSize int
	var ligatureCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &ligatureCount)
	{
		n := int(ligatureCount)
		/* FIXME: check that buf is long enough */
		out.ligatureOffsets = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LigatureSetTable) NumLigatureOffsets() int {
	return len(tbl.ligatureOffsets) / 2
}

func ParseLigatureSubstTable(buf []byte, out *LigatureSubstTable) int {
	*out = LigatureSubstTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SubstFormat)

	switch out.SubstFormat {
	case 1:
		dynSize += parseLigatureSubstTableFormat1(buf[2:], buf, &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseLigatureSubstTableFormat1(buf, parentBuf []byte, out *LigatureSubstTableFormat1) int {
	*out = LigatureSubstTableFormat1{}
	origBuf := buf
	var dynSize int
	var ligatureSetCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &ligatureSetCount)
	{
		n := int(ligatureSetCount)
		/* FIXME: check that buf is long enough */
		out.ligatureSetOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *LigatureSubstTableFormat1) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *LigatureSubstTableFormat1) NumLigatureSetOffsets() int {
	return len(tbl.ligatureSetOffsets) / 2
}

func ParseLigatureTable(buf []byte, out *LigatureTable) int {
	*out = LigatureTable{}
	origBuf := buf
	var dynSize int
	var componentCount uint16

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.LigatureGlyph)
	parseUint16(buf[2:4], &componentCount)
	{
		n := int(componentCount)
		/* FIXME: check that buf is long enough */
		out.componentGlyphIDs = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LigatureTable) ComponentGlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.componentGlyphIDs[i*2:(i+1)*2:len(tbl.componentGlyphIDs)], &out)
	return out
}

func (tbl *LigatureTable) ComponentGlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumComponentGlyphIDs() {
			if !yield(i, tbl.ComponentGlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *LigatureTable) NumComponentGlyphIDs() int {
	return len(tbl.componentGlyphIDs) / 2
}

func ParseMultipleSubstTable(buf []byte, out *MultipleSubstTable) int {
	*out = MultipleSubstTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SubstFormat)

	switch out.SubstFormat {
	case 1:
		dynSize += parseMultipleSubstTableFormat1(buf[2:], buf, &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseMultipleSubstTableFormat1(buf, parentBuf []byte, out *MultipleSubstTableFormat1) int {
	*out = MultipleSubstTableFormat1{}
	origBuf := buf
	var dynSize int
	var sequenceCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &sequenceCount)
	{
		n := int(sequenceCount)
		/* FIXME: check that buf is long enough */
		out.sequenceOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *MultipleSubstTableFormat1) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *MultipleSubstTableFormat1) NumSequenceOffsets() int {
	return len(tbl.sequenceOffsets) / 2
}

func ParseReverseChainSingleSubstTable(buf []byte, out *ReverseChainSingleSubstTable) int {
	*out = ReverseChainSingleSubstTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SubstFormat)

	switch out.SubstFormat {
	case 1:
		dynSize += parseReverseChainSingleSubstTableFormat1(buf[2:], buf, &out.Format1)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseReverseChainSingleSubstTableFormat1(buf, parentBuf []byte, out *ReverseChainSingleSubstTableFormat1) int {
	*out = ReverseChainSingleSubstTableFormat1{}
	origBuf := buf
	var dynSize int
	var backtrackGlyphCount uint16
	var lookaheadGlyphCount uint16
	var glyphCount uint16
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &backtrackGlyphCount)
	{
		n := int(backtrackGlyphCount)
		/* FIXME: check that buf is long enough */
		out.backtrackCoverageOffsets = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &lookaheadGlyphCount)
	{
		n := int(lookaheadGlyphCount)
		/* FIXME: check that buf is long enough */
		out.lookaheadCoverageOffsets = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.substituteGlyphIDs = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *ReverseChainSingleSubstTableFormat1) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *ReverseChainSingleSubstTableFormat1) NumBacktrackCoverageOffsets() int {
	return len(tbl.backtrackCoverageOffsets) / 2
}

func (tbl *ReverseChainSingleSubstTableFormat1) NumLookaheadCoverageOffsets() int {
	return len(tbl.lookaheadCoverageOffsets) / 2
}

func (tbl *ReverseChainSingleSubstTableFormat1) SubstituteGlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.substituteGlyphIDs[i*2:(i+1)*2:len(tbl.substituteGlyphIDs)], &out)
	return out
}

func (tbl *ReverseChainSingleSubstTableFormat1) SubstituteGlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumSubstituteGlyphIDs() {
			if !yield(i, tbl.SubstituteGlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *ReverseChainSingleSubstTableFormat1) NumSubstituteGlyphIDs() int {
	return len(tbl.substituteGlyphIDs) / 2
}

func ParseSequenceTable(buf []byte, out *SequenceTable) int {
	*out = SequenceTable{}
	origBuf := buf
	var dynSize int
	var glyphCount uint16

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &glyphCount)
	{
		n := int(glyphCount)
		/* FIXME: check that buf is long enough */
		out.substituteGlyphIDs = buf[2 : 2+n*2]
		dynSize += n * 2
		buf = buf[2+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SequenceTable) SubstituteGlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.substituteGlyphIDs[i*2:(i+1)*2:len(tbl.substituteGlyphIDs)], &out)
	return out
}

func (tbl *SequenceTable) SubstituteGlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumSubstituteGlyphIDs() {
			if !yield(i, tbl.SubstituteGlyphID(i)) {
				return
			}
		}
	}
}

func (tbl *SequenceTable) NumSubstituteGlyphIDs() int {
	return len(tbl.substituteGlyphIDs) / 2
}

func ParseSingleSubstTable(buf []byte, out *SingleSubstTable) int {
	*out = SingleSubstTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.SubstFormat)

	switch out.SubstFormat {
	case 1:
		parseSingleSubstTableFormat1(buf[2:6], buf, &out.Format1)
	case 2:
		dynSize += parseSingleSubstTableFormat2(buf[2:], buf, &out.Format2)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseSingleSubstTableFormat1(buf, parentBuf []byte, out *SingleSubstTableFormat1) int {
	*out = SingleSubstTableFormat1{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &out.DeltaGlyphID)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *SingleSubstTableFormat1) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func parseSingleSubstTableFormat2(buf, parentBuf []byte, out *SingleSubstTableFormat2) int {
	*out = SingleSubstTableFormat2{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseOffset16(buf[0:2], &out.coverageOffset)
	parseUint16(buf[2:4], &out.glyphCount)
	{
		n := int(out.glyphCount)
		/* FIXME: check that buf is long enough */
		out.substituteGlyphIDs = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *SingleSubstTableFormat2) Coverage(into *CoverageTable) bool {
	// FIXME: check bounds
	if tbl.coverageOffset == 0 {
		return false
	}
	ParseCoverageTable(tbl.parentData[tbl.coverageOffset:], into)
	return true
}

func (tbl *SingleSubstTableFormat2) SubstituteGlyphID(i int) uint16 {
	var out uint16
	parseUint16(tbl.substituteGlyphIDs[i*2:(i+1)*2:len(tbl.substituteGlyphIDs)], &out)
	return out
}

func (tbl *SingleSubstTableFormat2) SubstituteGlyphIDs() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range int(tbl.glyphCount) {
			if !yield(i, tbl.SubstituteGlyphID(i)) {
				return
			}
		}
	}
}

