// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import (
	"time"
)

type HeadTable struct {
	MajorVersion       uint16
	MinorVersion       uint16
	FontRevision       Int16_16
	ChecksumAdjustment uint32
	MagicNumber        uint32 // has to be 0x5F0F3CF5
	Flags              uint16
	UnitsPerEm         uint16
	Created            time.Time
	Modified           time.Time
	XMin               int16
	YMin               int16
	XMax               int16
	YMax               int16
	MacStyle           uint16
	LowestRecPPEM      uint16
	FontDirectionHint  int16
	IndexToLocFormat   int16
	GlyphDataFormat    int16
}
func ParseHeadTable(buf []byte, out *HeadTable) int {
	*out = HeadTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 54 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseInt16_16(buf[4:8], &out.FontRevision)
	parseUint32(buf[8:12], &out.ChecksumAdjustment)
	parseUint32(buf[12:16], &out.MagicNumber)
	parseUint16(buf[16:18], &out.Flags)
	parseUint16(buf[18:20], &out.UnitsPerEm)
	parseTime(buf[20:28], &out.Created)
	parseTime(buf[28:36], &out.Modified)
	parseInt16(buf[36:38], &out.XMin)
	parseInt16(buf[38:40], &out.YMin)
	parseInt16(buf[40:42], &out.XMax)
	parseInt16(buf[42:44], &out.YMax)
	parseUint16(buf[44:46], &out.MacStyle)
	parseUint16(buf[46:48], &out.LowestRecPPEM)
	parseInt16(buf[48:50], &out.FontDirectionHint)
	parseInt16(buf[50:52], &out.IndexToLocFormat)
	parseInt16(buf[52:54], &out.GlyphDataFormat)
	_ = buf
	_ = origBuf
	return dynSize
}

