// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

// Apple specifies a backwards-incompatible version 1 of the kern table, which changes the
// size of existing fields. This is contrary to the general rule that versions represented
// as single values are meant to be minor versions, with newer versions being backwards
// compatible. Fonts using the newer format are only compatible with macOS, not Windows
// (but Harfbuzz supports it).
//
// Apple furthermore specifies two new subtable formats, at least one of which has more
// peculiarities, such as having an offset field that is reinterpreted as something else
// whenever its value is not the "expected" offset.
//
// But Apple _also_ introduced the kerx table, which is similar to their incompatible kern
// extension, but cleaned up and with fewer special cases. Because of that, we support the
// kerx table, but only version 0 of the kern table. Well-behaving cross-platform fonts
// won't be using version 1 kern tables, and modern Apple-specific fonts will use kerx
// tables. We do not care about supporting old Apple-specific fonts that use version 1
// kern tables.

type KernTable struct {
	Version   uint16
	NumTables uint16
	subtables []byte
}

type KernSubTable struct {
	Version  uint16
	Length   uint16
	Coverage uint16

	Format0 KernSubtableFormat0
	Format2 KernSubtableFormat2
}

type KernSubtableFormat0 struct {
	nPairs uint16

	pairs Slice[KerningPair]
}

type KerningPair struct {
	Left  uint16
	Right uint16
	Value int16
}

type KernSubtableFormat2 struct {
	data []byte

	RowWidth           uint16
	LeftClassOffset    Offset16[KerningClassTable]
	RightClassOffset   Offset16[KerningClassTable]
	kerningArrayOffset uint16
}

type KerningClassTable struct {
	FirstGlyph uint16
	nGlyphs    uint16
	classes    Slice[uint16]
}
func ParseKernSubTable(buf []byte, out *KernSubTable) int {
	*out = KernSubTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseUint16(buf[2:4], &out.Length)
	parseUint16(buf[4:6], &out.Coverage)

	switch out.Format() {
	case 0:
		dynSize += parseKernSubtableFormat0(buf[6:], &out.Format0)
	case 2:
		parseKernSubtableFormat2(buf[6:14], &out.Format2)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseKernSubtableFormat0(buf []byte, out *KernSubtableFormat0) int {
	*out = KernSubtableFormat0{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.nPairs)
	{
		n := int(out.nPairs)
		/* FIXME: check that buf is long enough */
		out.pairs = buf[8 : 8+n*6]
		dynSize += n * 6
		buf = buf[8+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *KernSubtableFormat0) Pair(i int) KerningPair {
	var out KerningPair
	parseKerningPair(tbl.pairs[i*6:(i+1)*6:len(tbl.pairs)], &out)
	return out
}

func (tbl *KernSubtableFormat0) Pairs() iter.Seq2[int, KerningPair] {
	return func(yield func(int, KerningPair) bool) {
		for i := range int(tbl.nPairs) {
			if !yield(i, tbl.Pair(i)) {
				return
			}
		}
	}
}

func parseKernSubtableFormat2(buf []byte, out *KernSubtableFormat2) int {
	*out = KernSubtableFormat2{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.RowWidth)
	parseOffset16(buf[2:4], &out.LeftClassOffset)
	parseOffset16(buf[4:6], &out.RightClassOffset)
	parseUint16(buf[6:8], &out.kerningArrayOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseKernTable(buf []byte, out *KernTable) int {
	*out = KernTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseUint16(buf[2:4], &out.NumTables)
	{
		out.subtables = buf[4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func ParseKerningClassTable(buf []byte, out *KerningClassTable) int {
	*out = KerningClassTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.FirstGlyph)
	parseUint16(buf[2:4], &out.nGlyphs)
	{
		n := int(out.nGlyphs)
		/* FIXME: check that buf is long enough */
		out.classes = buf[4 : 4+n*2]
		dynSize += n * 2
		buf = buf[4+n*2:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *KerningClassTable) class(i int) uint16 {
	var out uint16
	parseUint16(tbl.classes[i*2:(i+1)*2:len(tbl.classes)], &out)
	return out
}

func (tbl *KerningClassTable) Classes() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range int(tbl.nGlyphs) {
			if !yield(i, tbl.class(i)) {
				return
			}
		}
	}
}

func parseKerningPair(buf []byte, out *KerningPair) int {
	*out = KerningPair{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Left)
	parseUint16(buf[2:4], &out.Right)
	parseInt16(buf[4:6], &out.Value)
	_ = buf
	_ = origBuf
	return dynSize
}

