// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type ShortLocaTable struct {
	// Offsets divided by 2 to locations of glyphs, relative to the beginning of the glyf
	// table.
	offsets Slice[uint16]
}

type LongLocaTable struct {
	// Offsets to locations of glyphs, relative to the beginning of the glyf table.
	offsets Slice[uint32]
}
func ParseLongLocaTable(buf []byte, out *LongLocaTable) int {
	*out = LongLocaTable{}
	origBuf := buf
	var dynSize int

	{
		out.offsets = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *LongLocaTable) Offset(i int) uint32 {
	var out uint32
	parseUint32(tbl.offsets[i*4:(i+1)*4:len(tbl.offsets)], &out)
	return out
}

func (tbl *LongLocaTable) Offsets() iter.Seq2[int, uint32] {
	return func(yield func(int, uint32) bool) {
		for i := range tbl.NumOffsets() {
			if !yield(i, tbl.Offset(i)) {
				return
			}
		}
	}
}

func (tbl *LongLocaTable) NumOffsets() int {
	return len(tbl.offsets) / 4
}

func ParseShortLocaTable(buf []byte, out *ShortLocaTable) int {
	*out = ShortLocaTable{}
	origBuf := buf
	var dynSize int

	{
		out.offsets = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ShortLocaTable) Offset(i int) uint16 {
	var out uint16
	parseUint16(tbl.offsets[i*2:(i+1)*2:len(tbl.offsets)], &out)
	return out
}

func (tbl *ShortLocaTable) Offsets() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumOffsets() {
			if !yield(i, tbl.Offset(i)) {
				return
			}
		}
	}
}

func (tbl *ShortLocaTable) NumOffsets() int {
	return len(tbl.offsets) / 2
}

