// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type MaxpTable struct {
	MajorVersion uint16
	MinorVersion uint16

	NumGlyphs uint16

	MaxPoints             uint16
	MaxContours           uint16
	MaxCompositePoints    uint16
	MaxCompositeContours  uint16
	MaxZones              uint16
	MaxTwilightPoints     uint16
	MaxStorage            uint16
	MaxFunctionDefs       uint16
	MaxInstructionDefs    uint16
	MaxStackElements      uint16
	MaxSizeOfInstructions uint16
	MaxComponentElements  uint16
	MaxComponentDepth     uint16
}
func ParseMaxpTable(buf []byte, out *MaxpTable) int {
	*out = MaxpTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseWeirdMinorVersion(buf[2:4], &out.MinorVersion)

	if out.MajorVersion == 0 && out.MinorVersion < 5 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[4:6], &out.NumGlyphs)

	if out.MajorVersion < 1 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 32 {
		return dynSize
	}
	parseUint16(buf[6:8], &out.MaxPoints)
	parseUint16(buf[8:10], &out.MaxContours)
	parseUint16(buf[10:12], &out.MaxCompositePoints)
	parseUint16(buf[12:14], &out.MaxCompositeContours)
	parseUint16(buf[14:16], &out.MaxZones)
	parseUint16(buf[16:18], &out.MaxTwilightPoints)
	parseUint16(buf[18:20], &out.MaxStorage)
	parseUint16(buf[20:22], &out.MaxFunctionDefs)
	parseUint16(buf[22:24], &out.MaxInstructionDefs)
	parseUint16(buf[24:26], &out.MaxStackElements)
	parseUint16(buf[26:28], &out.MaxSizeOfInstructions)
	parseUint16(buf[28:30], &out.MaxComponentElements)
	parseUint16(buf[30:32], &out.MaxComponentDepth)
	_ = buf
	_ = origBuf
	return dynSize
}

