// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type MergeFlag uint8

const (
	MergeLTR               MergeFlag = 1
	GroupLTR               MergeFlag = 2
	SecondIsSubordinateLTR MergeFlag = 4
	MergeRTL               MergeFlag = 16
	GroupRTL               MergeFlag = 32
	SecondIsSubordinateRTL MergeFlag = 64
)

type MERGTable struct {
	Version         uint16
	MergeClassCount uint16

	classDefOffsets Slice[Offset16[ClassDefTable]]
	// Row-major 2D array of merge entries, MergeClassCount² many.
	MergeEntries []MergeFlag
}
func ParseMERGTable(buf []byte, out *MERGTable) int {
	*out = MERGTable{}
	origBuf := buf
	var dynSize int
	var mergeDataOffset uint16
	var classDefCount uint16
	var offsetToClassDefOffsets uint16

	/* FIXME return error */
	if len(buf) < 10 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseUint16(buf[2:4], &out.MergeClassCount)
	parseUint16(buf[4:6], &mergeDataOffset)
	parseUint16(buf[6:8], &classDefCount)
	parseUint16(buf[8:10], &offsetToClassDefOffsets)
	{
		n := int(classDefCount)
		start := int(offsetToClassDefOffsets)
		/* FIXME: check that buf is long enough */
		out.classDefOffsets = origBuf[start : start+n*2]
	}

	{
		n := int(out.MergeClassCount) * int(out.MergeClassCount)
		start := int(mergeDataOffset)
		/* FIXME: check that buf is long enough */
		out.MergeEntries = sliceCast[MergeFlag](origBuf[start : start+n*1])
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *MERGTable) NumClassDefOffsets() int {
	return len(tbl.classDefOffsets) / 2
}

