// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type MetaTable struct {
	data []byte

	Version uint32
	Flags   uint32

	dataMaps Slice[DataMapRecord]
}

type DataMapRecord struct {
	parentData []byte

	Tag Tag

	Data []byte
}
func parseDataMapRecord(buf, parentBuf []byte, out *DataMapRecord) int {
	*out = DataMapRecord{}
	origBuf := buf
	var dynSize int
	var dataOffset uint32
	var dataLength uint32
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseTag(buf[0:4], &out.Tag)
	parseUint32(buf[4:8], &dataOffset)
	parseUint32(buf[8:12], &dataLength)
	{
		n := int(dataLength)
		start := int(dataOffset)
		/* FIXME: check that buf is long enough */
		out.Data = parentBuf[start : start+n*1]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func ParseMetaTable(buf []byte, out *MetaTable) int {
	*out = MetaTable{}
	origBuf := buf
	var dynSize int
	var dataMapsCount uint32
	out.data = buf

	/* FIXME return error */
	if len(buf) < 16 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.Version)
	parseUint32(buf[4:8], &out.Flags)
	parseUint32(buf[12:16], &dataMapsCount)
	{
		n := int(dataMapsCount)
		/* FIXME: check that buf is long enough */
		out.dataMaps = buf[16 : 16+n*12]
		dynSize += n * 12
		buf = buf[16+n*12:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *MetaTable) DataMap(i int) DataMapRecord {
	var out DataMapRecord
	parseDataMapRecord(tbl.dataMaps[i*12:(i+1)*12:len(tbl.dataMaps)], tbl.data, &out)
	return out
}

func (tbl *MetaTable) DataMaps() iter.Seq2[int, DataMapRecord] {
	return func(yield func(int, DataMapRecord) bool) {
		for i := range tbl.NumDataMaps() {
			if !yield(i, tbl.DataMap(i)) {
				return
			}
		}
	}
}

func (tbl *MetaTable) NumDataMaps() int {
	return len(tbl.dataMaps) / 12
}

