// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type MVARTable struct {
}
func ParseMVARTable(buf []byte, out *MVARTable) int {
	*out = MVARTable{}
	origBuf := buf
	var dynSize int

	_ = buf
	_ = origBuf
	return dynSize
}

