// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type NameTable struct {
	Version uint16

	nameRecords Slice[NameRecord]

	Data []byte

	langTagRecords Slice[LangTagRecord]
}

type LangTagRecord struct {
	Length uint16
	// Offset relative to NameTablev0's storage area, which is at storageOffset.
	Offset Offset16[[]byte]
}

type NameRecord struct {
	PlatformID PlatformID
	EncodingID EncodingID
	LanguageID uint16
	NameID     NameID
	Length     uint16
	// offset relative to NameTablev0's storage area, which is at storageOffset.
	StringOffset uint16
}
func parseLangTagRecord(buf []byte, out *LangTagRecord) int {
	*out = LangTagRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Length)
	parseOffset16(buf[2:4], &out.Offset)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseNameRecord(buf []byte, out *NameRecord) int {
	*out = NameRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parsePlatformID(buf[0:2], &out.PlatformID)
	parseEncodingID(buf[2:4], &out.EncodingID)
	parseUint16(buf[4:6], &out.LanguageID)
	parseNameID(buf[6:8], &out.NameID)
	parseUint16(buf[8:10], &out.Length)
	parseUint16(buf[10:12], &out.StringOffset)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseNameTable(buf []byte, out *NameTable) int {
	*out = NameTable{}
	origBuf := buf
	var dynSize int
	var Count uint16
	var storage Offset16[[]byte]
	var LangTagCount uint16

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseUint16(buf[2:4], &Count)
	parseOffset16(buf[4:6], &storage)
	{
		n := int(Count)
		/* FIXME: check that buf is long enough */
		out.nameRecords = buf[6 : 6+n*12]
		dynSize += n * 12
		buf = buf[6+n*12:]
	}

	{
		out.Data = origBuf[int(storage):]
	}

	if out.Version < 1 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &LangTagCount)
	{
		n := int(LangTagCount)
		/* FIXME: check that buf is long enough */
		out.langTagRecords = buf[2 : 2+n*4]
		dynSize += n * 4
		buf = buf[2+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *NameTable) NameRecord(i int) NameRecord {
	var out NameRecord
	parseNameRecord(tbl.nameRecords[i*12:(i+1)*12:len(tbl.nameRecords)], &out)
	return out
}

func (tbl *NameTable) NameRecords() iter.Seq2[int, NameRecord] {
	return func(yield func(int, NameRecord) bool) {
		for i := range tbl.NumNameRecords() {
			if !yield(i, tbl.NameRecord(i)) {
				return
			}
		}
	}
}

func (tbl *NameTable) NumNameRecords() int {
	return len(tbl.nameRecords) / 12
}

func (tbl *NameTable) LangTagRecord(i int) LangTagRecord {
	var out LangTagRecord
	parseLangTagRecord(tbl.langTagRecords[i*4:(i+1)*4:len(tbl.langTagRecords)], &out)
	return out
}

func (tbl *NameTable) LangTagRecords() iter.Seq2[int, LangTagRecord] {
	return func(yield func(int, LangTagRecord) bool) {
		for i := range tbl.NumLangTagRecords() {
			if !yield(i, tbl.LangTagRecord(i)) {
				return
			}
		}
	}
}

func (tbl *NameTable) NumLangTagRecords() int {
	return len(tbl.langTagRecords) / 4
}

