// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import (
	"encoding/binary"
)

type Weight uint16
type Width uint16
type FontSelection uint16

func parseWeight(buf []byte, out *Weight) int {
	*out = Weight(binary.BigEndian.Uint16(buf))
	return 0
}

func parseWidth(buf []byte, out *Width) int {
	*out = Width(binary.BigEndian.Uint16(buf))
	return 0
}

func parseFontSelection(buf []byte, out *FontSelection) int {
	*out = FontSelection(binary.BigEndian.Uint16(buf))
	return 0
}

const (
	WeightThin       Weight = 100 // thin
	WeightExtraLight Weight = 200 // extra-light
	WeightLight      Weight = 300 // light
	WeightNormal     Weight = 400 // normal
	WeightMedium     Weight = 500 // medium
	WeightSemiBold   Weight = 600 // semi-bold
	WeightBold       Weight = 700 // bold
	WeightExtraBold  Weight = 800 // extra-bold
	WeightBlack      Weight = 900 // black
)

const (
	WidthUltraCondensed Width = 1 // ultra-condensed
	WidthExtraCondensed Width = 2 // extra-condensed
	WidthCondensed      Width = 3 // condensed
	WidthSemiCondensed  Width = 4 // semi-condensed
	WidthMedium         Width = 5 // medium
	WidthSemiExpanded   Width = 6 // semi-expanded
	WidthExpanded       Width = 7 // expanded
	WidthExtraExpanded  Width = 8 // extra-expanded
	WidthUltraExpanded  Width = 9 // ultra-expanded
)

const (
	FsItalic         FontSelection = 1 << 0
	FsUnderscore     FontSelection = 1 << 1
	FsNegative       FontSelection = 1 << 2
	FsOutlined       FontSelection = 1 << 3
	FsStrikeout      FontSelection = 1 << 4
	FsBold           FontSelection = 1 << 5
	FsRegular        FontSelection = 1 << 6
	FsUseTypoMetrics FontSelection = 1 << 7
	FsWWS            FontSelection = 1 << 8
	FsOblique        FontSelection = 1 << 9
)

const (
	licenseInstallableEmbedding       = 0
	licenseRestrictedLicenseEmbedding = 2
	licensePreviewAndPrintEmbedding   = 4
	licenseEditableEmbedding          = 8
)

type OS2Table struct {
	Version             uint16
	XAvgCharWidth       int16
	UsWeightClass       Weight
	UsWidthClass        Width
	FsType              uint16
	YSubscriptXSize     int16
	YSubscriptYSize     int16
	YSubscriptXOffset   int16
	YSubscriptYOffset   int16
	YSuperscriptXSize   int16
	YSuperscriptYSize   int16
	YSuperscriptXOffset int16
	YSuperscriptYOffset int16
	YStrikeoutSize      int16
	YStrikeoutPosition  int16
	SFamilyClass        int16
	PANOSE              [10]uint8
	UlUnicodeRange      [4]uint32
	AchVendID           Tag
	FsSelection         FontSelection
	UsFirstCharIndex    uint16
	UsLastCharIndex     uint16

	STypoAscender  int16
	STypoDescender int16
	STypoLineGap   int16
	UsWinAscent    uint16
	UsWinDescent   uint16

	UlCodePageRange1 [2]uint32

	SxHeight      int16
	SCapHeight    int16
	UsDefaultChar uint16
	UsBreakChar   uint16
	UsMaxContext  uint16

	UsLowerOpticalPointSize uint16
	UsUpperOpticalPointSize uint16
}
func ParseOS2Table(buf []byte, out *OS2Table) int {
	*out = OS2Table{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 68 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseInt16(buf[2:4], &out.XAvgCharWidth)
	parseWeight(buf[4:6], &out.UsWeightClass)
	parseWidth(buf[6:8], &out.UsWidthClass)
	parseUint16(buf[8:10], &out.FsType)
	parseInt16(buf[10:12], &out.YSubscriptXSize)
	parseInt16(buf[12:14], &out.YSubscriptYSize)
	parseInt16(buf[14:16], &out.YSubscriptXOffset)
	parseInt16(buf[16:18], &out.YSubscriptYOffset)
	parseInt16(buf[18:20], &out.YSuperscriptXSize)
	parseInt16(buf[20:22], &out.YSuperscriptYSize)
	parseInt16(buf[22:24], &out.YSuperscriptXOffset)
	parseInt16(buf[24:26], &out.YSuperscriptYOffset)
	parseInt16(buf[26:28], &out.YStrikeoutSize)
	parseInt16(buf[28:30], &out.YStrikeoutPosition)
	parseInt16(buf[30:32], &out.SFamilyClass)
	out.PANOSE = [10]byte(buf[32:42])
	{
		buf := buf[42:58]
		into := &out.UlUnicodeRange
		parseUint32(buf[0:4], &into[0])
		parseUint32(buf[4:8], &into[1])
		parseUint32(buf[8:12], &into[2])
		parseUint32(buf[12:16], &into[3])
	}

	parseTag(buf[58:62], &out.AchVendID)
	parseFontSelection(buf[62:64], &out.FsSelection)
	parseUint16(buf[64:66], &out.UsFirstCharIndex)
	parseUint16(buf[66:68], &out.UsLastCharIndex)

	if len(buf) < 78 {
		return dynSize
	}
	parseInt16(buf[68:70], &out.STypoAscender)
	parseInt16(buf[70:72], &out.STypoDescender)
	parseInt16(buf[72:74], &out.STypoLineGap)
	parseUint16(buf[74:76], &out.UsWinAscent)
	parseUint16(buf[76:78], &out.UsWinDescent)

	if out.Version < 1 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 86 {
		return dynSize
	}
	{
		buf := buf[78:86]
		into := &out.UlCodePageRange1
		parseUint32(buf[0:4], &into[0])
		parseUint32(buf[4:8], &into[1])
	}

	if out.Version < 2 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 96 {
		return dynSize
	}
	parseInt16(buf[86:88], &out.SxHeight)
	parseInt16(buf[88:90], &out.SCapHeight)
	parseUint16(buf[90:92], &out.UsDefaultChar)
	parseUint16(buf[92:94], &out.UsBreakChar)
	parseUint16(buf[94:96], &out.UsMaxContext)

	if out.Version < 5 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 100 {
		return dynSize
	}
	parseUint16(buf[96:98], &out.UsLowerOpticalPointSize)
	parseUint16(buf[98:100], &out.UsUpperOpticalPointSize)
	_ = buf
	_ = origBuf
	return dynSize
}

