// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type PCLTTable struct {
	MajorVersion        uint16
	MinorVersion        uint16
	FontNumber          uint32
	Pitch               uint16
	XHeight             uint16
	Style               uint16
	TypeFamily          uint16
	CapHeight           uint16
	SymbolSet           uint16
	Typeface            [16]uint8
	CharacterComplement [8]uint8
	FileName            [6]uint8
	StrokeWeight        int8
	WidthType           int8
	SerifStyle          uint8
}
func ParsePCLTTable(buf []byte, out *PCLTTable) int {
	*out = PCLTTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 54 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseUint32(buf[4:8], &out.FontNumber)
	parseUint16(buf[8:10], &out.Pitch)
	parseUint16(buf[10:12], &out.XHeight)
	parseUint16(buf[12:14], &out.Style)
	parseUint16(buf[14:16], &out.TypeFamily)
	parseUint16(buf[16:18], &out.CapHeight)
	parseUint16(buf[18:20], &out.SymbolSet)
	out.Typeface = [16]byte(buf[20:36])
	out.CharacterComplement = [8]byte(buf[36:44])
	out.FileName = [6]byte(buf[44:50])
	out.StrokeWeight = int8(buf[50:51][0])
	out.WidthType = int8(buf[51:52][0])
	out.SerifStyle = buf[52:53][0]
	_ = buf
	_ = origBuf
	return dynSize
}

