// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type PrepTable struct {
	Data []byte
}
func ParsePrepTable(buf []byte, out *PrepTable) int {
	*out = PrepTable{}
	origBuf := buf
	var dynSize int

	{
		out.Data = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

