// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type SbixTable struct {
	Version uint16
	Flags   uint16

	strikeOffsets Slice[Offset32[Strike]]
}

type Strike struct {
	Ppem uint16
	PPI  uint16

	// maxp.numGlyphs+1 entries. The Slice may contain arbitrary trailing data. Offsets
	// are relative to Strike.
	glyphDataOffsets Slice[Offset32[GlyphData]]
}

type GlyphData struct {
	OriginalOffsetX int16
	OriginalOffsetY int16
	// One of "jpg ", "png ", "tiff", or "dupe".
	GraphicType Tag
	// Actual length is determined by delta of offsets in Strike.glyphDataOffsets.
	Data []byte
}
func parseGlyphData(buf []byte, out *GlyphData) int {
	*out = GlyphData{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseInt16(buf[0:2], &out.OriginalOffsetX)
	parseInt16(buf[2:4], &out.OriginalOffsetY)
	parseTag(buf[4:8], &out.GraphicType)
	{
		out.Data = buf[8:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func ParseSbixTable(buf []byte, out *SbixTable) int {
	*out = SbixTable{}
	origBuf := buf
	var dynSize int
	var numStrikes uint32

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseUint16(buf[2:4], &out.Flags)
	parseUint32(buf[4:8], &numStrikes)
	{
		n := int(numStrikes)
		/* FIXME: check that buf is long enough */
		out.strikeOffsets = buf[8 : 8+n*4]
		dynSize += n * 4
		buf = buf[8+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SbixTable) NumStrikeOffsets() int {
	return len(tbl.strikeOffsets) / 4
}

func parseStrike(buf []byte, out *Strike) int {
	*out = Strike{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Ppem)
	parseUint16(buf[2:4], &out.PPI)
	{
		out.glyphDataOffsets = buf[4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *Strike) NumGlyphDataOffsets() int {
	return len(tbl.glyphDataOffsets) / 4
}

