// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type STATTable struct {
	data []byte

	MajorVersion   uint16
	MinorVersion   uint16
	designAxisSize uint16

	designAxesOffset uint32

	offsetToAxisValueOffsets uint32

	ElidedFallbackNameID NameID

	designAxes       Slice[AxisRecord]
	axisValueOffsets Slice[Offset16[AxisValueTable]]
}

type AxisRecord struct {
	AxisTag      Tag
	AxisNameID   NameID
	AxisOrdering uint16
}

type AxisValueTable struct {
	Format  uint16
	Format1 AxisValueTableFormat1
	Format2 AxisValueTableFormat2
	Format3 AxisValueTableFormat3
	Format4 AxisValueTableFormat4
}

type AxisValueTableFormat1 struct {
	AxisIndex   uint16
	Flags       uint16
	ValueNameID NameID
	Value       Int16_16
}

type AxisValueTableFormat2 struct {
	AxisIndex     uint16
	Flags         uint16
	ValueNameID   NameID
	NominalValue  Int16_16
	RangeMinValue Int16_16
	RangeMaxValue Int16_16
}

type AxisValueTableFormat3 struct {
	AxisIndex   uint16
	Flags       uint16
	ValueNameID NameID
	Value       Int16_16
	LinkedValue Int16_16
}

type AxisValueTableFormat4 struct {
	Flags       uint16
	ValueNameID NameID
	axisValues  Slice[AxisValue]
}

type AxisValue struct {
	AxisIndex uint16
	Value     Int16_16
}
func parseAxisRecord(buf []byte, out *AxisRecord) int {
	*out = AxisRecord{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseTag(buf[0:4], &out.AxisTag)
	parseNameID(buf[4:6], &out.AxisNameID)
	parseUint16(buf[6:8], &out.AxisOrdering)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseAxisValue(buf []byte, out *AxisValue) int {
	*out = AxisValue{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.AxisIndex)
	parseInt16_16(buf[2:6], &out.Value)
	_ = buf
	_ = origBuf
	return dynSize
}

func ParseAxisValueTable(buf []byte, out *AxisValueTable) int {
	*out = AxisValueTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)

	switch out.Format {
	case 1:
		parseAxisValueTableFormat1(buf[2:12], &out.Format1)
	case 2:
		parseAxisValueTableFormat2(buf[2:20], &out.Format2)
	case 3:
		parseAxisValueTableFormat3(buf[2:16], &out.Format3)
	case 4:
		dynSize += parseAxisValueTableFormat4(buf[2:], &out.Format4)
	}
	_ = buf
	_ = origBuf
	return dynSize
}

func parseAxisValueTableFormat1(buf []byte, out *AxisValueTableFormat1) int {
	*out = AxisValueTableFormat1{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 10 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.AxisIndex)
	parseUint16(buf[2:4], &out.Flags)
	parseNameID(buf[4:6], &out.ValueNameID)
	parseInt16_16(buf[6:10], &out.Value)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseAxisValueTableFormat2(buf []byte, out *AxisValueTableFormat2) int {
	*out = AxisValueTableFormat2{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 18 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.AxisIndex)
	parseUint16(buf[2:4], &out.Flags)
	parseNameID(buf[4:6], &out.ValueNameID)
	parseInt16_16(buf[6:10], &out.NominalValue)
	parseInt16_16(buf[10:14], &out.RangeMinValue)
	parseInt16_16(buf[14:18], &out.RangeMaxValue)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseAxisValueTableFormat3(buf []byte, out *AxisValueTableFormat3) int {
	*out = AxisValueTableFormat3{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 14 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.AxisIndex)
	parseUint16(buf[2:4], &out.Flags)
	parseNameID(buf[4:6], &out.ValueNameID)
	parseInt16_16(buf[6:10], &out.Value)
	parseInt16_16(buf[10:14], &out.LinkedValue)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseAxisValueTableFormat4(buf []byte, out *AxisValueTableFormat4) int {
	*out = AxisValueTableFormat4{}
	origBuf := buf
	var dynSize int
	var axisCount uint16

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &axisCount)
	parseUint16(buf[2:4], &out.Flags)
	parseNameID(buf[4:6], &out.ValueNameID)
	{
		n := int(axisCount)
		/* FIXME: check that buf is long enough */
		out.axisValues = buf[6 : 6+n*6]
		dynSize += n * 6
		buf = buf[6+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *AxisValueTableFormat4) AxisValue(i int) AxisValue {
	var out AxisValue
	parseAxisValue(tbl.axisValues[i*6:(i+1)*6:len(tbl.axisValues)], &out)
	return out
}

func (tbl *AxisValueTableFormat4) AxisValues() iter.Seq2[int, AxisValue] {
	return func(yield func(int, AxisValue) bool) {
		for i := range tbl.NumAxisValues() {
			if !yield(i, tbl.AxisValue(i)) {
				return
			}
		}
	}
}

func (tbl *AxisValueTableFormat4) NumAxisValues() int {
	return len(tbl.axisValues) / 6
}

func ParseSTATTable(buf []byte, out *STATTable) int {
	*out = STATTable{}
	origBuf := buf
	var dynSize int
	var designAxisCount uint16
	var axisValueCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 18 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseUint16(buf[2:4], &out.MinorVersion)
	parseUint16(buf[4:6], &out.designAxisSize)
	parseUint16(buf[6:8], &designAxisCount)
	parseUint32(buf[8:12], &out.designAxesOffset)
	parseUint16(buf[12:14], &axisValueCount)
	parseUint32(buf[14:18], &out.offsetToAxisValueOffsets)

	if out.MajorVersion < 1 {
		return dynSize
	}
	if out.MajorVersion == 1 && out.MinorVersion < 1 {
		return dynSize
	}
	/* FIXME return error */
	if len(buf) < 20 {
		return dynSize
	}
	parseNameID(buf[18:20], &out.ElidedFallbackNameID)
	{
		sz := int(out.designAxisSize)
		n := int(designAxisCount)
		start := int(out.designAxesOffset)
		/* FIXME: check that buf is long enough */
		out.designAxes = origBuf[start : start+n*sz]
	}

	{
		n := int(axisValueCount)
		start := int(out.offsetToAxisValueOffsets)
		/* FIXME: check that buf is long enough */
		out.axisValueOffsets = origBuf[start : start+n*2]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *STATTable) DesignAxis(i int) AxisRecord {
	sz := int(tbl.designAxisSize)
	var out AxisRecord
	parseAxisRecord(tbl.designAxes[i*sz:(i+1)*sz:len(tbl.designAxes)], &out)
	return out
}

func (tbl *STATTable) DesignAxes() iter.Seq2[int, AxisRecord] {
	return func(yield func(int, AxisRecord) bool) {
		for i := range tbl.NumDesignAxes() {
			if !yield(i, tbl.DesignAxis(i)) {
				return
			}
		}
	}
}

func (tbl *STATTable) NumDesignAxes() int {
	return len(tbl.designAxes) / int(tbl.designAxisSize)
}

func (tbl *STATTable) NumAxisValueOffsets() int {
	return len(tbl.axisValueOffsets) / 2
}

