// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type SVGTable struct {
	data []byte

	Version            uint16
	documentListOffset Offset32[SVGDocumentList]
}

type SVGDocumentList struct {
	data []byte

	documentRecords Slice[SVGDocumentRecord]
}

type SVGDocumentRecord struct {
	parentData []byte

	StartGlyphID uint16
	EndGlyphID   uint16

	Data []byte
}
func parseSVGDocumentList(buf []byte, out *SVGDocumentList) int {
	*out = SVGDocumentList{}
	origBuf := buf
	var dynSize int
	var numEntries uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 2 {
		return dynSize
	}
	parseUint16(buf[0:2], &numEntries)
	{
		n := int(numEntries)
		/* FIXME: check that buf is long enough */
		out.documentRecords = buf[2 : 2+n*12]
		dynSize += n * 12
		buf = buf[2+n*12:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *SVGDocumentList) DocumentRecord(i int) SVGDocumentRecord {
	var out SVGDocumentRecord
	parseSVGDocumentRecord(tbl.documentRecords[i*12:(i+1)*12:len(tbl.documentRecords)], tbl.data, &out)
	return out
}

func (tbl *SVGDocumentList) DocumentRecords() iter.Seq2[int, SVGDocumentRecord] {
	return func(yield func(int, SVGDocumentRecord) bool) {
		for i := range tbl.NumDocumentRecords() {
			if !yield(i, tbl.DocumentRecord(i)) {
				return
			}
		}
	}
}

func (tbl *SVGDocumentList) NumDocumentRecords() int {
	return len(tbl.documentRecords) / 12
}

func parseSVGDocumentRecord(buf, parentBuf []byte, out *SVGDocumentRecord) int {
	*out = SVGDocumentRecord{}
	origBuf := buf
	var dynSize int
	var svgDocOffset uint32
	var svgDocLength uint32
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.StartGlyphID)
	parseUint16(buf[2:4], &out.EndGlyphID)
	parseUint32(buf[4:8], &svgDocOffset)
	parseUint32(buf[8:12], &svgDocLength)
	{
		n := int(svgDocLength)
		start := int(svgDocOffset)
		/* FIXME: check that buf is long enough */
		out.Data = parentBuf[start : start+n*1]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func ParseSVGTable(buf []byte, out *SVGTable) int {
	*out = SVGTable{}
	origBuf := buf
	var dynSize int
	out.data = buf

	/* FIXME return error */
	if len(buf) < 10 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Version)
	parseOffset32(buf[2:6], &out.documentListOffset)
	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *SVGTable) DocumentList(into *SVGDocumentList) bool {
	// FIXME: check bounds
	if tbl.documentListOffset == 0 {
		return false
	}
	parseSVGDocumentList(tbl.data[tbl.documentListOffset:], into)
	return true
}


