// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type TableDirectory struct {
	data []byte

	SfntVersion uint32

	// The following 3 fields shouldn't be used and should instead be derived from NumTables.

	// Followed by numTables rawTableRecords, sorted in ascending order by tag.
	tableRecords Slice[TableRecord]
}

type TableRecord struct {
	parentData []byte

	Tag      Tag
	Checksum uint32
	Offset   Offset32[any]
	Length   uint32
}
func ParseTableDirectory(buf []byte, out *TableDirectory) int {
	*out = TableDirectory{}
	origBuf := buf
	var dynSize int
	var numTables uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 12 {
		return dynSize
	}
	parseUint32(buf[0:4], &out.SfntVersion)
	parseUint16(buf[4:6], &numTables)
	{
		n := int(numTables)
		/* FIXME: check that buf is long enough */
		out.tableRecords = buf[12 : 12+n*16]
		dynSize += n * 16
		buf = buf[12+n*16:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *TableDirectory) TableRecord(i int) TableRecord {
	var out TableRecord
	parseTableRecord(tbl.tableRecords[i*16:(i+1)*16:len(tbl.tableRecords)], tbl.data, &out)
	return out
}

func (tbl *TableDirectory) TableRecords() iter.Seq2[int, TableRecord] {
	return func(yield func(int, TableRecord) bool) {
		for i := range tbl.NumTableRecords() {
			if !yield(i, tbl.TableRecord(i)) {
				return
			}
		}
	}
}

func (tbl *TableDirectory) NumTableRecords() int {
	return len(tbl.tableRecords) / 16
}

func parseTableRecord(buf, parentBuf []byte, out *TableRecord) int {
	*out = TableRecord{}
	origBuf := buf
	var dynSize int
	out.parentData = parentBuf

	/* FIXME return error */
	if len(buf) < 16 {
		return dynSize
	}
	parseTag(buf[0:4], &out.Tag)
	parseUint32(buf[4:8], &out.Checksum)
	parseOffset32(buf[8:12], &out.Offset)
	parseUint32(buf[12:16], &out.Length)
	_ = buf
	_ = origBuf
	return dynSize
}

