// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

import "iter"

type ItemVariationStoreTable struct {
	data []byte

	Format                    uint16
	variationRegionListOffset Offset32[VariationRegionList]

	itemVariationDataOffsets Slice[Offset32[ItemVariationDataSubtable]]
}

type ItemVariationDataSubtable struct {
	ItemCount      uint16
	WordDeltaCount uint16

	regionIndexes Slice[uint16]
	DeltaSets     []byte
}

type VariationRegionList struct {
	AxisCount        uint16
	RegionCount      uint16
	variationRegions Slice[RegionAxisCoordinates]
}

type RegionAxisCoordinates struct {
	StartCoord Int2_14
	PeakCoord  Int2_14
	EndCoord   Int2_14
}
func parseItemVariationDataSubtable(buf []byte, out *ItemVariationDataSubtable) int {
	*out = ItemVariationDataSubtable{}
	origBuf := buf
	var dynSize int
	var regionIndexCount uint16

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.ItemCount)
	parseUint16(buf[2:4], &out.WordDeltaCount)
	parseUint16(buf[4:6], &regionIndexCount)
	{
		n := int(regionIndexCount)
		/* FIXME: check that buf is long enough */
		out.regionIndexes = buf[6 : 6+n*2]
		dynSize += n * 2
		buf = buf[6+n*2:]
	}

	{
		out.DeltaSets = buf[0:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *ItemVariationDataSubtable) RegionIndex(i int) uint16 {
	var out uint16
	parseUint16(tbl.regionIndexes[i*2:(i+1)*2:len(tbl.regionIndexes)], &out)
	return out
}

func (tbl *ItemVariationDataSubtable) RegionIndexes() iter.Seq2[int, uint16] {
	return func(yield func(int, uint16) bool) {
		for i := range tbl.NumRegionIndexes() {
			if !yield(i, tbl.RegionIndex(i)) {
				return
			}
		}
	}
}

func (tbl *ItemVariationDataSubtable) NumRegionIndexes() int {
	return len(tbl.regionIndexes) / 2
}

func ParseItemVariationStoreTable(buf []byte, out *ItemVariationStoreTable) int {
	*out = ItemVariationStoreTable{}
	origBuf := buf
	var dynSize int
	var itemVariationDataCount uint16
	out.data = buf

	/* FIXME return error */
	if len(buf) < 8 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.Format)
	parseOffset32(buf[2:6], &out.variationRegionListOffset)
	parseUint16(buf[6:8], &itemVariationDataCount)
	{
		n := int(itemVariationDataCount)
		/* FIXME: check that buf is long enough */
		out.itemVariationDataOffsets = buf[8 : 8+n*4]
		dynSize += n * 4
		buf = buf[8+n*4:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}
func (tbl *ItemVariationStoreTable) VariationRegionList(into *VariationRegionList) bool {
	// FIXME: check bounds
	if tbl.variationRegionListOffset == 0 {
		return false
	}
	parseVariationRegionList(tbl.data[tbl.variationRegionListOffset:], into)
	return true
}

func (tbl *ItemVariationStoreTable) NumItemVariationDataOffsets() int {
	return len(tbl.itemVariationDataOffsets) / 4
}

func parseRegionAxisCoordinates(buf []byte, out *RegionAxisCoordinates) int {
	*out = RegionAxisCoordinates{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 6 {
		return dynSize
	}
	parseInt2_14(buf[0:2], &out.StartCoord)
	parseInt2_14(buf[2:4], &out.PeakCoord)
	parseInt2_14(buf[4:6], &out.EndCoord)
	_ = buf
	_ = origBuf
	return dynSize
}

func parseVariationRegionList(buf []byte, out *VariationRegionList) int {
	*out = VariationRegionList{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 4 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.AxisCount)
	parseUint16(buf[2:4], &out.RegionCount)
	{
		n := int(out.AxisCount) * int(out.RegionCount)
		/* FIXME: check that buf is long enough */
		out.variationRegions = buf[4 : 4+n*6]
		dynSize += n * 6
		buf = buf[4+n*6:]
	}

	_ = buf
	_ = origBuf
	return dynSize
}

func (tbl *VariationRegionList) VariationRegion(i int) RegionAxisCoordinates {
	var out RegionAxisCoordinates
	parseRegionAxisCoordinates(tbl.variationRegions[i*6:(i+1)*6:len(tbl.variationRegions)], &out)
	return out
}

func (tbl *VariationRegionList) VariationRegions() iter.Seq2[int, RegionAxisCoordinates] {
	return func(yield func(int, RegionAxisCoordinates) bool) {
		for i := range tbl.NumVariationRegions() {
			if !yield(i, tbl.VariationRegion(i)) {
				return
			}
		}
	}
}

func (tbl *VariationRegionList) NumVariationRegions() int {
	return len(tbl.variationRegions) / 6
}

