// Code generated by honnef.co/go/gutter/internal/cmd/gen_parser. DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Dominik Honnef and contributors
//
// SPDX-License-Identifier: MIT

package opentype

type VheaTable struct {
	MajorVersion uint16
	MinorVersion uint16

	VertTypoAscendender  int16
	VertTypoDescender    int16
	VertTypoLineGap      int16
	AdvanceHeightMax     int16
	MinTopSideBearing    int16
	MinBottomSideBearing int16
	YMaxExtent           int16
	CaretSlopeRise       int16
	CaretSlopeRun        int16
	CaretOffset          int16

	MetricDataFormat    int16
	NumOfLongVerMetrics uint16
}
func ParseVheaTable(buf []byte, out *VheaTable) int {
	*out = VheaTable{}
	origBuf := buf
	var dynSize int

	/* FIXME return error */
	if len(buf) < 36 {
		return dynSize
	}
	parseUint16(buf[0:2], &out.MajorVersion)
	/* XXX return error */
	if out.MajorVersion > 1 {
		return dynSize
	}
	parseWeirdMinorVersion(buf[2:4], &out.MinorVersion)
	parseInt16(buf[4:6], &out.VertTypoAscendender)
	parseInt16(buf[6:8], &out.VertTypoDescender)
	parseInt16(buf[8:10], &out.VertTypoLineGap)
	parseInt16(buf[10:12], &out.AdvanceHeightMax)
	parseInt16(buf[12:14], &out.MinTopSideBearing)
	parseInt16(buf[14:16], &out.MinBottomSideBearing)
	parseInt16(buf[16:18], &out.YMaxExtent)
	parseInt16(buf[18:20], &out.CaretSlopeRise)
	parseInt16(buf[20:22], &out.CaretSlopeRun)
	parseInt16(buf[22:24], &out.CaretOffset)
	parseInt16(buf[32:34], &out.MetricDataFormat)
	parseUint16(buf[34:36], &out.NumOfLongVerMetrics)
	_ = buf
	_ = origBuf
	return dynSize
}

