// Code generated by "stringer -type=StateTransitionKind"; DO NOT EDIT.

package widget

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInitializing-0]
	_ = x[StateUpdatedWidget-1]
	_ = x[StateChangedDependencies-2]
	_ = x[StateDeactivating-3]
	_ = x[StateActivating-4]
	_ = x[StateDisposing-5]
}

const _StateTransitionKind_name = "StateInitializingStateUpdatedWidgetStateChangedDependenciesStateDeactivatingStateActivatingStateDisposing"

var _StateTransitionKind_index = [...]uint8{0, 17, 35, 59, 76, 91, 105}

func (i StateTransitionKind) String() string {
	if i >= StateTransitionKind(len(_StateTransitionKind_index)-1) {
		return "StateTransitionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateTransitionKind_name[_StateTransitionKind_index[i]:_StateTransitionKind_index[i+1]]
}
