// Code generated by "stringer -type=FillRule -trimprefix=FillRule"; DO NOT EDIT.

package gfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NonZero-0]
	_ = x[EvenOdd-1]
}

const _FillRule_name = "NonZeroEvenOdd"

var _FillRule_index = [...]uint8{0, 7, 14}

func (i FillRule) String() string {
	if i < 0 || i >= FillRule(len(_FillRule_index)-1) {
		return "FillRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FillRule_name[_FillRule_index[i]:_FillRule_index[i+1]]
}
