// Code generated by "stringer -type=GradientExtend -trimprefix=GradientExtend"; DO NOT EDIT.

package gfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GradientExtendPad-0]
	_ = x[GradientExtendRepeat-1]
	_ = x[GradientExtendReflect-2]
}

const _GradientExtend_name = "PadRepeatReflect"

var _GradientExtend_index = [...]uint8{0, 3, 9, 16}

func (i GradientExtend) String() string {
	if i < 0 || i >= GradientExtend(len(_GradientExtend_index)-1) {
		return "GradientExtend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GradientExtend_name[_GradientExtend_index[i]:_GradientExtend_index[i+1]]
}
