// Code generated by "stringer -type=Mix -trimprefix=Mix"; DO NOT EDIT.

package gfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MixNormal-0]
	_ = x[MixMultiply-1]
	_ = x[MixScreen-2]
	_ = x[MixOverlay-3]
	_ = x[MixDarken-4]
	_ = x[MixLighten-5]
	_ = x[MixColorDodge-6]
	_ = x[MixColorBurn-7]
	_ = x[MixHardLight-8]
	_ = x[MixSoftLight-9]
	_ = x[MixDifference-10]
	_ = x[MixExclusion-11]
}

const _Mix_name = "NormalMultiplyScreenOverlayDarkenLightenColorDodgeColorBurnHardLightSoftLightDifferenceExclusion"

var _Mix_index = [...]uint8{0, 6, 14, 20, 27, 33, 40, 50, 59, 68, 77, 87, 96}

func (i Mix) String() string {
	if i >= Mix(len(_Mix_index)-1) {
		return "Mix(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mix_name[_Mix_index[i]:_Mix_index[i+1]]
}
